select json_build_object(
 'installer', current_user, 'server_version', current_setting('server_version'),
 'public_tables', (select count(*) from pg_tables where schemaname='public'),
 'public_functions', (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'),
 'security_definer', (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef),
 'anon_execute', (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and has_function_privilege('anon',p.oid,'EXECUTE')),
 'authenticated_execute', (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and has_function_privilege('authenticated',p.oid,'EXECUTE')),
 'service_role_execute', (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and has_function_privilege('service_role',p.oid,'EXECUTE')),
 'anon_sequences', (select count(*) from pg_sequences s where s.schemaname='public' and has_sequence_privilege('anon', quote_ident(s.schemaname)||'.'||quote_ident(s.sequencename), 'USAGE,SELECT,UPDATE')),
 'gated_present', (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in (__GATED_NAMES__)),
 'gated_anon_execute', (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in (__GATED_NAMES__) and has_function_privilege('anon',p.oid,'EXECUTE')),
 'gated_authenticated_execute', (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in (__GATED_NAMES__) and has_function_privilege('authenticated',p.oid,'EXECUTE')),
 'gated_service_role_execute', (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in (__GATED_NAMES__) and has_function_privilege('service_role',p.oid,'EXECUTE')),
 'p0_authenticated_execute', has_function_privilege('authenticated','public.review_tournament_team_entry(uuid,uuid,text,text,jsonb)','EXECUTE'),
 'identity_rls', (select c.relrowsecurity and c.relforcerowsecurity from pg_class c where c.oid='public.torneos_identity'::regclass),
 'roles', (select json_agg(json_build_object('rolname',rolname,'login',rolcanlogin,'inherit',rolinherit,'super',rolsuper,'bypassrls',rolbypassrls) order by rolname) from pg_roles where rolname like 'torneos%'),
 'writer_members', (select json_agg(m.rolname order by m.rolname) from pg_auth_members am join pg_roles r on r.oid=am.roleid join pg_roles m on m.oid=am.member where r.rolname='torneos_identity_writer'),
 'adapter_members', (select json_agg(m.rolname order by m.rolname) from pg_auth_members am join pg_roles r on r.oid=am.roleid join pg_roles m on m.oid=am.member where r.rolname='torneos_core_adapter'),
 'pre_request', (select json_agg(c) from pg_roles r, unnest(r.rolconfig) c where r.rolname='authenticator' and c like 'pgrst.db_pre_request=%'),
 'extensions', (select json_agg(extname||' '||extversion order by extname) from pg_extension),
 'foreign_servers', (select count(*) from pg_foreign_server),
 'table_owners', (select json_agg(distinct pg_get_userbyid(c.relowner)) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'),
 'function_owners', (select json_agg(distinct pg_get_userbyid(p.proowner)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'),
 'seeds', json_build_object('sport_modalities',(select count(*) from public.tournament_sport_modalities),'competition_formats',(select count(*) from public.tournament_competition_formats),'role_capabilities',(select count(*) from public.tournament_organization_role_capabilities),'plan_catalog',(select count(*) from public.tournament_plan_catalog)),
 'cron_jobs', (select case when to_regclass('cron.job') is null then -1 else (xpath('/row/c/text()', query_to_xml('select count(*) as c from cron.job', false, true, '')))[1]::text::bigint end),
 'storage_buckets', (select case when to_regclass('storage.buckets') is null then -1 else (xpath('/row/c/text()', query_to_xml('select count(*) as c from storage.buckets', false, true, '')))[1]::text::bigint end)
)
