// COMPETITION-V1 samples shared by competition-adapter.test.mjs and adapter.test.mjs: one representative
// input per competition alias (the shape the pages send), the composite aliases and the legacy aliases the
// hybrid adapter must not offer.
export const ORG = '33333333-3333-4333-8333-333333333333';
export const scope = { organizationId: ORG, tournamentId: 't1', categoryId: 'c1' };

// One representative input per alias, in the shape the pages send (undefined/empty values included on purpose).
export const COMPETITION_SAMPLE = {
  loadFixtureContext: [ORG, 't1', 'c1'],
  loadScheduleContext: [ORG, 't1', 'c1'],
  freezeParticipants: [{ ...scope, idempotencyKey: 'k1' }],
  reopenParticipants: [{ ...scope, reason: 'Faltaba un equipo' }],
  saveDrawPots: [{ ...scope, pots: [{ potNumber: 1, participantIds: ['p1'] }] }],
  executeGroupDraw: [{ ...scope, groupCount: 2, seed: 's', publish: 1 }],
  generateFixture: [{ ...scope, seed: '', configuration: undefined, idempotencyKey: 'k2' }],
  createManualFixture: [{ ...scope, sourceFixtureVersionId: undefined, idempotencyKey: 'k3' }],
  updateDraftFixture: [{ organizationId: ORG, fixtureVersionId: 'v1', action: 'create_round', payload: undefined }],
  validateFixture: [{ organizationId: ORG, fixtureVersionId: 'v1' }],
  publishFixture: [{ organizationId: ORG, fixtureVersionId: 'v1' }],
  appendPlayoffPhase: [{ ...scope, sourcePhaseId: 'ph1', qualifierCount: 2, doubleLeg: 0, idempotencyKey: 'k4' }],
  supersedeFixture: [{ organizationId: ORG, fixtureVersionId: 'v1', idempotencyKey: 'k5' }],
  createVenue: [{ organizationId: ORG, name: 'Club', address: 'Calle 1', latitude: 0, locality: '', timezone: '' }],
  createCourt: [{ organizationId: ORG, venueId: 've1', name: 'Cancha 1', sportModality: 'football_5' }],
  saveScheduleWindows: [{ organizationId: ORG, tournamentId: 't1', windows: [{ dayOfWeek: 1, startsAt: '08:00', endsAt: '23:00' }] }],
  validateMatchSchedule: [{ organizationId: ORG, matchId: 'm1', scheduledAt: '2030-01-01T18:00:00Z', venueId: 've1', courtId: 'co1', durationMinutes: 60 }],
  scheduleMatch: [{ organizationId: ORG, matchId: 'm1', scheduledAt: '2030-01-01T18:00:00Z', venueId: 've1', courtId: 'co1', durationMinutes: 60, overrideWarnings: 1, overrideReason: '' }],
  rescheduleMatch: [{ organizationId: ORG, matchId: 'm1', scheduledAt: '2030-01-02T18:00:00Z', venueId: 've1', courtId: 'co1', durationMinutes: 60, reason: 'Lluvia' }],
  autoScheduleMatches: [{ organizationId: ORG, fixtureVersionId: 'v1' }],
  respondMatchAvailability: [{ matchId: 'm1', response: 'available' }],
  loadMatchSquad: [{ organizationId: ORG, matchId: 'm1', teamEntryId: 'e1' }],
  loadMyManagedMatchSquad: ['m1'],
  saveMatchSquad: [{ organizationId: ORG, matchId: 'm1', teamEntryId: 'e1', players: [{ rosterPlayerId: 'rp1' }] }],
  submitMatchSquad: [{ organizationId: ORG, matchId: 'm1', teamEntryId: 'e1' }],
  loadMatchOperations: [{ organizationId: ORG, tournamentId: 't1', categoryId: undefined }],
  loadMatchOperation: [{ organizationId: ORG, operationId: 'o1' }],
  openMatchOperation: [{ organizationId: ORG, matchId: 'm1', overrideReason: '' }],
  setMatchOutcome: [{ organizationId: ORG, operationId: 'o1', outcome: { outcomeType: 'played', countsForStandings: true } }],
  setMatchScore: [{ organizationId: ORG, operationId: 'o1', score: { homeScore: 2, awayScore: 1, scoreType: 'played' } }],
  addMatchEvent: [{ organizationId: ORG, operationId: 'o1', event: { eventType: 'goal', minute: 10 } }],
  voidMatchEvent: [{ organizationId: ORG, eventId: 'ev1', reason: 'Error de carga' }],
  submitMatchOperation: [{ organizationId: ORG, operationId: 'o1' }],
  reviewMatchOperation: [{ organizationId: ORG, operationId: 'o1', decision: 'approved', reason: 'OK acta' }],
  validateMatchOperation: [{ organizationId: ORG, operationId: 'o1' }],
  makeMatchOfficial: [{ organizationId: ORG, operationId: 'o1' }],
  requestMatchCorrection: [{ organizationId: ORG, operationId: 'o1', reason: 'Gol mal cargado' }],
  createMatchCorrection: [{ organizationId: ORG, operationId: 'o1' }],
  loadStandings: [{ ...scope, phaseId: 'ph1', groupId: undefined }],
  loadStatistics: [{ ...scope, phaseId: 'ph1', groupId: 'g1' }],
  rebuildStandings: [{ ...scope, phaseId: 'ph1', reason: 'Recalculo', idempotencyKey: undefined }],
  publishStandings: [{ revisionId: 'r1', reason: 'Publicar' }],
  resolveQualification: [{ revisionId: 'r1', reason: 'Desempate' }],
  startCompetition: [{ organizationId: ORG, tournamentId: 't1' }],
  finishCompetition: [{ organizationId: ORG, tournamentId: 't1' }],
  reopenCompetition: [{ organizationId: ORG, tournamentId: 't1', reason: 'Corrección' }],
  withdrawCompetitionParticipant: [{ organizationId: ORG, tournamentId: 't1', teamEntryId: 'e1', reasonCode: 'voluntary_resignation' }],
  setHubCategory: [{ tournamentId: 't1', categoryId: 'c1' }],
  loadPublishedMatches: [{ tournamentId: 't1', categoryId: 'c1' }],
  loadParticipantMatch: ['m1'],
  loadPublishedTeams: [{ tournamentId: 't1', categoryId: 'c1', limit: 8 }],
  loadPublishedStandings: [{ tournamentId: 't1', categoryId: 'c1', phaseId: 'ph1' }],
  loadPublishedStatistics: [{ tournamentId: 't1', categoryId: 'c1', phaseId: 'ph1', groupId: 'g1' }],
  loadCommunicationsInbox: [{ tournamentId: 't1' }],
  loadAnnouncement: ['a1'],
  markAnnouncementRead: [{ announcementId: 'a1' }],
  loadNotificationPreferences: ['t1'],
  updateNotificationPreferences: [{ tournamentId: 't1', general: true, matchChanges: false, callups: true, discipline: true, documents: false, summaries: true }],
  loadPublishedDocuments: [{ tournamentId: 't1' }],
  acknowledgeDocument: [{ versionId: 'dv1', confirm: true }],
  loadCommunicationsAdminContext: [{ organizationId: ORG }],
  createAnnouncementDraft: [{ organizationId: ORG, tournamentId: 't1', type: 'general', title: 'T', summary: 'S', body: 'B', idempotencyKey: 'k6' }],
  replaceAnnouncementAudience: [{ announcementId: 'a1', type: 'tournament' }],
  setAnnouncementLink: [{ announcementId: 'a1', type: 'match', resourceId: 'm1', label: 'Ver partido' }],
  updateAnnouncementDraft: [{ announcementId: 'a1', title: 'T', summary: 'S', body: 'B' }],
  previewAnnouncementAudience: ['a1'],
  publishAnnouncement: [{ announcementId: 'a1', expectedRecipientCount: 3 }],
  createDocument: [{ organizationId: ORG, tournamentId: 't1', type: 'regulation', title: 'T', summary: 'S', body: 'B', idempotencyKey: 'k7' }],
  publishDocumentVersion: ['dv1'],
  loadPublicPageSettings: [{ organizationId: ORG, tournamentId: 't1' }],
  setPublicPagePublished: [{ organizationId: ORG, tournamentId: 't1', published: 1 }],
};
// Composite aliases, checked on their own below.
export const COMPETITION_COMPOSITE = ['loadPlayerMatches', 'loadParticipantHub', 'loadOrganizationVenues'];
// Legacy aliases the hybrid adapter must NOT offer: service-only RPCs, features off, no page caller.
export const COMPETITION_EXCLUDED = ['archiveFixture', 'changeMatchPlan', 'lockRoster', 'recordManualMatchAvailability',
  'createPointsAdjustment', 'revokePointsAdjustment', 'createDisciplinaryOverride', 'markSuspensionServed', 'loadPlayerStatistics',
  'loadPlayerSuspensions', 'updateVenue', 'updateCourt', 'setAnnouncementAudience', 'saveMatchOperationDraft', 'voidMatchOperation',
  'loadMediaAdminContext', 'loadPublishedMedia', 'reportMediaAsset', 'signMediaReadUrls', 'uploadMediaPhoto', 'deleteMediaAsset',
  'loadSocialStudioContext', 'loadSocialSnapshot', 'authorizeSocialExport', 'setSocialPermission', 'loadTeamVisualPolicy',
  'setTeamVisualPolicy', 'resolveTeamShieldUrl', 'resolveTournamentLogoUrl', 'loadSeasonMediaUsage', 'handleMediaReport'];

