#!/usr/bin/env python3
"""Regenerates the tournament-media image fixtures.

Real encoder output only. The verifier under test has to accept exactly what a
browser canvas or a camera pipeline produces, so hand-written byte blobs would
prove nothing. Requires Pillow.

    python3 scripts/edge-functions/fixtures/tournament-media/generate.py
"""

import base64
import os
import textwrap

from PIL import Image, PngImagePlugin

OUT = os.path.dirname(os.path.abspath(__file__))

# Subset embedded in supabase/functions/_shared/tournamentMediaSelfTest.ts so a
# cold Edge Function can certify itself without network or filesystem access.
EMBEDDED = {
    "PROBE_PNG_1X1": "probe-1x1.png",
    "PROBE_JPEG_8X8": "probe-8x8.jpg",
    "PROBE_WEBP_8X8": "probe-8x8.webp",
    "DIRTY_PNG_TEXT": "text-64x48.png",
    "DIRTY_JPEG_EXIF": "exif-orient6-64x48.jpg",
    "ANIMATED_PNG": "animated-16x16.png",
    "GIF_8X8": "sample-8x8.gif",
}


def gradient(width, height):
    image = Image.new("RGB", (width, height))
    pixels = image.load()
    for y in range(height):
        for x in range(width):
            pixels[x, y] = ((x * 7) % 256, (y * 11) % 256, ((x + y) * 3) % 256)
    return image


def main():
    base = gradient(64, 48)
    exif = Image.Exif()
    exif[0x0112] = 6  # Orientation: rotate 90° CW
    exif[0x010E] = "Cancha 3 - Nicolas"  # ImageDescription: a name, on purpose

    base.save(f"{OUT}/clean-64x48.jpg", "JPEG", quality=80)
    base.save(f"{OUT}/exif-orient6-64x48.jpg", "JPEG", quality=80, exif=exif.tobytes())

    base.save(f"{OUT}/clean-64x48.png", "PNG")
    text = PngImagePlugin.PngInfo()
    text.add_text("Author", "Nicolas Avayu")
    text.add_text("Comment", "privado")
    base.save(f"{OUT}/text-64x48.png", "PNG", pnginfo=text)

    base.save(f"{OUT}/clean-64x48.webp", "WEBP", quality=80)
    base.save(f"{OUT}/exif-64x48.webp", "WEBP", quality=80, exif=exif.tobytes())

    gradient(1, 1).save(f"{OUT}/probe-1x1.png", "PNG")
    gradient(8, 8).save(f"{OUT}/probe-8x8.jpg", "JPEG", quality=70)
    gradient(8, 8).save(f"{OUT}/probe-8x8.webp", "WEBP", quality=70)

    frames = [gradient(16, 16), gradient(16, 16).transpose(Image.FLIP_LEFT_RIGHT)]
    for suffix, fmt in (("png", "PNG"), ("webp", "WEBP")):
        frames[0].save(
            f"{OUT}/animated-16x16.{suffix}", fmt,
            save_all=True, append_images=frames[1:], duration=100, loop=0,
        )
    gradient(8, 8).save(f"{OUT}/sample-8x8.gif", "GIF")

    with open(f"{OUT}/payload.svg", "w", encoding="utf8") as handle:
        handle.write(
            '<?xml version="1.0"?>\n'
            '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="48">'
            "<script>alert(1)</script></svg>\n"
        )

    print("fixtures written to", OUT)
    print("\n--- base64 constants for tournamentMediaSelfTest.ts ---\n")
    for name, filename in EMBEDDED.items():
        with open(os.path.join(OUT, filename), "rb") as handle:
            encoded = base64.b64encode(handle.read()).decode()
        chunks = textwrap.wrap(encoded, 72)
        body = "\n".join(
            f'    {"+ " if index else ""}"{chunk}"'
            for index, chunk in enumerate(chunks)
        )
        print(
            f"/** `{filename}` — generated by "
            f"scripts/edge-functions/fixtures/README.md */\n"
            f"const {name} = decode(\n{body},\n)\n"
        )


if __name__ == "__main__":
    main()
