// Error copy and the workspace error type, kept free of any backend client so the
// staging-v1 adapter (gateway transport) and the legacy service (Core singleton)
// share exactly the same code→message contract.
export const ERROR_MESSAGES = {
  TORNEOS_AUTH_REQUIRED: 'Tu sesión venció. Volvé a iniciar sesión para continuar.',
  TORNEOS_IDEMPOTENCY_REQUIRED: 'No pudimos preparar la creación. Volvé a intentarlo.',
  TORNEOS_IDEMPOTENCY_CONFLICT: 'Ese intento de creación corresponde a un recurso archivado.',
  TORNEOS_INVALID_NAME: 'Revisá el nombre de la organización.',
  TORNEOS_INVALID_SLUG: 'Revisá el identificador de la organización.',
  TORNEOS_SLUG_TAKEN: 'Ese identificador ya está en uso. Probá con otro.',
  TORNEOS_CREATION_RATE_LIMITED: 'Se hicieron varios intentos. Esperá unos minutos y probá de nuevo.',
  TORNEOS_WORKSPACE_FORBIDDEN: 'Ya no tenés acceso a ese espacio.',
  TORNEOS_ORGANIZATION_FORBIDDEN: 'No tenés permiso para realizar esa acción.',
  TORNEOS_ARCHIVE_FORBIDDEN: 'Sólo el Propietario puede archivar la organización.',
  TORNEOS_INVALID_STATUS: 'El estado seleccionado no es válido.',
  TORNEOS_ACTIVE_OWNER_REQUIRED: 'La organización debe conservar un Propietario activo.',
  TORNEOS_RESOURCE_FORBIDDEN: 'No encontramos ese recurso o no tenés permiso para acceder.',
  TORNEOS_CONTEXT_FORBIDDEN: 'Ese contexto ya no está disponible.',
  TORNEOS_INVALID_SEASON: 'Revisá los datos de la temporada.',
  TORNEOS_INVALID_DATES: 'Revisá el orden de las fechas.',
  TORNEOS_SEASON_SLUG_TAKEN: 'Ya existe una temporada con ese identificador.',
  TORNEOS_INVALID_SEASON_TRANSITION: 'Ese cambio de estado de temporada no está permitido.',
  TORNEOS_SEASON_HAS_TOURNAMENTS: 'Archivá primero los torneos vigentes de esta temporada.',
  TORNEOS_INVALID_TOURNAMENT: 'Revisá la configuración del torneo.',
  TORNEOS_INVALID_MODALITY: 'Seleccioná una modalidad válida.',
  TORNEOS_INVALID_PATCH: 'La configuración enviada contiene campos no permitidos.',
  TORNEOS_INVALID_SCORING: 'Revisá la configuración de puntuación.',
  TORNEOS_INVALID_DISCIPLINE: 'Revisá la configuración disciplinaria.',
  TORNEOS_TOURNAMENT_SLUG_TAKEN: 'Ya existe un torneo con ese identificador en la temporada.',
  TORNEOS_INVALID_TIEBREAKS: 'Revisá el orden de los criterios de desempate.',
  TORNEOS_INVALID_CATEGORY: 'Revisá los datos de la categoría.',
  TORNEOS_CATEGORY_SLUG_TAKEN: 'Ya existe una categoría con ese identificador.',
  TORNEOS_CATEGORY_REQUIRED: 'El torneo debe conservar al menos una categoría activa.',
  TORNEOS_INVALID_TOURNAMENT_TRANSITION: 'Ese cambio de estado del torneo no está permitido.',
  TORNEOS_REGISTRATION_INCOMPLETE: 'Completá los requisitos antes de preparar la inscripción.',
  TORNEOS_PREMIUM_REQUIRED: 'Esta edición necesita Premium antes de abrir inscripciones u operar la competencia.',
  TORNEOS_BILLING_FORBIDDEN: 'Sólo el Propietario o un Administrador pueden gestionar la compra.',
  TORNEOS_ALREADY_PREMIUM: 'Esta temporada ya tiene Premium activo.',
  TORNEOS_SEASON_ALREADY_PREMIUM: 'Esta temporada ya tiene Premium activo.',
  TORNEOS_SEASON_COLLABORATOR_LIMIT_REACHED: 'La temporada alcanzó el límite de colaboradores de su plan.',
  TORNEOS_SEASON_MEDIA_QUOTA_EXCEEDED: 'La temporada alcanzó la cuota multimedia de su plan.',
  TORNEOS_SOCIAL_PREMIUM_REQUIRED: 'Esta placa o este estilo necesitan Premium en esta temporada.',
  TORNEOS_BRANDING_PREMIUM_REQUIRED: 'Sólo Premium permite descargar placas sin la firma Arma2.',
  // Estudio Social (SOCIAL-V1): the database re-authorizes every export; these are its answers.
  TORNEOS_SOCIAL_EXPORT_FORBIDDEN: 'Tu rol no puede descargar ni compartir placas de esta temporada. Pedíselo a un administrador.',
  TORNEOS_SOCIAL_FORBIDDEN: 'No tenés acceso al Estudio Social de esta organización o temporada.',
  TORNEOS_SOCIAL_SCOPE_UNAVAILABLE: 'Todavía no hay datos oficiales publicados para esta placa. Publicá el fixture o elegí otra categoría o fase.',
  TORNEOS_SOCIAL_THEME_UNKNOWN: 'Ese estilo no está disponible. Elegí uno de la lista.',
  TORNEOS_SOCIAL_PIECE_UNKNOWN: 'Esa placa no está disponible. Elegí una de la lista.',
  TORNEOS_SOCIAL_PIECE_INVALID: 'Esa placa no está disponible. Elegí una de la lista.',
  TORNEOS_SOCIAL_BRANDING_INVALID: 'No pudimos confirmar la firma Arma2 de la placa. Volvé a intentar.',
  TORNEOS_SOCIAL_TEAM_FORMAT_INVALID: 'La modalidad del torneo no permite armar el Equipo ideal. Revisá la configuración de la categoría.',
  TORNEOS_PURCHASE_FORBIDDEN: 'No encontramos esa compra o no tenés permiso para verla.',
  TORNEOS_SCOPE_IMMUTABLE: 'No se puede mover un recurso entre organizaciones o torneos.',
  TORNEOS_REGISTRATION_CLOSED: 'La inscripción no está abierta para ese torneo o categoría.',
  TORNEOS_INVALID_TEAM_ENTRY: 'Revisá los datos del equipo.',
  TORNEOS_TEAM_ALREADY_REGISTERED: 'Ese equipo ya está inscripto en la categoría.',
  TORNEOS_INVALID_MANAGER: 'Revisá los datos del responsable.',
  TORNEOS_MANAGER_INVITATION_REQUIRED: 'El responsable debe confirmar una invitación con su propia cuenta.',
  TORNEOS_INVITATION_RATE_LIMITED: 'Se generaron varias invitaciones. Esperá unos minutos.',
  TORNEOS_SEARCH_RATE_LIMITED: 'Se hicieron muchas búsquedas. Esperá un minuto y probá de nuevo.',
  TORNEOS_INVITATION_INVALID: 'La invitación no existe, ya fue usada o no corresponde a esta cuenta.',
  TORNEOS_INVITATION_EXPIRED: 'La invitación venció. Pedí al organizador un enlace nuevo.',
  TORNEOS_ENTRY_NOT_EDITABLE: 'La inscripción ya no admite cambios.',
  TORNEOS_INVALID_PLAYER: 'Revisá el nombre del jugador.',
  TORNEOS_INVALID_PLAYER_IDENTITY: 'Elegí un jugador de Arma2 o creá uno provisional.',
  TORNEOS_DUPLICATE_PLAYER: 'Ese jugador ya está en el plantel.',
  TORNEOS_DUPLICATE_SHIRT_NUMBER: 'Ese dorsal ya está asignado.',
  TORNEOS_ROSTER_MAXIMUM_REACHED: 'El plantel alcanzó el máximo permitido.',
  TORNEOS_ROSTER_INCOMPLETE: 'El plantel todavía no cumple todos los requisitos.',
  TORNEOS_MANAGER_REQUIRED: 'Asigná al menos un responsable antes de presentar.',
  TORNEOS_INVALID_REVIEW: 'Indicá un motivo claro para completar la revisión.',
  TORNEOS_REASON_REQUIRED: 'Indicá el motivo de esta acción.',
  TORNEOS_PARTICIPANTS_ALREADY_FROZEN: 'Los participantes ya están cerrados para esta categoría.',
  TORNEOS_PARTICIPANTS_NOT_FROZEN: 'Cerrá los participantes antes de generar el fixture.',
  TORNEOS_PENDING_REGISTRATIONS: 'Hay inscripciones pendientes que deben resolverse antes del cierre.',
  TORNEOS_NOT_ENOUGH_PARTICIPANTS: 'Se necesitan al menos dos equipos aprobados con plantel habilitado.',
  TORNEOS_DRAW_NOT_EDITABLE: 'El sorteo publicado ya no admite cambios.',
  TORNEOS_GROUP_DRAW_REQUIRED: 'Publicá los grupos antes de generar este formato.',
  // generate_tournament_fixture en formatos con grupos: sin sorteo publicado los grupos no tienen clave.
  TORNEOS_GROUP_DRAW_SEED_INVALID: 'Primero sorteá y publicá los grupos. Después vas a poder generar el fixture.',
  TORNEOS_GROUP_DRAW_SEED_MISMATCH: 'La clave no coincide con la del sorteo publicado. Dejala vacía para usar la del sorteo.',
  TORNEOS_INVALID_DRAW: 'Revisá la cantidad de grupos y la semilla del sorteo.',
  TORNEOS_INVALID_DRAW_POTS: 'Revisá la configuración de bombos.',
  TORNEOS_DUPLICATE_DRAW_ASSIGNMENT: 'Un participante o seed está asignado más de una vez.',
  TORNEOS_FIXTURE_INVALID: 'El fixture tiene conflictos estructurales que impiden publicarlo.',
  TORNEOS_STALE_FIXTURE_VERSION: 'Hay un borrador de fixture más reciente. Publicá la última versión o archivá esta.',
  TORNEOS_FIXTURE_DRAFT_READ_ONLY: 'Ese borrador quedó cerrado cuando comenzó el torneo. Archivá la revisión o agregá una fase sobre el fixture publicado.',
  TORNEOS_PUBLISHED_FIXTURE_REQUIRED: 'Publicá primero el fixture de Liga antes de agregar Playoffs.',
  TORNEOS_PLAYOFF_SOURCE_INVALID: 'Elegí una fase de Liga publicada como origen de la clasificación.',
  TORNEOS_PLAYOFF_PHASE_EXISTS: 'Este fixture ya tiene una fase eliminatoria.',
  TORNEOS_INVALID_QUALIFIERS: 'Elegí una cantidad de clasificados compatible con los equipos del torneo.',
  TORNEOS_SCHEDULE_CONFLICT: 'La programación tiene un conflicto bloqueante.',
  TORNEOS_SCHEDULE_WARNING_CONFIRMATION: 'Revisá las advertencias y confirmá el override con motivo.',
  TORNEOS_AUTOSCHEDULE_RANGE_REQUIRED: 'Definí un rango acotado para usar la programación automática.',
  TORNEOS_CYCLIC_MATCH_SOURCE: 'La fuente del cruce produciría una referencia cíclica.',
  TORNEOS_MATCH_FORBIDDEN: 'El partido no está disponible o no tenés permiso para verlo.',
  TORNEOS_MATCH_NOT_OPENABLE: 'El partido todavía no reúne las condiciones para abrir el acta.',
  TORNEOS_MATCH_ALREADY_OFFICIAL: 'El partido ya tiene un resultado oficial. Solicitá una corrección para crear otra versión.',
  // La levantan la programación, la convocatoria y la disponibilidad: la copy no puede hablar de una sola.
  TORNEOS_MATCH_OPERATION_ACTIVE: 'El partido ya tiene un acta activa: su programación, convocatorias y disponibilidad ya no admiten cambios.',
  TORNEOS_MATCH_OPEN_WINDOW: 'El acta se está abriendo fuera de horario. Indicá el motivo del override.',
  TORNEOS_MATCH_PLAYER_OUT_OF_SCOPE: 'Ese jugador no pertenece al plantel habilitado del equipo.',
  TORNEOS_MATCH_PLAYER_ABSENT: 'Ese jugador figura ausente o justificado y no puede recibir el evento.',
  TORNEOS_MATCH_PLAYER_NOT_ON_FIELD: 'Ese jugador no está en cancha en ese momento.',
  TORNEOS_MATCH_PLAYER_ALREADY_ON_FIELD: 'Ese jugador ya está en cancha en ese momento.',
  TORNEOS_MATCH_ROSTER_NOT_APPROVED: 'El equipo no tiene un plantel aprobado o bloqueado.',
  TORNEOS_INVALID_MATCH_SQUAD: 'Revisá titulares, capitán y jugadores de la convocatoria.',
  TORNEOS_MATCH_SQUAD_LOCKED: 'La convocatoria ya fue presentada o bloqueada.',
  TORNEOS_MATCH_SQUAD_SCOPE: 'La convocatoria no coincide con el partido, equipo o plantel habilitado.',
  TORNEOS_INVALID_AVAILABILITY: 'Elegí Voy, No voy o En duda.',
  TORNEOS_MATCH_AVAILABILITY_SELF_AUTHORITATIVE: 'La respuesta personal del jugador no puede reemplazarse manualmente.',
  TORNEOS_MATCH_EVENT_TEAM_MISMATCH: 'El evento no corresponde a un equipo del partido.',
  TORNEOS_MATCH_EVENT_PLAYER_MISMATCH: 'El jugador del evento no pertenece a esa alineación.',
  TORNEOS_MATCH_EVENT_RELATION_INVALID: 'Revisá la relación entre los eventos seleccionados.',
  TORNEOS_MATCH_ASSIST_WITHOUT_GOAL: 'La asistencia debe vincularse con un gol válido del mismo equipo.',
  TORNEOS_MATCH_SUBSTITUTION_INVALID: 'La sustitución debe vincular una salida vigente con un ingreso válido.',
  TORNEOS_MATCH_PLAYER_ALREADY_SENT_OFF: 'Ese jugador ya fue expulsado; revisá la secuencia del acta.',
  TORNEOS_MATCH_SECOND_YELLOW_WITHOUT_FIRST: 'La segunda amarilla requiere una amarilla previa vigente.',
  TORNEOS_MATCH_OPERATION_INVALID: 'El acta tiene validaciones pendientes antes de presentarse.',
  TORNEOS_MATCH_DUAL_CONTROL_REQUIRED: 'Este torneo usa doble control: otra persona autorizada debe validar el acta que presentaste.',
  // OFFICIALIZATION-V1: membresía de la organización y política de doble control.
  TORNEOS_MEMBER_FORBIDDEN: 'No tenés permiso para administrar los miembros de esta organización.',
  TORNEOS_MEMBER_ROLE_FORBIDDEN: 'Sólo el Propietario puede asignar o cambiar el rol de Administrador.',
  TORNEOS_MEMBER_SELF_CHANGE_FORBIDDEN: 'No podés cambiar ni quitar tu propia membresía.',
  TORNEOS_OWNER_PROTECTED: 'El Propietario no puede ser quitado ni cambiar de rol.',
  TORNEOS_MEMBER_NOT_ACTIVE: 'Ese miembro ya no está activo.',
  TORNEOS_MEMBER_ALREADY_ACTIVE: 'Ya sos miembro activo de esta organización.',
  TORNEOS_INVALID_MEMBER_ROLE: 'Elegí Administrador o Colaborador.',
  TORNEOS_INVALID_MEMBER_EMAIL: 'Ingresá un email válido.',
  TORNEOS_INVITATION_NOT_PENDING: 'Esa invitación ya no está pendiente.',
  TORNEOS_INVALID_DUAL_CONTROL: 'Elegí si el torneo usa doble control.',
  TORNEOS_DUAL_CONTROL_SECOND_VALIDATOR_REQUIRED: 'Para activar el doble control hace falta otro Administrador con acceso a esta temporada.',
  TORNEOS_MATCH_REVIEW_NOT_OPEN: 'La revisión ya fue resuelta o dejó de estar disponible.',
  TORNEOS_MATCH_REVIEW_OPEN: 'Hay una revisión incompatible todavía abierta.',
  TORNEOS_MATCH_CORRECTION_EXISTS: 'Ya existe una corrección activa para esta versión.',
  TORNEOS_MATCH_CORRECTION_STALE: 'La versión a corregir ya no es la vigente.',
  TORNEOS_STANDINGS_FORBIDDEN: 'La tabla no está disponible para este perfil o contexto.',
  TORNEOS_STANDINGS_SCOPE_INVALID: 'La categoría, fase o grupo no pertenecen al contexto activo.',
  TORNEOS_STANDINGS_REASON_REQUIRED: 'Indicá un motivo claro para recalcular o publicar.',
  TORNEOS_STANDINGS_DRAFT_EXISTS: 'Ya existe un cálculo borrador para este contexto.',
  TORNEOS_STANDINGS_NOT_PUBLISHABLE: 'Esta revisión ya no puede publicarse.',
  TORNEOS_STANDINGS_STALE: 'Los resultados oficiales cambiaron. Recalculá antes de publicar.',
  TORNEOS_STANDINGS_SOURCES_CHANGED: 'Los datos oficiales cambiaron durante el cálculo. Volvé a recalcular.',
  TORNEOS_STATISTICS_FORBIDDEN: 'Las estadísticas no están disponibles para este perfil.',
  TORNEOS_QUALIFICATION_FORBIDDEN: 'No tenés permiso para resolver clasificaciones.',
  TORNEOS_QUALIFICATION_REASON_REQUIRED: 'Indicá el motivo de la resolución de clasificados.',
  TORNEOS_QUALIFICATION_INCOMPLETE: 'Aún hay partidos o resultados pendientes en esta fase.',
  TORNEOS_QUALIFICATION_AMBIGUOUS: 'La clasificación requiere una resolución manual.',
  TORNEOS_QUALIFICATION_MANUAL_LOCKED: 'Ese cruce tiene una resolución manual y no puede reemplazarse automáticamente.',
  TORNEOS_DISCIPLINE_FORBIDDEN: 'No tenés permiso para administrar disciplina.',
  TORNEOS_DISCIPLINE_OVERRIDE_INVALID: 'Revisá el tipo, la cantidad y el motivo del ajuste disciplinario.',
  TORNEOS_SUSPENSION_NOT_ACTIVE: 'La sanción ya no está activa.',
  TORNEOS_SUSPENSION_MATCH_INVALID: 'Ese partido no puede computarse como fecha cumplida.',
  TORNEOS_PLAYER_SUSPENDED: 'El jugador tiene una suspensión activa y no puede integrar la convocatoria.',
  TORNEOS_HUB_FORBIDDEN: 'Ese torneo ya no está disponible para tu perfil.',
  TORNEOS_HUB_INVALID_FILTER: 'El filtro de partidos no es válido.',
  TORNEOS_COMMUNICATION_FORBIDDEN: 'Ese comunicado no está disponible para tu perfil.',
  TORNEOS_DOCUMENT_FORBIDDEN: 'Ese documento no está disponible para tu perfil.',
  TORNEOS_COMMUNICATION_IMMUTABLE: 'El comunicado publicado no puede editarse. Creá una actualización.',
  TORNEOS_DOCUMENT_VERSION_IMMUTABLE: 'La versión publicada no puede editarse. Creá una nueva versión.',
  TORNEOS_COMMUNICATION_NOT_PUBLISHABLE: 'Ese comunicado ya no se puede publicar.',
  TORNEOS_COMMUNICATION_INVALID_FILTER: 'El filtro de novedades no es válido.',
  TORNEOS_INVALID_AUDIENCE: 'La audiencia ya no pertenece a este torneo.',
  TORNEOS_AUDIENCE_REQUIRED: 'Definí una audiencia antes de publicar.',
  TORNEOS_AUDIENCE_EMPTY: 'La audiencia no tiene destinatarios activos.',
  TORNEOS_AUDIENCE_LIMIT_REACHED: 'El comunicado alcanzó el máximo de audiencias.',
  TORNEOS_RECIPIENT_LIMIT_REACHED: 'La audiencia supera el máximo permitido.',
  TORNEOS_DRAFT_LIMIT_REACHED: 'Hay demasiados borradores abiertos en este espacio.',
  TORNEOS_PUBLISH_RATE_LIMITED: 'Se publicaron muchos comunicados. Esperá antes de continuar.',
  TORNEOS_CORRECTION_ALREADY_SUPERSEDED: 'Ese comunicado ya fue reemplazado por otra corrección. Revisá la versión vigente.',
  TORNEOS_LINK_LIMIT_REACHED: 'El comunicado alcanzó el máximo de enlaces.',
  TORNEOS_INVALID_COMMUNICATION_LINK: 'El enlace no pertenece a este torneo o no es seguro.',
  TORNEOS_DOCUMENT_DRAFT_EXISTS: 'Ya existe una versión borrador para este documento.',
  TORNEOS_MEDIA_FORBIDDEN: 'La galería no está disponible o no tenés permiso para esa acción.',
  TORNEOS_MEDIA_SCOPE_INVALID: 'La galería, el partido o la relación deportiva no coinciden.',
  TORNEOS_MEDIA_VISIBILITY_INVALID: 'Esa visibilidad no corresponde al alcance de la galería.',
  TORNEOS_MEDIA_GALLERY_IMMUTABLE: 'La galería publicada ya no admite edición directa.',
  TORNEOS_MEDIA_GALLERY_NOT_PUBLISHABLE: 'Revisá la portada y las fotos aprobadas antes de publicar.',
  TORNEOS_MEDIA_FILE_INVALID: 'El archivo no superó la validación segura.',
  TORNEOS_MEDIA_IDEMPOTENCY_CONFLICT: 'Ese intento ya se usó con otros datos. Volvé a iniciar la acción.',
  TORNEOS_MEDIA_PROCESSING_REQUIRED: 'La foto todavía se está procesando de forma segura.',
  TORNEOS_MEDIA_QUOTA_EXCEEDED: 'Se alcanzó la cuota multimedia de este espacio.',
  TORNEOS_MEDIA_UPLOAD_SESSION_INVALID: 'La sesión de carga venció o ya fue utilizada.',
  TORNEOS_MEDIA_DUPLICATE: 'Esa foto ya fue cargada en la organización.',
  TORNEOS_MEDIA_TRANSITION_INVALID: 'Ese cambio de estado ya no está disponible.',
  TORNEOS_MEDIA_COVER_INVALID: 'Elegí como portada una foto aprobada de esta galería.',
  TORNEOS_MEDIA_CONSENT_INVALID: 'Revisá la persona y el uso asociado al consentimiento.',
  TORNEOS_MEDIA_CONSENT_REQUIRED: 'Falta registrar el derecho de visualización interna.',
  TORNEOS_MEDIA_ASSIGNMENT_INVALID: 'No pudimos asignar ese fotógrafo.',
  TORNEOS_MEDIA_FILTER_INVALID: 'Revisá los filtros de Multimedia.',
  TORNEOS_MEDIA_REPORT_RATE_LIMITED: 'Recibimos varios reportes. Esperá antes de enviar otro.',
  TORNEOS_MEDIA_REPORT_INVALID: 'Ese reporte ya no admite esa resolución.',
  TORNEOS_MEDIA_ORDER_INVALID: 'No pudimos mover la foto a esa posición.',
  TORNEOS_PUBLIC_PAGE_FORBIDDEN: 'No tenés permiso para publicar esta página.',
  TORNEOS_PUBLIC_PAGE_NOT_PUBLISHABLE: 'El torneo todavía no está en un estado publicable.',
  // Reglas del ciclo de vida de la competencia. Sin estas entradas cualquier
  // llamador las recibe como un fallo genérico: el código funcional se pierde
  // acá y no llega a la pantalla. `getLifecycleErrorMessage` refina estos
  // mensajes con la cantidad cuando el backend la informa.
  TORNEOS_COMPETITION_HAS_PENDING_COMMITMENTS:
    'Todavía quedan partidos por resolver antes de finalizar la competencia.',
  TORNEOS_COMPETITION_READ_ONLY:
    'La competencia está finalizada y no admite cambios. Reabrila si necesitás corregir algo.',
  TORNEOS_PARTICIPANT_ALREADY_WITHDRAWN: 'Este equipo ya figura como retirado.',
  TORNEOS_PARTICIPANT_HAS_OPEN_OPERATIONS:
    'El equipo tiene un acta abierta. Resolvela o anulala antes de retirarlo.',
  // CONNECTED-V1: catálogo, solicitudes de inscripción, perfil y avisos de Torneos.
  TORNEOS_APPLICATIONS_CLOSED: 'Esta convocatoria no está recibiendo solicitudes en este momento.',
  TORNEOS_CATEGORY_FULL: 'La categoría completó su cupo: no hay lugar para otro equipo.',
  TORNEOS_TEAM_NOT_AUTHORIZED:
    'Sólo quien administra el equipo en Arma2 puede inscribirlo. Compartí la convocatoria con tu responsable.',
  TORNEOS_TEAM_NAME_TAKEN: 'Ya hay un equipo con ese nombre en la categoría.',
  TORNEOS_APPLICATION_LIMIT_REACHED: 'Ya tenés 3 solicitudes abiertas en este torneo. Resolvé alguna antes de pedir otra.',
  TORNEOS_APPLICATION_CONDITIONS_REQUIRED: 'Para pedir la inscripción tenés que aceptar las condiciones del torneo.',
  TORNEOS_PROFILE_NAME_REQUIRED: 'Elegí cómo te va a ver la organización antes de pedir la inscripción.',
  TORNEOS_PROFILE_INVALID: 'El nombre de presentación tiene que tener entre 2 y 60 caracteres.',
  TORNEOS_CATALOG_LISTING_NOT_READY:
    'Para publicar la convocatoria el torneo tiene que estar en inscripción, con su página pública publicada y al menos una categoría activa.',
  TORNEOS_CATALOG_LISTING_INCOMPLETE: 'Completá el resumen y la localidad antes de publicar la convocatoria.',
  TORNEOS_CATALOG_LISTING_INVALID: 'Revisá los datos de la convocatoria.',
  TORNEOS_CONTACT_INVALID: 'Ingresá el WhatsApp con código de país, por ejemplo +54 9 11 2345 6789.',
  TORNEOS_CONTACT_CONSENT_REQUIRED: 'Confirmá que el WhatsApp se va a mostrar públicamente en la convocatoria.',
  TORNEOS_CATALOG_LISTING_REMOVED: 'Arma2 retiró esta convocatoria del catálogo y no puede volver a publicarse.',
  TORNEOS_CAPACITY_BELOW_APPROVED: 'El cupo no puede ser menor que la cantidad de equipos ya aprobados.',
  TORNEOS_SEARCH_QUERY_INVALID: 'Escribí al menos 2 letras del nombre de tu equipo.',
  TORNEOS_CATALOG_INVALID_FILTER: 'Revisá los filtros de búsqueda.',
  TORNEOS_APPLICATIONS_INVALID_FILTER: 'Ese filtro de solicitudes no existe.',
  TORNEOS_NOTIFICATIONS_INVALID: 'No pudimos procesar esos avisos.',
};

export class TournamentWorkspaceError extends Error {
  constructor(code, message, cause = null) {
    super(message);
    this.name = 'TournamentWorkspaceError';
    this.code = code;
    this.cause = cause;
  }
}

export function getKnownErrorCode(error) {
  const value = [
    error?.message,
    error?.details,
    error?.hint,
    error?.code,
  ].filter(Boolean).join(' ');
  return Object.keys(ERROR_MESSAGES).find((code) => value.includes(code)) || null;
}

export function toWorkspaceError(error, fallbackMessage) {
  if (error instanceof TournamentWorkspaceError) return error;
  const code = getKnownErrorCode(error) || 'TORNEOS_REQUEST_FAILED';
  return new TournamentWorkspaceError(
    code,
    ERROR_MESSAGES[code] || fallbackMessage,
    error,
  );
}
