// supabase/functions/_shared/tournamentMediaSelfTest.ts
//
// The processor attests its capabilities to the database, and `uploadReady`
// is derived from that attestation. An attestation that is merely a hardcoded
// object would be exactly the kind of optimistic constant this pipeline exists
// to remove — so the processor proves the claim first, against real image
// bytes compiled into the bundle, and only then attests.
//
// The fixtures below are byte-for-byte copies of files in
// `scripts/edge-functions/fixtures/tournament-media/`, which the Node suite
// exercises far more thoroughly. Keeping a small subset inline is what lets a
// cold Edge Function certify itself with no network and no filesystem.

import {
  MediaImageError,
  sha256Hex,
  sniffImageMime,
  verifyNormalizedImage,
} from "./tournamentMediaImage.ts"
import { variantGeometry } from "./tournamentMediaContract.ts"

function decode(base64: string): Uint8Array {
  return Uint8Array.from(atob(base64), (character) => character.charCodeAt(0))
}

/** `probe-1x1.png` — generated by scripts/edge-functions/fixtures/README.md */
const PROBE_PNG_1X1 = decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGNgYGAAAAAEAAH2"
    + "FzhVAAAAAElFTkSuQmCC",
)

/** `probe-8x8.jpg` — generated by scripts/edge-functions/fixtures/README.md */
const PROBE_JPEG_8X8 = decode(
    "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8l"
    + "JCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIo"
    + "Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAAR"
    + "CAAIAAgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA"
    + "AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK"
    + "FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWG"
    + "h4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl"
    + "5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA"
    + "AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYk"
    + "NOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE"
    + "hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk"
    + "5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDzKHTf9miiisOdmNKtPl3P/9k=",
)

/** `probe-8x8.webp` — generated by scripts/edge-functions/fixtures/README.md */
const PROBE_WEBP_8X8 = decode(
    "UklGRjwAAABXRUJQVlA4IDAAAAAwAgCdASoIAAgAAkA4JYgCdH8AGZMSTN4uEAD+/eS44zbL"
    + "KVBmcPmlZoN699QLAAA=",
)

/** `text-64x48.png` — generated by scripts/edge-functions/fixtures/README.md */
const DIRTY_PNG_TEXT = decode(
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAAAwCAIAAAAuKetIAAAAFHRFWHRBdXRob3IATmljb2xh"
    + "cyBBdmF5dZAiMHEAAAAPdEVYdENvbW1lbnQAcHJpdmFkb+r7vCgAAABZSURBVHic7c9BCcAA"
    + "EMTAlBz0Uf9+q2MhMAbmAV7cdXzCsCtgAQsw7ApYwAIMuwIWsADDroAFLMCwK2ABCzDsCljA"
    + "Agy7AhawAMOugAUswLArYAELMOzWAz/EJCh5d8XhbgAAAABJRU5ErkJggg==",
)

/** `exif-orient6-64x48.jpg` — generated by scripts/edge-functions/fixtures/README.md */
const DIRTY_JPEG_EXIF = decode(
    "/9j/4AAQSkZJRgABAQAAAQABAAD/4QBCRXhpZgAATU0AKgAAAAgAAgEOAAIAAAATAAAAJgES"
    + "AAMAAAABAAYAAAAAAABDYW5jaGEgMyAtIE5pY29sYXMAAP/bAEMABgQFBgUEBgYFBgcHBggK"
    + "EAoKCQkKFA4PDBAXFBgYFxQWFhodJR8aGyMcFhYgLCAjJicpKikZHy0wLSgwJSgpKP/bAEMB"
    + "BwcHCggKEwoKEygaFhooKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo"
    + "KCgoKCgoKCgoKP/AABEIADAAQAMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQID"
    + "BAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgj"
    + "QrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdo"
    + "aWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK"
    + "0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQID"
    + "BAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGh"
    + "scEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZn"
    + "aGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfI"
    + "ycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APn+00bp8tbVpo3T"
    + "5a6+00bp8tbVpo3T5a8+OLOHLs521OQtNG6fLW1aaN0+WuvtNG6fLW1aaN0+Wto4s+8y7Odt"
    + "Tyrxro3/ABJoPl/5eF/9BauZtNG6fLXt/jXRv+JNB8v/AC8L/wCgtXM2mjdPlr6jK8X+4Xqf"
    + "LcS5z/wqPX7MTkLTRuny1tWmjdPlrr7TRuny1tWmjdPlr1Y4s7suznbUr2mjdPlratNG6fLX"
    + "zNaaN0+Wtq00bp8tfDR4e/6ff+S//bHweXZDt/tH/kv/ANsfTNpo3T5a2rTRuny18zWmjdPl"
    + "ratNG6fLWseHv+n3/kv/ANsfeZdkO3+0f+S//bHufjXRv+JNB8v/AC8L/wCgtXM2mjdPlryX"
    + "xro3/Emg+X/l4X/0Fq5m00bp8tfUZXw9+4X77r/L/wDbHyvEuQ/8Kj/2j7Mfs/8A2x9NWmjd"
    + "PlratdHAGSAAOSTXzLa6OAMkAAckmiSzM52RqREP/HqzzmjQyih7SpWvJ/DG2rf37d3+p6WV"
    + "cOOo0liP/Jf/ALY07TRuny1tWmjdPlrWtNR8Pcf8TvSv/AuP/Gtq01Hw9x/xO9K/8C4/8a8W"
    + "M638r+5nw+XY+vp7r+5mTaaN0+Wtq00bp8ta1pqPh7j/AInelf8AgXH/AI1tWmo+HuP+J3pP"
    + "/gXH/jW0Z1v5X9zPvMux9fT3X9zOD8a6N/xJoPl/5eF/9BauYtdHAGSAAOSTXq3jbUvDo0WE"
    + "nXNJAE4JJvI/7re9efya74fnOyPXNKEQ/wCnuP5v1rur58sowXtKkW5O/LGz1/4Hd/qfNcQ4"
    + "rEVM1aUX8MejMqSyM52RqREP/Hqu2mjdPlrWtNR8Pcf8TvSf/AuP/Gtm01Hw9x/xO9K/8C4/"
    + "8a/KMbmOMzCu8RiE3J+Tsl2Xke/lmMrQSSg/uZ//2Q==",
)

/** `animated-16x16.png` — generated by scripts/edge-functions/fixtures/README.md */
const ANIMATED_PNG = decode(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAACGFjVEwAAAACAAAAAPONk3AA"
    + "AAAaZmNUTAAAAAAAAAAQAAAAEAAAAAAAAAAAAGQD6AAAikecOAAAACJJREFUeJxjZGBgYGdg"
    + "Jh6xMHAzMzCQgFhGNTCMamAYIhoAIO8ESbBiaVkAAAAaZmNUTAAAAAEAAAAQAAAAEAAAAAAA"
    + "AAAAAGQD6AAAETR27AAAAChmZEFUAAAAAnicY8xk0P3J8Jd4xMLAzcxACmAZ1UAEYBnVQASg"
    + "vQYAiRUfEGzxNUwAAAAASUVORK5CYII=",
)

/** `sample-8x8.gif` — generated by scripts/edge-functions/fixtures/README.md */
const GIF_8X8 = decode(
    "R0lGODdhCAAIAIUAADFNKipNJyNNJDFCJypCJCNCIRxNIRVNHhxCHhVCGzE3JCo3ISM3Hhw3"
    + "GxU3GA5NGwdNGABNFQ5CGAdCFQBCEg43FQc3EgA3DzEsISosHiMsGzEhHiohGyMhGBwsGBUs"
    + "FRwhFRUhEg4sEgcsDwAsDA4hDwchDAAhCTEWGyoWGCMWFTELGCoLFSMLEhwWEhUWDxwLDxUL"
    + "DDEAFSoAEiMADxwADBUACQ4WDAcWCQAWBg4LCQcLBgALAw4ABgcAAwAAACwAAAAACAAIAAAI"
    + "SwB/+OhhowaNGTJ47NARA0YLFity4LjxwoWKFChOmCgRAkQHDhtIjBDxwYOGDBguWKjgoAGD"
    + "BQooTJCQAEEBAgMiQHhwwICAAAACAgA7",
)

export type ProcessorSelfTest = {
  passed: boolean
  checks: Record<string, boolean>
}

function expectRejection(
  bytes: Uint8Array, mime: string, code: string,
): boolean {
  try {
    verifyNormalizedImage(bytes, mime)
    return false
  } catch (error) {
    return error instanceof MediaImageError && error.code === code
  }
}

function withTrailingBytes(bytes: Uint8Array): Uint8Array {
  const out = new Uint8Array(bytes.length + 4)
  out.set(bytes)
  out.set([0x50, 0x4b, 0x03, 0x04], bytes.length) // a ZIP local header
  return out
}

/**
 * Runs every capability the processor is about to claim. A single false here
 * means the release does not attest, and uploads stay closed.
 */
export async function runProcessorSelfTest(): Promise<ProcessorSelfTest> {
  const checks: Record<string, boolean> = {}

  checks.sniffJpeg = sniffImageMime(PROBE_JPEG_8X8) === "image/jpeg"
  checks.sniffPng = sniffImageMime(PROBE_PNG_1X1) === "image/png"
  checks.sniffWebp = sniffImageMime(PROBE_WEBP_8X8) === "image/webp"
  checks.rejectsGif = sniffImageMime(GIF_8X8) === null

  try {
    const png = verifyNormalizedImage(PROBE_PNG_1X1, "image/png")
    checks.decodesPng = png.width === 1 && png.height === 1 && png.alreadyClean
  } catch {
    checks.decodesPng = false
  }
  try {
    const jpeg = verifyNormalizedImage(PROBE_JPEG_8X8, "image/jpeg")
    checks.decodesJpeg = jpeg.width === 8 && jpeg.height === 8 && jpeg.alreadyClean
  } catch {
    checks.decodesJpeg = false
  }
  try {
    const webp = verifyNormalizedImage(PROBE_WEBP_8X8, "image/webp")
    checks.decodesWebp = webp.width === 8 && webp.height === 8 && webp.alreadyClean
  } catch {
    checks.decodesWebp = false
  }

  checks.rejectsMimeLie = expectRejection(
    PROBE_PNG_1X1, "image/jpeg", "MEDIA_MIME_MISMATCH",
  )
  checks.rejectsSvg = expectRejection(
    new TextEncoder().encode('<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg"/>'),
    "image/png",
    "MEDIA_MIME_MISMATCH",
  )
  checks.rejectsExifOrientation = expectRejection(
    DIRTY_JPEG_EXIF, "image/jpeg", "MEDIA_ORIENTATION_NOT_NORMALIZED",
  )
  checks.rejectsPngMetadata = expectRejection(
    DIRTY_PNG_TEXT, "image/png", "MEDIA_METADATA_PRESENT",
  )
  checks.rejectsAnimation = expectRejection(
    ANIMATED_PNG, "image/png", "MEDIA_ANIMATION_UNSUPPORTED",
  )
  checks.rejectsTruncated = expectRejection(
    PROBE_PNG_1X1.subarray(0, PROBE_PNG_1X1.length - 6),
    "image/png",
    "MEDIA_CONTENT_CORRUPT",
  )
  checks.rejectsTrailingBytes = expectRejection(
    withTrailingBytes(PROBE_PNG_1X1), "image/png", "MEDIA_TRAILING_BYTES",
  )

  // Metadata stripping is enforced, not applied — but the stripper still has to
  // find the carriers, otherwise "already clean" would be vacuously true.
  try {
    verifyNormalizedImage(DIRTY_PNG_TEXT, "image/png")
    checks.findsMetadataCarriers = false
  } catch (error) {
    checks.findsMetadataCarriers = error instanceof MediaImageError
      && error.message.includes("PNG:tEXt")
  }

  const digest = await sha256Hex(new TextEncoder().encode("arma2"))
  checks.checksumVerification = /^[0-9a-f]{64}$/.test(digest)

  const geometry = variantGeometry("thumbnail", 4000, 3000)
  checks.variantGeometry = geometry.width === 320 && geometry.height === 240
  const noUpscale = variantGeometry("detail", 100, 50)
  checks.variantNeverUpscales = noUpscale.width === 100 && noUpscale.height === 50

  return {
    passed: Object.values(checks).every(Boolean),
    checks,
  }
}
