-- Migration: Create match_join_requests and RLS
-- Date: 2026-01-30

create table if not exists public.match_join_requests (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.partidos(id) on delete cascade,
  user_id uuid not null references public.usuarios(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid references public.usuarios(id)
);

-- Indexes for performance
create index if not exists match_join_requests_match_id_idx on public.match_join_requests(match_id);
create index if not exists match_join_requests_user_id_idx on public.match_join_requests(user_id);

-- Unique constraint for pending requests
create unique index if not exists match_join_requests_unique_pending
  on public.match_join_requests(match_id, user_id)
  where status = 'pending';

-- RLS Policies
alter table public.match_join_requests enable row level security;

-- Users can create their own requests
create policy "user can request join"
on public.match_join_requests
for insert
to authenticated
with check (auth.uid() = user_id);

-- Users can read their own requests
create policy "user can read own requests"
on public.match_join_requests
for select
to authenticated
using (auth.uid() = user_id);

-- Admins can read requests for their matches
create policy "admin can read match requests"
on public.match_join_requests
for select
to authenticated
using (
  exists (
    select 1
    from public.partidos m
    where m.id = match_join_requests.match_id
      and m.creado_por = auth.uid()
  )
);

-- Admins can update request status
create policy "admin can update match requests"
on public.match_join_requests
for update
to authenticated
using (
  exists (
    select 1
    from public.partidos m
    where m.id = match_join_requests.match_id
      and m.creado_por = auth.uid()
  )
)
with check (status in ('approved', 'rejected'));
