#!/usr/bin/env node
// Focused DB integration test for "múltiples posiciones + arquero".
//
// Boots an embedded Postgres, applies a minimal self-contained stub of the prod
// core (usuarios/partidos/jugadores/notifications/match_join_requests/profiles +
// the geo helpers the feature reuses), then applies the real feature migration
// `20260718120000_multi_positions_and_goalkeeper_availability.sql` and exercises
// its invariants against real SQL: the positions trigger, the role-aware
// approval RPC, and the deduped goalkeeper notification fan-out.
//
// Uso: npm run test:db:goalkeeper

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import EmbeddedPostgres from 'embedded-postgres';
import pg from 'pg';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const MIGRATION = '20260718120000_multi_positions_and_goalkeeper_availability.sql';

const PORT = 54800 + Math.floor(Math.random() * 400);
const DB_NAME = 'arma2_goalkeeper';
const DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'arma2-gk-pg-'));

const ADMIN = '00000000-0000-4000-8000-0000000000a1';
const GK_NEAR = '00000000-0000-4000-8000-0000000000b1';
const GK_FAR = '00000000-0000-4000-8000-0000000000b2';
const GK_OFF = '00000000-0000-4000-8000-0000000000b3';
const FIELD = '00000000-0000-4000-8000-0000000000c1';
const GK_IN_MATCH = '00000000-0000-4000-8000-0000000000b4';
const GK_SECOND = '00000000-0000-4000-8000-0000000000b5';
// Capacity + concurrency scenarios: a pool of plain field players.
const CAP_ADMIN = '00000000-0000-4000-8000-0000000000d0';
const CAP_USERS = Array.from({ length: 8 }, (_, i) =>
  `00000000-0000-4000-8000-0000000000e${i}`);
const RACE_ADMIN = '00000000-0000-4000-8000-0000000000f0';
const RACE_A = '00000000-0000-4000-8000-0000000000f1';
const RACE_B = '00000000-0000-4000-8000-0000000000f2';
// Flag-gating scenarios: one ARQ user + one field-only user.
const FLAG_ADMIN = '00000000-0000-4000-8000-0000000000c9';
const FLAG_ARQ = '00000000-0000-4000-8000-0000000000ca';
const FLAG_FIELD = '00000000-0000-4000-8000-0000000000cb';
const FLAG_LEGACY = '00000000-0000-4000-8000-0000000000cc';

let failures = 0;
let checks = 0;
const clients = [];

const ok = (condition, label, extra = '') => {
  checks += 1;
  if (condition) {
    console.log(`  ✔ ${label}`);
  } else {
    failures += 1;
    console.error(`  ✘ ${label}${extra ? ` — ${extra}` : ''}`);
  }
};
const eq = (actual, expected, label) =>
  ok(JSON.stringify(actual) === JSON.stringify(expected), label, `esperado ${JSON.stringify(expected)}, obtenido ${JSON.stringify(actual)}`);
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
// Runs a query expected to fail; returns the error message ('' if it unexpectedly succeeded).
const expectFailure = async (client, sql, params = []) => {
  try {
    await client.query(sql, params);
    return '';
  } catch (e) {
    return String(e.message || e);
  }
};

const STUB_SCHEMA = `
create schema if not exists auth;
create table auth.users (id uuid primary key);
create or replace function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
create role authenticated;

create table public.usuarios (
  id uuid primary key,
  nombre text,
  avatar_url text,
  latitud double precision,
  longitud double precision,
  posicion text,
  created_at timestamptz not null default now()
);
create table public.profiles (id uuid primary key, nombre text, avatar_url text);
create table public.partidos (
  id bigint generated by default as identity primary key,
  nombre text,
  fecha date,
  hora text,
  sede text,
  sede_direccion_normalizada text,
  sede_latitud double precision,
  sede_longitud double precision,
  modalidad text,
  cupo_jugadores integer,
  falta_jugadores boolean not null default false,
  creado_por uuid references public.usuarios(id),
  estado text,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);
create table public.jugadores (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  usuario_id uuid references public.usuarios(id),
  nombre text,
  avatar_url text,
  score numeric,
  is_goalkeeper boolean default false,
  created_at timestamptz not null default now()
);
-- Prod carries this unique index (20260227170000): last-resort duplicate guard.
create unique index jugadores_partido_usuario_uidx
  on public.jugadores (partido_id, usuario_id);
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.usuarios(id),
  type text not null,
  title text,
  message text,
  data jsonb,
  read boolean default false,
  partido_id bigint,
  created_at timestamptz not null default now()
);
create table public.match_join_requests (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.partidos(id) on delete cascade,
  user_id uuid not null references public.usuarios(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid
);

-- Geo helpers the feature reuses (reproduced from the prod quiero_jugar migration).
create or replace function public.coordinates_are_valid(p_lat double precision, p_lng double precision)
returns boolean language sql immutable as $$
  select p_lat is not null and p_lng is not null
    and p_lat between -90 and 90 and p_lng between -180 and 180
    and not (abs(p_lat) < 0.0001 and abs(p_lng) < 0.0001);
$$;
create or replace function public.haversine_km(a double precision, b double precision, c double precision, d double precision)
returns double precision language sql immutable as $$
  select case when not public.coordinates_are_valid(a,b) or not public.coordinates_are_valid(c,d) then null
    else 6371::double precision * 2 * atan2(
      sqrt(sin(radians(c-a)/2)^2 + cos(radians(a))*cos(radians(c))*sin(radians(d-b)/2)^2),
      sqrt(1 - (sin(radians(c-a)/2)^2 + cos(radians(a))*cos(radians(c))*sin(radians(d-b)/2)^2))) end;
$$;
create or replace function public.partido_kickoff_at(p_fecha date, p_hora text)
returns timestamptz language sql immutable as $$
  select case when p_fecha is null or coalesce(p_hora,'') = '' then null
    else (p_fecha + (left(p_hora,5) || ':00')::time) at time zone 'America/Argentina/Buenos_Aires' end;
$$;

grant all on all tables in schema public to authenticated;
grant usage on all sequences in schema public to authenticated;
grant usage on schema public to authenticated;
`;

const postgres = new EmbeddedPostgres({
  databaseDir: DATA_DIR, user: 'postgres', password: 'password', port: PORT,
  persistent: false, onLog: () => {}, onError: () => {},
});

async function connect(uid = null) {
  const client = new pg.Client({ host: '127.0.0.1', port: PORT, user: 'postgres', password: 'password', database: DB_NAME });
  await client.connect();
  clients.push(client);
  if (uid) {
    await client.query("select set_config('request.jwt.claim.sub', $1, false)", [uid]);
    await client.query('set role authenticated');
  }
  return client;
}

async function main() {
  await postgres.initialise();
  await postgres.start();
  await postgres.createDatabase(DB_NAME);

  const admin = await connect();
  await admin.query(STUB_SCHEMA);
  await admin.query(fs.readFileSync(path.join(ROOT, 'supabase', 'migrations', MIGRATION), 'utf8'));

  // Grant on the objects created by the migration (run as postgres/superuser).
  await admin.query('grant all on all tables in schema public to authenticated');
  await admin.query('grant usage on all sequences in schema public to authenticated');

  console.log('\n▶ Posiciones trigger (dedup / cap 2 / validación / sync posicion / gating ARQ)');
  await admin.query(`insert into public.usuarios (id, nombre, posiciones) values ($1,'Multi', array['ARQ','ARQ','DEF','DEL'])`, [GK_NEAR]);
  let row = (await admin.query('select posiciones, posicion, disponible_arquero from public.usuarios where id=$1', [GK_NEAR])).rows[0];
  eq(row.posiciones, ['ARQ', 'DEF'], 'dedupe + cap at 2');
  eq(row.posicion, 'ARQ', 'legacy posicion mirrors posiciones[0]');
  eq(row.disponible_arquero, false, 'disponible_arquero defaults false');

  await admin.query(`insert into public.usuarios (id, nombre, posicion) values ($1,'Legacy','MED')`, [FIELD]);
  row = (await admin.query('select posiciones from public.usuarios where id=$1', [FIELD])).rows[0];
  eq(row.posiciones, ['MED'], 'legacy posicion seeds posiciones');

  await admin.query(`update public.usuarios set posiciones = array['DEF','bogus','del'] where id=$1`, [FIELD]);
  row = (await admin.query('select posiciones from public.usuarios where id=$1', [FIELD])).rows[0];
  eq(row.posiciones, ['DEF', 'DEL'], 'invalid tokens dropped, aliases normalized');

  // Availability requires ARQ.
  await admin.query(`update public.usuarios set disponible_arquero = true where id=$1`, [FIELD]);
  row = (await admin.query('select disponible_arquero from public.usuarios where id=$1', [FIELD])).rows[0];
  eq(row.disponible_arquero, false, 'cannot enable availability without ARQ');

  await admin.query(`update public.usuarios set posiciones = array['ARQ','DEL'], disponible_arquero = true where id=$1`, [FIELD]);
  row = (await admin.query('select disponible_arquero from public.usuarios where id=$1', [FIELD])).rows[0];
  eq(row.disponible_arquero, true, 'availability enabled once ARQ present');

  await admin.query(`update public.usuarios set posiciones = array['DEF','DEL'] where id=$1`, [FIELD]);
  row = (await admin.query('select disponible_arquero from public.usuarios where id=$1', [FIELD])).rows[0];
  eq(row.disponible_arquero, false, 'removing ARQ auto-clears availability');

  // Legacy writer path: a client that only touches `posicion` (leaving the array
  // untouched) rebuilds `posiciones` from it, so the two columns never diverge.
  await admin.query(`update public.usuarios set posicion = 'ARQ' where id=$1`, [FIELD]);
  row = (await admin.query('select posiciones, posicion from public.usuarios where id=$1', [FIELD])).rows[0];
  eq(row.posiciones, ['ARQ'], 'legacy posicion-only write rebuilds posiciones');
  eq(row.posicion, 'ARQ', 'legacy posicion-only write stays mirrored');

  console.log('\n▶ approve_join_request honors role → is_goalkeeper (per match)');
  await admin.query('delete from public.usuarios where id = any($1)', [[GK_NEAR, FIELD]]);
  await admin.query(`insert into public.usuarios (id, nombre, latitud, longitud) values ($1,'Admin',-34.60,-58.38)`, [ADMIN]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, disponible_arquero, latitud, longitud) values ($1,'GKnear', array['ARQ'], true, -34.605, -58.381)`, [GK_NEAR]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, latitud, longitud) values ($1,'Field', array['DEF'], -34.60, -58.38)`, [FIELD]);
  const matchId = (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, sede_latitud, sede_longitud, modalidad, cupo_jugadores, creado_por, estado, falta_jugadores, busca_arquero)
     values ('P', (now() + interval '3 days')::date, '20:00', 'Cancha', -34.60, -58.38, 'F5', 10, $1, 'active', true, true) returning id`, [ADMIN])).rows[0].id;

  const adminAsUser = await connect(ADMIN);
  const reqGk = (await admin.query(`insert into public.match_join_requests (match_id, user_id, role) values ($1,$2,'goalkeeper') returning id`, [matchId, GK_NEAR])).rows[0].id;
  await adminAsUser.query('select public.approve_join_request($1)', [reqGk]);
  let jg = (await admin.query('select is_goalkeeper from public.jugadores where partido_id=$1 and usuario_id=$2', [matchId, GK_NEAR])).rows[0];
  eq(jg.is_goalkeeper, true, 'goalkeeper request → is_goalkeeper=true');

  // Creation-side guard: a goalkeeper request from a non-ARQ profile is REJECTED
  // at insert time (never silently downgraded to a player request), so the stored
  // intent / "Se suma como arquero" label can never lie.
  const fieldGkErr = await expectFailure(
    admin,
    `insert into public.match_join_requests (match_id, user_id, role) values ($1,$2,'goalkeeper')`,
    [matchId, FIELD],
  );
  ok(/ARQ/i.test(fieldGkErr), 'goalkeeper request without ARQ is rejected at creation', fieldGkErr);
  const fieldReqCount = (await admin.query('select 1 from public.match_join_requests where match_id=$1 and user_id=$2', [matchId, FIELD])).rowCount;
  eq(fieldReqCount, 0, 'rejected goalkeeper request is never stored');
  // The same user CAN still request as a plain field player (match wants players).
  const reqFieldPlayer = (await admin.query(`insert into public.match_join_requests (match_id, user_id, role) values ($1,$2,'player') returning id`, [matchId, FIELD])).rows[0].id;
  await adminAsUser.query('select public.approve_join_request($1)', [reqFieldPlayer]);
  jg = (await admin.query('select is_goalkeeper from public.jugadores where partido_id=$1 and usuario_id=$2', [matchId, FIELD])).rows[0];
  eq(jg.is_goalkeeper, false, 'player request never marks goalkeeper');

  // A rejected request can never be approved, even by a direct RPC call.
  await admin.query(`insert into public.usuarios (id, nombre, posiciones) values ($1,'GKrej', array['ARQ'])`, [GK_OFF]);
  const reqRejected = (await admin.query(`insert into public.match_join_requests (match_id, user_id, role, status) values ($1,$2,'goalkeeper','rejected') returning id`, [matchId, GK_OFF])).rows[0].id;
  let rejectedApprovalBlocked = false;
  try {
    await adminAsUser.query('select public.approve_join_request($1)', [reqRejected]);
  } catch (e) {
    rejectedApprovalBlocked = /no está pendiente/i.test(String(e.message));
  }
  ok(rejectedApprovalBlocked, 'a rejected request cannot be approved');
  const rejectedJugador = (await admin.query('select 1 from public.jugadores where partido_id=$1 and usuario_id=$2', [matchId, GK_OFF])).rowCount;
  eq(rejectedJugador, 0, 'rejected-then-approve never inserts the player');

  await admin.query(`insert into public.usuarios (id, nombre, posiciones) values ($1,'GKplayer', array['ARQ'])`, [GK_FAR]);
  const reqPlayer = (await admin.query(`insert into public.match_join_requests (match_id, user_id, role) values ($1,$2,'player') returning id`, [matchId, GK_FAR])).rows[0].id;
  await adminAsUser.query('select public.approve_join_request($1)', [reqPlayer]);
  jg = (await admin.query('select is_goalkeeper from public.jugadores where partido_id=$1 and usuario_id=$2', [matchId, GK_FAR])).rows[0];
  eq(jg.is_goalkeeper, false, 'player request never auto-marks goalkeeper');

  console.log('\n▶ Creation guard: goalkeeper estricto + PLAYER compatible (no exige falta_jugadores)');
  await admin.query(`insert into public.usuarios (id, nombre) values ($1,'FlagAdmin')`, [FLAG_ADMIN]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones) values ($1,'FlagArq', array['ARQ'])`, [FLAG_ARQ]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones) values ($1,'FlagField', array['DEF'])`, [FLAG_FIELD]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones) values ($1,'FlagLegacy', array['DEL'])`, [FLAG_LEGACY]);

  const mkMatch = async (falta, busca) => (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, modalidad, cupo_jugadores, creado_por, estado, falta_jugadores, busca_arquero)
     values ('Flags', (now() + interval '3 days')::date, '20:00', 'Cancha', 'F5', 10, $1, 'active', $2, $3) returning id`,
    [FLAG_ADMIN, falta, busca])).rows[0].id;
  const reqInsert = (mid, uid, role) =>
    `insert into public.match_join_requests (match_id, user_id, role) values (${mid},'${uid}','${role}')`;
  const reqCount = async (mid, uid) =>
    (await admin.query('select 1 from public.match_join_requests where match_id=$1 and user_id=$2', [mid, uid])).rowCount;

  // Backward compatibility: a PLAYER request is accepted regardless of
  // falta_jugadores — including a role-less (legacy) insert and a fully-closed
  // match — so already-installed clients keep working. A goalkeeper request on a
  // match not searching a GK is still rejected.
  const mClosed = await mkMatch(false, false); // neither flag
  await admin.query(reqInsert(mClosed, FLAG_FIELD, 'player'));
  eq(await reqCount(mClosed, FLAG_FIELD), 1, 'closed match: explicit player request accepted (legacy compat)');
  await admin.query(`insert into public.match_join_requests (match_id, user_id) values (${mClosed},'${FLAG_LEGACY}')`);
  eq(await reqCount(mClosed, FLAG_LEGACY), 1, 'closed match: role-less (legacy) request accepted as player');
  ok(/no está buscando arquero/i.test(await expectFailure(admin, reqInsert(mClosed, FLAG_ARQ, 'goalkeeper'))),
    'closed match: goalkeeper request rejected (busca_arquero=false)');

  // Players-only → player accepted; goalkeeper rejected (match not searching a GK).
  const mPlayers = await mkMatch(true, false);
  await admin.query(reqInsert(mPlayers, FLAG_FIELD, 'player'));
  eq(await reqCount(mPlayers, FLAG_FIELD), 1, 'players-only: player request accepted');
  ok(/no está buscando arquero/i.test(await expectFailure(admin, reqInsert(mPlayers, FLAG_ARQ, 'goalkeeper'))),
    'players-only: goalkeeper request rejected');

  // Goalkeeper-only → ARQ goalkeeper accepted; non-ARQ goalkeeper REJECTED (never
  // coerced); a PLAYER request is still accepted (legacy compat).
  const mGk = await mkMatch(false, true);
  await admin.query(reqInsert(mGk, FLAG_ARQ, 'goalkeeper'));
  eq(await reqCount(mGk, FLAG_ARQ), 1, 'goalkeeper-only: ARQ goalkeeper request accepted');
  ok(/ARQ/i.test(await expectFailure(admin, reqInsert(mGk, FLAG_FIELD, 'goalkeeper'))),
    'goalkeeper-only: non-ARQ goalkeeper request rejected (not coerced)');
  await admin.query(reqInsert(mGk, FLAG_FIELD, 'player'));
  eq(await reqCount(mGk, FLAG_FIELD), 1, 'goalkeeper-only: player request still accepted (legacy compat)');

  // Both flags → both roles allowed.
  const mBoth = await mkMatch(true, true);
  await admin.query(reqInsert(mBoth, FLAG_FIELD, 'player'));
  await admin.query(reqInsert(mBoth, FLAG_ARQ, 'goalkeeper'));
  eq((await admin.query('select count(*)::int c from public.match_join_requests where match_id=$1', [mBoth])).rows[0].c, 2,
    'both flags: player and goalkeeper requests both accepted');

  console.log('\n▶ Capacidad: cupo titulares + hasta 4 suplentes, nunca un 5º (no expulsa a nadie)');
  await admin.query(`insert into public.usuarios (id, nombre) values ($1,'CapAdmin')`, [CAP_ADMIN]);
  for (const uid of CAP_USERS) {
    await admin.query(`insert into public.usuarios (id, nombre, posiciones) values ($1,'CapUser', array['DEF'])`, [uid]);
  }
  const capMatch = (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, modalidad, cupo_jugadores, creado_por, estado, falta_jugadores)
     values ('Cap', (now() + interval '3 days')::date, '20:00', 'Cancha', 'F5', 1, $1, 'active', true) returning id`,
    [CAP_ADMIN])).rows[0].id;
  const capAdminSession = await connect(CAP_ADMIN);

  // cupo=1 → the 1st approval is a titular, the next 4 are suplentes, the 6th is full.
  const capOutcomes = [];
  for (let i = 0; i < 6; i += 1) {
    const reqId = (await admin.query(
      `insert into public.match_join_requests (match_id, user_id, role) values ($1,$2,'player') returning id`,
      [capMatch, CAP_USERS[i]])).rows[0].id;
    try {
      const res = (await capAdminSession.query('select public.approve_join_request($1) as r', [reqId])).rows[0].r;
      capOutcomes.push(res.is_substitute ? 'sub' : 'titular');
    } catch (e) {
      capOutcomes.push(/completo/i.test(String(e.message)) ? 'full' : `err:${e.message}`);
    }
  }
  eq(capOutcomes, ['titular', 'sub', 'sub', 'sub', 'sub', 'full'],
    'cupo=1: 1 titular, 4 suplentes, luego "partido completo"');
  const capCounts = (await admin.query(
    `select count(*) filter (where not coalesce(is_substitute,false))::int as titulares,
            count(*) filter (where coalesce(is_substitute,false))::int as suplentes
       from public.jugadores where partido_id=$1`, [capMatch])).rows[0];
  eq(capCounts, { titulares: 1, suplentes: 4 }, 'plantel final = 1 titular + 4 suplentes (nunca un 5º suplente)');

  console.log('\n▶ Concurrencia: un solo lugar, dos aprobaciones casi simultáneas → solo una entra');
  await admin.query(`insert into public.usuarios (id, nombre) values ($1,'RaceAdmin')`, [RACE_ADMIN]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones) values ($1,'RaceA', array['DEF'])`, [RACE_A]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones) values ($1,'RaceB', array['DEF'])`, [RACE_B]);
  const raceMatch = (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, modalidad, cupo_jugadores, creado_por, estado, falta_jugadores)
     values ('Race', (now() + interval '3 days')::date, '20:00', 'Cancha', 'F5', 1, $1, 'active', true) returning id`,
    [RACE_ADMIN])).rows[0].id;
  // Pre-fill so EXACTLY one open slot remains (cupo=1 → 1 titular + up to 4 subs;
  // here 1 titular + 3 subs, leaving the 4th substitute slot as the last one).
  await admin.query(`insert into public.jugadores (partido_id, usuario_id, nombre, is_substitute) values
    ($1, $2, 'pre-titular', false),
    ($1, $3, 'pre-sub1', true),
    ($1, $4, 'pre-sub2', true),
    ($1, $5, 'pre-sub3', true)`,
    [raceMatch, CAP_USERS[6], CAP_USERS[7], FLAG_ARQ, FLAG_FIELD]);
  const reqRaceA = (await admin.query(`insert into public.match_join_requests (match_id, user_id, role) values ($1,$2,'player') returning id`, [raceMatch, RACE_A])).rows[0].id;
  const reqRaceB = (await admin.query(`insert into public.match_join_requests (match_id, user_id, role) values ($1,$2,'player') returning id`, [raceMatch, RACE_B])).rows[0].id;

  const sessionA = await connect(RACE_ADMIN);
  const sessionB = await connect(RACE_ADMIN);
  await sessionA.query('begin');
  await sessionB.query('begin');
  // A takes the match lock, fills the last slot, and holds its transaction open.
  await sessionA.query('select public.approve_join_request($1)', [reqRaceA]);
  // B races for the same last slot: it BLOCKS on the match-row lock until A commits.
  const bPromise = sessionB.query('select public.approve_join_request($1) as r', [reqRaceB]);
  await sleep(300); // give B time to reach (and block on) the lock
  await sessionA.query('commit');

  let bError = '';
  try {
    await bPromise;
    await sessionB.query('commit');
  } catch (e) {
    bError = String(e.message || e);
    await sessionB.query('rollback');
  }
  ok(/completo/i.test(bError), 'second concurrent approval fails safely (partido completo)', bError || '(no error)');

  const raceFinal = (await admin.query(
    `select count(*)::int as total,
            count(*) filter (where not coalesce(is_substitute,false))::int as titulares,
            count(*) filter (where coalesce(is_substitute,false))::int as suplentes,
            count(distinct usuario_id)::int as distintos
       from public.jugadores where partido_id=$1`, [raceMatch])).rows[0];
  eq(raceFinal.total, 5, 'roster stays at the cap (1 titular + 4 suplentes = 5), never over the limit');
  eq(raceFinal.titulares, 1, 'never more than cupo titulares under concurrency');
  eq(raceFinal.suplentes, 4, 'never a 5th substitute under concurrency');
  eq(raceFinal.distintos, 5, 'no duplicate players');
  eq((await admin.query('select 1 from public.jugadores where partido_id=$1 and usuario_id=$2', [raceMatch, RACE_A])).rowCount, 1, 'the winning request entered exactly once');
  eq((await admin.query('select 1 from public.jugadores where partido_id=$1 and usuario_id=$2', [raceMatch, RACE_B])).rowCount, 0, 'the losing request never entered the match');

  console.log('\n▶ notify_available_goalkeepers (eligibility + radius + dedupe)');
  // Fresh match for the notification scenario — clear dependents first (FKs).
  await admin.query('delete from public.jugadores');
  await admin.query('delete from public.match_join_requests');
  await admin.query('delete from public.notifications');
  await admin.query('delete from public.partidos');
  await admin.query('delete from public.usuarios where id = any($1)', [[GK_NEAR, GK_FAR, GK_OFF, FIELD, GK_IN_MATCH, GK_SECOND]]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, disponible_arquero, latitud, longitud) values
    ($1,'GKnear',   array['ARQ'],       true,  -34.61, -58.38),
    ($2,'GKfar',    array['ARQ'],       true,  -34.95, -58.38),
    ($3,'GKoff',    array['ARQ'],       false, -34.61, -58.38),
    ($4,'Field',    array['DEF'],       false, -34.61, -58.38),
    ($5,'GKin',     array['ARQ'],       true,  -34.61, -58.38),
    ($6,'GKsecond', array['DEL','ARQ'], true,  -34.615, -58.38)`, [GK_NEAR, GK_FAR, GK_OFF, FIELD, GK_IN_MATCH, GK_SECOND]);
  const gkMatch = (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, sede_direccion_normalizada, sede_latitud, sede_longitud, modalidad, cupo_jugadores, creado_por, estado, busca_arquero)
     values ('GKsearch', (now() + interval '3 days')::date, '21:00', 'Cancha Centro', 'Palermo', -34.60, -58.38, 'F5', 10, $1, 'active', true) returning id`, [ADMIN])).rows[0].id;
  await admin.query(`insert into public.jugadores (partido_id, usuario_id, nombre) values ($1,$2,'GKin')`, [gkMatch, GK_IN_MATCH]);

  const notified1 = (await adminAsUser.query('select public.notify_available_goalkeepers($1, 30) as r', [gkMatch])).rows[0].r;
  // GKnear (ARQ) and GKsecond (ARQ as 2nd position) are eligible; GKfar (radius),
  // GKoff (no availability), Field (no ARQ), GKin (already in match) and the admin
  // (actor) are all excluded.
  eq(notified1.notified, 2, 'near available goalkeepers notified (ARQ as 1st or 2nd position)');
  const recipients = (await admin.query(`select user_id from public.notifications where partido_id=$1 and type='match_needs_goalkeeper' order by user_id`, [gkMatch])).rows.map((r) => r.user_id);
  eq(recipients, [GK_NEAR, GK_SECOND], 'recipients are exactly the two eligible near goalkeepers');

  // Deep link opens the correct match.
  const link = (await admin.query(`select data->>'link' AS link from public.notifications where partido_id=$1 and type='match_needs_goalkeeper' limit 1`, [gkMatch])).rows[0].link;
  eq(link, `/partido-publico/${gkMatch}`, 'notification deep link points to the correct match');

  const notified2 = (await adminAsUser.query('select public.notify_available_goalkeepers($1, 30) as r', [gkMatch])).rows[0].r;
  eq(notified2.notified, 0, 're-running does not re-notify (dedupe)');

  await admin.query('update public.partidos set busca_arquero = false where id=$1', [gkMatch]);
  const notified3 = (await adminAsUser.query('select public.notify_available_goalkeepers($1, 30) as r', [gkMatch])).rows[0].r;
  eq(notified3.reason, 'not_searching_goalkeeper', 'no fan-out when not searching a goalkeeper');

  // Non-admin cannot trigger the fan-out for someone else's match.
  const outsider = await connect(GK_NEAR);
  let forbidden = false;
  try { await outsider.query('select public.notify_available_goalkeepers($1, 30)', [gkMatch]); } catch (e) { forbidden = /Forbidden/.test(String(e.message)); }
  ok(forbidden, 'non-admin cannot fan out for a match they do not own');
}

main()
  .catch((error) => { console.error('\n💥 Error inesperado:', error); failures += 1; })
  .finally(async () => {
    for (const client of clients) { try { await client.end(); } catch { /* noop */ } }
    try { await postgres.stop(); } catch { /* noop */ }
    try { fs.rmSync(DATA_DIR, { recursive: true, force: true }); } catch { /* noop */ }
    console.log(`\n${failures === 0 ? '✅' : '❌'} ${checks - failures}/${checks} checks OK`);
    process.exit(failures === 0 ? 0 : 1);
  });
