#!/usr/bin/env node
// Focused DB integration test for the PR #87 smoke fixes:
//   * 20260719120000_goalkeeper_search_notification_reliability.sql
//       - push channel mapping for 'match_needs_goalkeeper'
//       - reliable fan-out via an AFTER INSERT/UPDATE trigger on partidos
//   * 20260719121000_demote_join_request_on_player_removal.sql
//       - atomic demotion of an approved request when the player is removed
//
// Boots an embedded Postgres, applies a minimal self-contained stub of the prod
// core (same shape used by goalkeeper.mjs), then applies the already-in-prod
// feature migration plus the two forward fixes, and exercises the invariants
// against real SQL.
//
// Uso: npm run test:db:goalkeeper:notifications

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import EmbeddedPostgres from 'embedded-postgres';
import pg from 'pg';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const MIGRATIONS = [
  '20260718120000_multi_positions_and_goalkeeper_availability.sql',
  '20260719120000_goalkeeper_search_notification_reliability.sql',
  '20260719121000_demote_join_request_on_player_removal.sql',
];

const PORT = 55200 + Math.floor(Math.random() * 400);
const DB_NAME = 'arma2_gk_notif';
const DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'arma2-gknotif-pg-'));

const ORG = '00000000-0000-4000-8000-0000000000a1';       // organizer / actor
const GK_NEAR = '00000000-0000-4000-8000-0000000000b1';    // ARQ, available, in radius
const GK_FAR = '00000000-0000-4000-8000-0000000000b2';     // ARQ, available, out of radius
const GK_UNAVAIL = '00000000-0000-4000-8000-0000000000b3'; // ARQ, NOT available
const GK_SECOND = '00000000-0000-4000-8000-0000000000b4';  // ARQ as SECOND position, available
const GK_PARTICIPANT = '00000000-0000-4000-8000-0000000000b5'; // ARQ available but already in match
const GK_NOTOKEN = '00000000-0000-4000-8000-0000000000b6';  // ARQ available, no push token registered
const FIELD = '00000000-0000-4000-8000-0000000000c1';      // no ARQ

let failures = 0;
let checks = 0;
const clients = [];

const ok = (condition, label, extra = '') => {
  checks += 1;
  if (condition) {
    console.log(`  ✔ ${label}`);
  } else {
    failures += 1;
    console.error(`  ✘ ${label}${extra ? ` — ${extra}` : ''}`);
  }
};
const eq = (actual, expected, label) =>
  ok(JSON.stringify(actual) === JSON.stringify(expected), label, `esperado ${JSON.stringify(expected)}, obtenido ${JSON.stringify(actual)}`);

const STUB_SCHEMA = `
create schema if not exists auth;
create table auth.users (id uuid primary key);
create or replace function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
create role authenticated;
create role anon;

create table public.usuarios (
  id uuid primary key,
  nombre text,
  avatar_url text,
  latitud double precision,
  longitud double precision,
  posicion text,
  created_at timestamptz not null default now()
);
create table public.profiles (id uuid primary key, nombre text, avatar_url text);
create table public.partidos (
  id bigint generated by default as identity primary key,
  nombre text,
  fecha date,
  hora text,
  sede text,
  sede_direccion_normalizada text,
  sede_latitud double precision,
  sede_longitud double precision,
  modalidad text,
  cupo_jugadores integer,
  falta_jugadores boolean not null default false,
  creado_por uuid references public.usuarios(id),
  estado text,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);
create table public.jugadores (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  usuario_id uuid references public.usuarios(id),
  nombre text,
  avatar_url text,
  score numeric,
  is_goalkeeper boolean default false,
  created_at timestamptz not null default now()
);
create unique index jugadores_partido_usuario_uidx
  on public.jugadores (partido_id, usuario_id);
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.usuarios(id),
  type text not null,
  title text,
  message text,
  data jsonb,
  read boolean default false,
  partido_id bigint,
  created_at timestamptz not null default now()
);
create table public.match_join_requests (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.partidos(id) on delete cascade,
  user_id uuid not null references public.usuarios(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid
);

create or replace function public.coordinates_are_valid(p_lat double precision, p_lng double precision)
returns boolean language sql immutable as $$
  select p_lat is not null and p_lng is not null
    and p_lat between -90 and 90 and p_lng between -180 and 180
    and not (abs(p_lat) < 0.0001 and abs(p_lng) < 0.0001);
$$;
create or replace function public.haversine_km(a double precision, b double precision, c double precision, d double precision)
returns double precision language sql immutable as $$
  select case when not public.coordinates_are_valid(a,b) or not public.coordinates_are_valid(c,d) then null
    else 6371::double precision * 2 * atan2(
      sqrt(sin(radians(c-a)/2)^2 + cos(radians(a))*cos(radians(c))*sin(radians(d-b)/2)^2),
      sqrt(1 - (sin(radians(c-a)/2)^2 + cos(radians(a))*cos(radians(c))*sin(radians(d-b)/2)^2))) end;
$$;
create or replace function public.partido_kickoff_at(p_fecha date, p_hora text)
returns timestamptz language sql immutable as $$
  select case when p_fecha is null or coalesce(p_hora,'') = '' then null
    else (p_fecha + (left(p_hora,5) || ':00')::time) at time zone 'America/Argentina/Buenos_Aires' end;
$$;

grant all on all tables in schema public to authenticated;
grant usage on all sequences in schema public to authenticated;
grant usage on schema public to authenticated;
`;

const postgres = new EmbeddedPostgres({
  databaseDir: DATA_DIR, user: 'postgres', password: 'password', port: PORT,
  persistent: false, onLog: () => {}, onError: () => {},
});

async function connect(uid = null) {
  const client = new pg.Client({ host: '127.0.0.1', port: PORT, user: 'postgres', password: 'password', database: DB_NAME });
  await client.connect();
  clients.push(client);
  if (uid) {
    await client.query("select set_config('request.jwt.claim.sub', $1, false)", [uid]);
    await client.query('set role authenticated');
  }
  return client;
}

// Kickoff helpers: build a future / past match consistently.
const FUTURE = "(now() + interval '3 days')::date";
const PAST = "(now() - interval '3 days')::date";

async function notifCount(db, matchId, userId) {
  return (await db.query(
    "select count(*)::int c from public.notifications where partido_id=$1 and user_id=$2 and type='match_needs_goalkeeper'",
    [matchId, userId],
  )).rows[0].c;
}

async function main() {
  await postgres.initialise();
  await postgres.start();
  await postgres.createDatabase(DB_NAME);

  const admin = await connect();
  await admin.query(STUB_SCHEMA);
  for (const m of MIGRATIONS) {
    await admin.query(fs.readFileSync(path.join(ROOT, 'supabase', 'migrations', m), 'utf8'));
  }
  await admin.query('grant all on all tables in schema public to authenticated');
  await admin.query('grant usage on all sequences in schema public to authenticated');

  // Users. Match at Buenos Aires centre; near GK ~0.5km, far GK ~far away.
  await admin.query(`insert into public.usuarios (id, nombre, latitud, longitud) values ($1,'Org',-34.60,-58.38)`, [ORG]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, disponible_arquero, latitud, longitud) values ($1,'GKnear', array['ARQ'], true, -34.605, -58.381)`, [GK_NEAR]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, disponible_arquero, latitud, longitud) values ($1,'GKfar', array['ARQ'], true, -34.90, -58.90)`, [GK_FAR]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, disponible_arquero, latitud, longitud) values ($1,'GKunavail', array['ARQ'], false, -34.605, -58.381)`, [GK_UNAVAIL]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, disponible_arquero, latitud, longitud) values ($1,'GKsecond', array['DEF','ARQ'], true, -34.606, -58.382)`, [GK_SECOND]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, disponible_arquero, latitud, longitud) values ($1,'GKpart', array['ARQ'], true, -34.604, -58.380)`, [GK_PARTICIPANT]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, disponible_arquero, latitud, longitud) values ($1,'GKnotoken', array['ARQ'], true, -34.607, -58.383)`, [GK_NOTOKEN]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, latitud, longitud) values ($1,'Field', array['DEF'], -34.60, -58.38)`, [FIELD]);

  // -----------------------------------------------------------------
  console.log('\n▶ Channel mapping so the notification actually pushes');
  const ch = (await admin.query("select public.notification_event_channel('match_needs_goalkeeper') as c")).rows[0].c;
  eq(ch, 'GOALKEEPER_SEARCH', "match_needs_goalkeeper maps to GOALKEEPER_SEARCH (not INFO)");
  const allows = (await admin.query("select public.notification_channel_allows_push(public.notification_event_channel('match_needs_goalkeeper')) as a")).rows[0].a;
  eq(allows, true, 'GOALKEEPER_SEARCH is push-allowed (the fix for "no push")');
  // Regression guard: existing mappings still intact.
  eq((await admin.query("select public.notification_event_channel('match_invite') as c")).rows[0].c, 'INVITATION', 'existing channel mapping preserved');

  // -----------------------------------------------------------------
  console.log('\n▶ Fan-out on CREATION with busca_arquero=true (trigger, no frontend)');
  const m1 = (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, sede_direccion_normalizada, sede_latitud, sede_longitud, modalidad, cupo_jugadores, creado_por, estado, falta_jugadores, busca_arquero)
     values ('Create', ${FUTURE}, '20:00', 'Cancha Centro', 'Av Siempre Viva 123', -34.60, -58.38, 'F5', 10, $1, 'active', false, true) returning id`, [ORG])).rows[0].id;

  eq(await notifCount(admin, m1, GK_NEAR), 1, 'near ARQ available in radius → notified on creation');
  eq(await notifCount(admin, m1, GK_SECOND), 1, 'ARQ as SECOND position → notified');
  eq(await notifCount(admin, m1, GK_NOTOKEN), 1, 'ARQ without push token → still gets in-app notification');
  eq(await notifCount(admin, m1, GK_FAR), 0, 'ARQ out of radius → excluded');
  eq(await notifCount(admin, m1, GK_UNAVAIL), 0, 'ARQ not available → excluded');
  eq(await notifCount(admin, m1, FIELD), 0, 'non-ARQ → excluded');
  eq(await notifCount(admin, m1, ORG), 0, 'organizer → excluded');

  // Deep link points to the right match.
  const link = (await admin.query("select data->>'link' l from public.notifications where partido_id=$1 and user_id=$2 and type='match_needs_goalkeeper'", [m1, GK_NEAR])).rows[0].l;
  eq(link, `/partido-publico/${m1}`, 'deep link points at the correct match');

  // -----------------------------------------------------------------
  console.log('\n▶ Already-participant is excluded on creation');
  const m2 = (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, sede_latitud, sede_longitud, modalidad, cupo_jugadores, creado_por, estado, busca_arquero)
     values ('WithPart', ${FUTURE}, '20:00', 'Cancha', -34.60, -58.38, 'F5', 10, $1, 'active', false) returning id`, [ORG])).rows[0].id;
  await admin.query(`insert into public.jugadores (partido_id, usuario_id, nombre, score) values ($1,$2,'GKpart',5)`, [m2, GK_PARTICIPANT]);
  // Now turn the search on → participant must not be notified.
  await admin.query('update public.partidos set busca_arquero=true where id=$1', [m2]);
  eq(await notifCount(admin, m2, GK_PARTICIPANT), 0, 'ARQ already in the match → excluded');
  eq(await notifCount(admin, m2, GK_NEAR), 1, 'other eligible ARQ still notified on activation');

  // -----------------------------------------------------------------
  console.log('\n▶ Activation later (false→true) + second activation is deduped (no spam)');
  const m3 = (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, sede_latitud, sede_longitud, modalidad, cupo_jugadores, creado_por, estado, busca_arquero)
     values ('Toggle', ${FUTURE}, '20:00', 'Cancha', -34.60, -58.38, 'F5', 10, $1, 'active', false) returning id`, [ORG])).rows[0].id;
  eq(await notifCount(admin, m3, GK_NEAR), 0, 'no notification while busca_arquero=false');
  await admin.query('update public.partidos set busca_arquero=true where id=$1', [m3]);
  eq(await notifCount(admin, m3, GK_NEAR), 1, 'activation later notifies eligible ARQ');
  // Toggle off then on again → deduped by the unique index, no second notification.
  await admin.query('update public.partidos set busca_arquero=false where id=$1', [m3]);
  await admin.query('update public.partidos set busca_arquero=true where id=$1', [m3]);
  eq(await notifCount(admin, m3, GK_NEAR), 1, 'off→on again does NOT spam (deduped exactly once)');

  // -----------------------------------------------------------------
  console.log('\n▶ Future-only: a past match never notifies');
  const m4 = (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, sede_latitud, sede_longitud, modalidad, cupo_jugadores, creado_por, estado, busca_arquero)
     values ('Past', ${PAST}, '20:00', 'Cancha', -34.60, -58.38, 'F5', 10, $1, 'active', true) returning id`, [ORG])).rows[0].id;
  eq(await notifCount(admin, m4, GK_NEAR), 0, 'past match → nobody notified');

  // -----------------------------------------------------------------
  console.log('\n▶ RPC still works and is deduped against the trigger');
  const orgAsUser = await connect(ORG);
  const rpc = (await orgAsUser.query('select public.notify_available_goalkeepers($1) as r', [m1])).rows[0].r;
  eq(rpc.ok, true, 'notify_available_goalkeepers RPC returns ok');
  eq(await notifCount(admin, m1, GK_NEAR), 1, 'RPC re-run does not create a duplicate (already notified by trigger)');
  // Non-owner cannot call the RPC.
  const strangerAsUser = await connect(GK_NEAR);
  let forbidden = false;
  try { await strangerAsUser.query('select public.notify_available_goalkeepers($1)', [m1]); }
  catch (e) { forbidden = /Forbidden/.test(String(e.message)); }
  ok(forbidden, 'non-organizer cannot trigger the fan-out RPC');

  // -----------------------------------------------------------------
  console.log('\n▶ Eject demotion: approved request → rejected atomically when player removed');
  const m5 = (await admin.query(
    `insert into public.partidos (nombre, fecha, hora, sede, sede_latitud, sede_longitud, modalidad, cupo_jugadores, creado_por, estado, falta_jugadores, busca_arquero)
     values ('Eject', ${FUTURE}, '20:00', 'Cancha', -34.60, -58.38, 'F5', 10, $1, 'active', true, false) returning id`, [ORG])).rows[0].id;

  // pending → approve via RPC → jugador created.
  const req = (await admin.query(`insert into public.match_join_requests (match_id, user_id, role) values ($1,$2,'player') returning id`, [m5, FIELD])).rows[0].id;
  eq((await admin.query('select status from public.match_join_requests where id=$1', [req])).rows[0].status, 'pending', 'request starts pending');
  await orgAsUser.query('select public.approve_join_request($1)', [req]);
  eq((await admin.query('select status from public.match_join_requests where id=$1', [req])).rows[0].status, 'approved', 'request approved');
  const jid = (await admin.query('select id from public.jugadores where partido_id=$1 and usuario_id=$2', [m5, FIELD])).rows[0].id;
  ok(jid != null, 'participation row created');

  // Eject: delete the jugador row → trigger demotes the approved request atomically.
  await admin.query('delete from public.jugadores where id=$1', [jid]);
  eq((await admin.query('select status from public.match_join_requests where id=$1', [req])).rows[0].status, 'rejected', 'approved request is demoted to rejected on removal');
  eq((await admin.query('select count(*)::int c from public.jugadores where partido_id=$1 and usuario_id=$2', [m5, FIELD])).rows[0].c, 0, 'player no longer in roster');

  // The old rejected request can never silently re-add the player.
  let rejApprove = false;
  try { await orgAsUser.query('select public.approve_join_request($1)', [req]); }
  catch (e) { rejApprove = /no está pendiente/i.test(String(e.message)); }
  ok(rejApprove, 'a demoted (rejected) request cannot be re-approved');

  // The user can request again later (reopen the row to pending — unique/duplicate path).
  await admin.query(`update public.match_join_requests set status='pending', decided_at=null where id=$1`, [req]);
  eq((await admin.query('select status from public.match_join_requests where id=$1', [req])).rows[0].status, 'pending', 'user can request again (no permanent block)');

  // Manually-added player (no usuario_id) removal never errors.
  await admin.query(`insert into public.jugadores (partido_id, nombre, score) values ($1,'Guest',5)`, [m5]);
  const guestId = (await admin.query('select id from public.jugadores where partido_id=$1 and usuario_id is null', [m5])).rows[0].id;
  let guestDeleteOk = true;
  try { await admin.query('delete from public.jugadores where id=$1', [guestId]); }
  catch { guestDeleteOk = false; }
  ok(guestDeleteOk, 'removing a manually-added player (no usuario_id) does not error');

  console.log(`\n${failures === 0 ? '✅' : '❌'} ${checks - failures}/${checks} checks passed`);
}

main()
  .catch((err) => { console.error(err); failures += 1; })
  .finally(async () => {
    for (const c of clients) { try { await c.end(); } catch {} }
    try { await postgres.stop(); } catch {}
    try { fs.rmSync(DATA_DIR, { recursive: true, force: true }); } catch {}
    process.exit(failures === 0 ? 0 : 1);
  });
