#!/usr/bin/env node
// Focused DB integration test: legacy vs v2 Quiero Jugar surface.
//
// Applies the REAL legacy migration (20260320110000 — defines
// `partidos_abiertos_operativos` + `get_open_matches_for_quiero_jugar` with the
// historical `falta_jugadores`-only "operationally open" condition) and the REAL
// v2 migration (20260718121000 — adds the `*_v2` objects that ALSO open on
// `busca_arquero`), on a self-contained stub. Proves the legacy objects keep their
// pre-PR behavior (apps already installed never start seeing busca_arquero-only
// matches) while the new v2 surface exposes them.
//
// Uso: npm run test:db:quierojugar

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import EmbeddedPostgres from 'embedded-postgres';
import pg from 'pg';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const MIGRATIONS = [
  '20260320110000_quiero_jugar_authoritative_open_matches.sql',
  '20260320133000_quiero_jugar_backfill_and_permissions.sql',
  '20260718121000_quiero_jugar_expose_busca_arquero.sql',
];

const PORT = 55200 + Math.floor(Math.random() * 400);
const DB_NAME = 'arma2_quiero_jugar_v2';
const DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'arma2-qj-pg-'));
const ADMIN = '00000000-0000-4000-8000-0000000000a1';

let failures = 0;
let checks = 0;
const clients = [];

const ok = (condition, label, extra = '') => {
  checks += 1;
  if (condition) {
    console.log(`  ✔ ${label}`);
  } else {
    failures += 1;
    console.error(`  ✘ ${label}${extra ? ` — ${extra}` : ''}`);
  }
};
const eq = (actual, expected, label) =>
  ok(JSON.stringify(actual) === JSON.stringify(expected), label, `esperado ${JSON.stringify(expected)}, obtenido ${JSON.stringify(actual)}`);

const STUB_SCHEMA = `
create schema if not exists auth;
create table auth.users (id uuid primary key);
create or replace function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
create role authenticated;
create role anon;

create table public.usuarios (id uuid primary key, nombre text);

create table public.partidos (
  id bigint generated by default as identity primary key,
  match_ref uuid,
  codigo text unique,
  nombre text,
  fecha date,
  hora text,
  sede text,
  sede_place_id text,
  sede_direccion_normalizada text,
  sede_latitud double precision,
  sede_longitud double precision,
  "sedeMaps" jsonb,
  modalidad text,
  cupo_jugadores integer,
  falta_jugadores boolean default false,
  busca_arquero boolean not null default false,
  tipo_partido text,
  creado_por uuid references public.usuarios(id),
  estado text,
  survey_status text,
  result_status text,
  finished_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table public.partidos_frecuentes (
  id bigint generated by default as identity primary key,
  sede text,
  sede_place_id text,
  sede_direccion_normalizada text,
  sede_latitud double precision,
  sede_longitud double precision
);

create table public.jugadores (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  usuario_id uuid references public.usuarios(id),
  nombre text
);

grant all on all tables in schema public to authenticated;
grant usage on all sequences in schema public to authenticated;
grant usage on schema public to authenticated, anon;
`;

const postgres = new EmbeddedPostgres({
  databaseDir: DATA_DIR, user: 'postgres', password: 'password', port: PORT,
  persistent: false, onLog: () => {}, onError: () => {},
});

async function connect() {
  const client = new pg.Client({ host: '127.0.0.1', port: PORT, user: 'postgres', password: 'password', database: DB_NAME });
  await client.connect();
  clients.push(client);
  return client;
}

async function insertMatch(admin, nombre, falta, busca) {
  const id = (await admin.query(
    `insert into public.partidos
       (nombre, fecha, hora, sede, sede_latitud, sede_longitud, modalidad, cupo_jugadores, creado_por, estado, falta_jugadores, busca_arquero)
     values ($1, (now() + interval '3 days')::date, '20:00', 'Cancha', -34.60, -58.40, 'F5', 10, $2, 'active', $3, $4)
     returning id`,
    [nombre, ADMIN, falta, busca],
  )).rows[0].id;
  return Number(id);
}

async function main() {
  await postgres.initialise();
  await postgres.start();
  await postgres.createDatabase(DB_NAME);

  const admin = await connect();
  await admin.query(STUB_SCHEMA);
  for (const migration of MIGRATIONS) {
    await admin.query(fs.readFileSync(path.join(ROOT, 'supabase', 'migrations', migration), 'utf8'));
  }
  await admin.query('grant all on all tables in schema public to authenticated');
  await admin.query('grant usage on all sequences in schema public to authenticated');

  await admin.query(`insert into public.usuarios (id, nombre) values ($1,'Admin')`, [ADMIN]);

  console.log('\n▶ Legacy vs v2 open-matches (busca_arquero-only visibility)');
  // Four active, future, valid-coord matches covering every flag combination.
  const players = await insertMatch(admin, 'PlayersOnly', true, false);
  const goalkeeper = await insertMatch(admin, 'GoalkeeperOnly', false, true);
  const both = await insertMatch(admin, 'Both', true, true);
  const neither = await insertMatch(admin, 'Neither', false, false);

  const legacyRows = (await admin.query('select * from public.get_open_matches_for_quiero_jugar(null, null, 30)')).rows;
  const legacyIds = legacyRows.map((r) => Number(r.id)).sort((a, b) => a - b);
  const v2Rows = (await admin.query('select * from public.get_open_matches_for_quiero_jugar_v2(null, null, 30)')).rows;
  const v2Ids = v2Rows.map((r) => Number(r.id)).sort((a, b) => a - b);

  // Legacy: falta_jugadores-only → players + both. NEVER goalkeeper-only or neither.
  eq(legacyIds, [players, both].sort((a, b) => a - b), 'legacy RPC returns exactly the falta_jugadores matches');
  ok(!legacyIds.includes(goalkeeper), 'legacy RPC hides busca_arquero-only matches (installed-app compat)');
  ok(!legacyIds.includes(neither), 'legacy RPC hides matches searching for nobody');
  ok(!('busca_arquero' in (legacyRows[0] || {})), 'legacy RPC does not expose busca_arquero (columns unchanged)');

  // v2: falta OR busca → players + goalkeeper + both. Never neither.
  eq(v2Ids, [players, goalkeeper, both].sort((a, b) => a - b), 'v2 RPC returns players, goalkeeper-only and both');
  ok(v2Ids.includes(goalkeeper), 'v2 RPC shows busca_arquero-only matches');
  ok(!v2Ids.includes(neither), 'v2 RPC still hides matches searching for nobody');
  ok(v2Ids.filter((id) => id === both).length === 1, 'the "both" match appears exactly once in v2');
  ok('busca_arquero' in (v2Rows[0] || {}), 'v2 RPC exposes busca_arquero');
  const bothRow = v2Rows.find((r) => Number(r.id) === both);
  eq({ falta: bothRow.falta_jugadores, busca: bothRow.busca_arquero }, { falta: true, busca: true }, 'v2 "both" row carries both flags');
  const gkRow = v2Rows.find((r) => Number(r.id) === goalkeeper);
  eq({ falta: gkRow.falta_jugadores, busca: gkRow.busca_arquero }, { falta: false, busca: true }, 'v2 goalkeeper-only row carries busca_arquero only');

  // The view counts mirror the RPCs and prove the legacy view is untouched.
  const legacyViewCount = Number((await admin.query('select count(*)::int c from public.partidos_abiertos_operativos')).rows[0].c);
  const v2ViewCount = Number((await admin.query('select count(*)::int c from public.partidos_abiertos_operativos_v2')).rows[0].c);
  eq(legacyViewCount, 2, 'legacy view lists only the 2 falta_jugadores matches');
  eq(v2ViewCount, 3, 'v2 view lists the 3 open (players or goalkeeper) matches');

  // The legacy view must not even have a busca_arquero column.
  let legacyViewHasColumn = true;
  try {
    await admin.query('select busca_arquero from public.partidos_abiertos_operativos limit 1');
  } catch (e) {
    legacyViewHasColumn = !/busca_arquero/.test(String(e.message));
  }
  ok(!legacyViewHasColumn, 'legacy view has no busca_arquero column (semantics unchanged)');
}

main()
  .catch((error) => { console.error('\n💥 Error inesperado:', error); failures += 1; })
  .finally(async () => {
    for (const client of clients) { try { await client.end(); } catch { /* noop */ } }
    try { await postgres.stop(); } catch { /* noop */ }
    try { fs.rmSync(DATA_DIR, { recursive: true, force: true }); } catch { /* noop */ }
    console.log(`\n${failures === 0 ? '✅' : '❌'} ${checks - failures}/${checks} checks OK`);
    process.exit(failures === 0 ? 0 : 1);
  });
