#!/usr/bin/env node
// Focused DB integration test for "re-solicitud después de expulsión" (PR #87
// smoke finding: an ejected player cannot request again — "No se pudo enviar la
// solicitud").
//
// Boots an embedded Postgres and reproduces the PROD-FAITHFUL shape of the join
// pipeline that the bug depends on — the one the goalkeeper harness intentionally
// omits:
//   * match_join_requests carries a UNIQUE (match_id, user_id) row,
//   * RLS is ENABLED with the real policies (self INSERT/SELECT, admin-only
//     UPDATE), and
//   * the demote-on-removal trigger (20260719121000) and the new reopen RPC
//     (20260720120000) are applied on top of the goalkeeper migration.
//
// Then it drives the exact flow from real authenticated connections (RLS on):
// request → approve → eject → re-request as player / as goalkeeper, plus the
// invalid variants (no ARQ, match not searching a goalkeeper) and the toggle
// combinations. It also pins the ROOT CAUSE: the old client-side UPDATE
// rejected→pending affects ZERO rows under RLS, while the RPC reopens it.
//
// Uso: npm run test:db:rejoin

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import EmbeddedPostgres from 'embedded-postgres';
import pg from 'pg';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const MIGRATIONS = [
  '20260718120000_multi_positions_and_goalkeeper_availability.sql',
  '20260719121000_demote_join_request_on_player_removal.sql',
  '20260720120000_reopen_own_match_join_request.sql',
];

const PORT = 55200 + Math.floor(Math.random() * 400);
const DB_NAME = 'arma2_rejoin';
const DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'arma2-rejoin-pg-'));

const ADMIN = '00000000-0000-4000-8000-0000000000a1';
const PLAYER = '00000000-0000-4000-8000-0000000000b1'; // field player, no ARQ
const KEEPER = '00000000-0000-4000-8000-0000000000b2'; // has ARQ

let failures = 0;
let checks = 0;
const clients = [];

const ok = (condition, label, extra = '') => {
  checks += 1;
  if (condition) {
    console.log(`  ✔ ${label}`);
  } else {
    failures += 1;
    console.error(`  ✘ ${label}${extra ? ` — ${extra}` : ''}`);
  }
};
const eq = (actual, expected, label) =>
  ok(JSON.stringify(actual) === JSON.stringify(expected), label, `esperado ${JSON.stringify(expected)}, obtenido ${JSON.stringify(actual)}`);
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
// Runs a query expected to fail; returns the error message ('' if it unexpectedly succeeded).
const expectFailure = async (client, sql, params = []) => {
  try {
    await client.query(sql, params);
    return '';
  } catch (e) {
    return String(e.message || e);
  }
};

const STUB_SCHEMA = `
create schema if not exists auth;
create table auth.users (id uuid primary key);
create or replace function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
create role authenticated;
create role anon;

create table public.usuarios (
  id uuid primary key,
  nombre text,
  avatar_url text,
  latitud double precision,
  longitud double precision,
  posicion text,
  created_at timestamptz not null default now()
);
create table public.profiles (id uuid primary key, nombre text, avatar_url text);
create table public.partidos (
  id bigint generated by default as identity primary key,
  nombre text,
  fecha date,
  hora text,
  sede text,
  sede_direccion_normalizada text,
  sede_latitud double precision,
  sede_longitud double precision,
  modalidad text,
  cupo_jugadores integer,
  falta_jugadores boolean not null default false,
  creado_por uuid references public.usuarios(id),
  estado text,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);
create table public.jugadores (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  usuario_id uuid references public.usuarios(id),
  nombre text,
  avatar_url text,
  score numeric,
  is_goalkeeper boolean default false,
  created_at timestamptz not null default now()
);
create unique index jugadores_partido_usuario_uidx
  on public.jugadores (partido_id, usuario_id);
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.usuarios(id),
  type text not null,
  title text,
  message text,
  data jsonb,
  read boolean default false,
  partido_id bigint,
  created_at timestamptz not null default now()
);

-- match_join_requests: PROD shape — one unique row per (match, user) + RLS.
create table public.match_join_requests (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.partidos(id) on delete cascade,
  user_id uuid not null references public.usuarios(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid
);
-- The unique constraint that makes the client fall into the reopen/23505 path.
alter table public.match_join_requests
  add constraint match_join_requests_match_user_uidx unique (match_id, user_id);

-- RLS reproduced from 20260323135941_restore_match_join_requests_rls_and_grants:
-- the requester may INSERT/SELECT their OWN rows; only the admin may UPDATE.
alter table public.match_join_requests enable row level security;
grant select, insert, update on table public.match_join_requests to authenticated;
create policy "user can request join" on public.match_join_requests
  for insert to authenticated with check (auth.uid() = user_id);
create policy "user can read own requests" on public.match_join_requests
  for select to authenticated using (auth.uid() = user_id);
create policy "admin can read match requests" on public.match_join_requests
  for select to authenticated using (
    exists (select 1 from public.partidos p
            where p.id = match_join_requests.match_id and p.creado_por = auth.uid()));
create policy "admin can update match requests" on public.match_join_requests
  for update to authenticated using (
    exists (select 1 from public.partidos p
            where p.id = match_join_requests.match_id and p.creado_por = auth.uid()))
  with check (status in ('approved', 'rejected'));

-- Geo helpers the goalkeeper migration reuses.
create or replace function public.coordinates_are_valid(p_lat double precision, p_lng double precision)
returns boolean language sql immutable as $$
  select p_lat is not null and p_lng is not null
    and p_lat between -90 and 90 and p_lng between -180 and 180
    and not (abs(p_lat) < 0.0001 and abs(p_lng) < 0.0001);
$$;
create or replace function public.haversine_km(a double precision, b double precision, c double precision, d double precision)
returns double precision language sql immutable as $$
  select case when not public.coordinates_are_valid(a,b) or not public.coordinates_are_valid(c,d) then null
    else 6371::double precision * 2 * atan2(
      sqrt(sin(radians(c-a)/2)^2 + cos(radians(a))*cos(radians(c))*sin(radians(d-b)/2)^2),
      sqrt(1 - (sin(radians(c-a)/2)^2 + cos(radians(a))*cos(radians(c))*sin(radians(d-b)/2)^2))) end;
$$;
create or replace function public.partido_kickoff_at(p_fecha date, p_hora text)
returns timestamptz language sql immutable as $$
  select case when p_fecha is null or coalesce(p_hora,'') = '' then null
    else (p_fecha + (left(p_hora,5) || ':00')::time) at time zone 'America/Argentina/Buenos_Aires' end;
$$;

grant usage on schema public to authenticated;
grant usage on all sequences in schema public to authenticated;
-- Prod exposes these to authenticated (RLS governs rows). The grants also let the
-- FK referential-integrity checks on a match_join_requests INSERT read the
-- referenced rows as the requester.
grant select on public.partidos to authenticated;
grant select on public.usuarios to authenticated;
grant select on public.jugadores to authenticated;
`;

const postgres = new EmbeddedPostgres({
  databaseDir: DATA_DIR, user: 'postgres', password: 'password', port: PORT,
  persistent: false, onLog: () => {}, onError: () => {},
});

async function connect(uid = null) {
  const client = new pg.Client({ host: '127.0.0.1', port: PORT, user: 'postgres', password: 'password', database: DB_NAME });
  await client.connect();
  clients.push(client);
  if (uid) {
    await client.query("select set_config('request.jwt.claim.sub', $1, false)", [uid]);
    await client.query('set role authenticated');
  }
  return client;
}

// Insert a request as the requester (RLS INSERT policy path).
const insertOwnRequest = (asUser, matchId, role) =>
  asUser.query(
    `insert into public.match_join_requests (match_id, user_id, role) values ($1, $2, $3) returning id`,
    [matchId, asUser.__uid, role],
  );

const latestStatus = async (admin, matchId, userId) => (
  await admin.query(
    'select status, role from public.match_join_requests where match_id=$1 and user_id=$2',
    [matchId, userId],
  )
).rows[0];

async function main() {
  await postgres.initialise();
  await postgres.start();
  await postgres.createDatabase(DB_NAME);

  const admin = await connect();
  await admin.query(STUB_SCHEMA);
  for (const migration of MIGRATIONS) {
    await admin.query(fs.readFileSync(path.join(ROOT, 'supabase', 'migrations', migration), 'utf8'));
  }
  // The goalkeeper migration creates functions that grant execute to authenticated
  // themselves; ensure the pre-existing sequences stay usable by the role too.
  await admin.query('grant usage on all sequences in schema public to authenticated');

  // Seed accounts.
  await admin.query(`insert into public.usuarios (id, nombre, latitud, longitud) values ($1,'Admin',-34.60,-58.38)`, [ADMIN]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, latitud, longitud) values ($1,'Field', array['DEF'], -34.60,-58.38)`, [PLAYER]);
  await admin.query(`insert into public.usuarios (id, nombre, posiciones, latitud, longitud) values ($1,'Keeper', array['ARQ'], -34.60,-58.38)`, [KEEPER]);

  const adminAsUser = await connect(ADMIN);
  const playerAsUser = await connect(PLAYER); playerAsUser.__uid = PLAYER;
  const keeperAsUser = await connect(KEEPER); keeperAsUser.__uid = KEEPER;

  const mkMatch = async (falta, busca, opts = {}) => {
    const fechaExpr = opts.past ? `(now() - interval '1 day')::date` : `(now() + interval '3 days')::date`;
    return (await admin.query(
      `insert into public.partidos (nombre, fecha, hora, sede, sede_latitud, sede_longitud, modalidad, cupo_jugadores, creado_por, estado, falta_jugadores, busca_arquero)
       values ('P', ${fechaExpr}, '20:00', 'Cancha', -34.60, -58.38, 'F5', 10, $1, $4, $2, $3) returning id`,
      [ADMIN, falta, busca, opts.estado || 'active'],
    )).rows[0].id;
  };

  // Insert a request then drive it to a terminal status (as if rejected/ejected).
  const seedTerminalRequest = async (asUser, matchId, role, terminal = 'rejected') => {
    await insertOwnRequest(asUser, matchId, role);
    await admin.query(
      `update public.match_join_requests set status=$3 where match_id=$1 and user_id=$2`,
      [matchId, asUser.__uid, terminal],
    );
  };

  const ejectFromMatch = (matchId, userId) =>
    admin.query('delete from public.jugadores where partido_id=$1 and usuario_id=$2', [matchId, userId]);

  const reopen = async (asUser, matchId, role) =>
    (await asUser.query('select public.reopen_own_match_join_request($1,$2) as r', [matchId, role])).rows[0].r;

  // ─────────────────────────────────────────────────────────────────────────
  console.log('\n▶ Flujo real: solicitar → aprobar → expulsar → volver a solicitar (jugador)');
  const m1 = await mkMatch(true, false); // solo-jugadores

  // solicitar (RLS INSERT policy: own row)
  await insertOwnRequest(playerAsUser, m1, 'player');
  eq((await latestStatus(admin, m1, PLAYER)).status, 'pending', 'solicitar → pending');

  // aprobar (admin RPC, SECURITY DEFINER)
  const req1 = (await admin.query('select id from public.match_join_requests where match_id=$1 and user_id=$2', [m1, PLAYER])).rows[0].id;
  await adminAsUser.query('select public.approve_join_request($1)', [req1]);
  eq((await latestStatus(admin, m1, PLAYER)).status, 'approved', 'aprobar → approved');
  eq((await admin.query('select 1 from public.jugadores where partido_id=$1 and usuario_id=$2', [m1, PLAYER])).rowCount, 1, 'aprobado → jugador en el plantel');

  // expulsar (delete jugador → demote trigger)
  await ejectFromMatch(m1, PLAYER);
  eq((await latestStatus(admin, m1, PLAYER)).status, 'rejected', 'expulsar → solicitud demota a rejected');
  eq((await admin.query('select 1 from public.jugadores where partido_id=$1 and usuario_id=$2', [m1, PLAYER])).rowCount, 0, 'expulsar → jugador fuera del plantel');

  // ROOT CAUSE: the OLD client path (direct authenticated UPDATE) hits RLS and
  // updates ZERO rows — this is exactly what produced "No se pudo enviar la solicitud".
  const oldPath = await playerAsUser.query(
    `update public.match_join_requests set status='pending' where match_id=$1 and user_id=$2`,
    [m1, PLAYER],
  );
  eq(oldPath.rowCount, 0, 'BUG probado: UPDATE directo del solicitante afecta 0 filas (RLS admin-only)');
  eq((await latestStatus(admin, m1, PLAYER)).status, 'rejected', 'BUG probado: la solicitud sigue rejected tras el UPDATE directo');

  // FIX: the reopen RPC (SECURITY DEFINER) reopens the requester's own row.
  const reopen1 = (await playerAsUser.query('select public.reopen_own_match_join_request($1,$2) as r', [m1, 'player'])).rows[0].r;
  eq(reopen1.status, 'pending', 'volver a solicitar (jugador) → RPC devuelve pending');
  eq(reopen1.reopened, true, 'RPC marca reopened=true');
  eq((await latestStatus(admin, m1, PLAYER)).status, 'pending', 'volver a solicitar (jugador) → solicitud queda pending');

  // ─────────────────────────────────────────────────────────────────────────
  console.log('\n▶ Volver a solicitar como ARQUERO (partido busca arquero, usuario con ARQ)');
  const m2 = await mkMatch(true, true); // ambos toggles
  await insertOwnRequest(keeperAsUser, m2, 'goalkeeper');
  const req2 = (await admin.query('select id from public.match_join_requests where match_id=$1 and user_id=$2', [m2, KEEPER])).rows[0].id;
  await adminAsUser.query('select public.approve_join_request($1)', [req2]);
  eq((await admin.query('select is_goalkeeper from public.jugadores where partido_id=$1 and usuario_id=$2', [m2, KEEPER])).rows[0].is_goalkeeper, true, 'aprobado como arquero → is_goalkeeper=true');
  await ejectFromMatch(m2, KEEPER);
  eq((await latestStatus(admin, m2, KEEPER)).status, 'rejected', 'expulsar arquero → rejected');
  const reopen2 = (await keeperAsUser.query('select public.reopen_own_match_join_request($1,$2) as r', [m2, 'goalkeeper'])).rows[0].r;
  eq(reopen2.status, 'pending', 'volver a solicitar (arquero) → pending');
  const after2 = await latestStatus(admin, m2, KEEPER);
  eq(after2.status, 'pending', 'solicitud arquero queda pending');
  eq(after2.role, 'goalkeeper', 'rol reabierto = goalkeeper');

  // ─────────────────────────────────────────────────────────────────────────
  console.log('\n▶ Elegibilidad de rol validada en el BACKEND (estados controlados)');
  // Sin ARQ: el jugador de campo intenta reabrir como arquero → not_goalkeeper.
  const m3 = await mkMatch(true, true);
  await seedTerminalRequest(playerAsUser, m3, 'player');
  const noArq = await reopen(playerAsUser, m3, 'goalkeeper');
  eq(noArq.status, 'not_goalkeeper', 'sin ARQ → reabrir como arquero devuelve not_goalkeeper');
  eq((await latestStatus(admin, m3, PLAYER)).status, 'rejected', 'sin ARQ → la solicitud NO cambia (sigue rejected)');

  // Partido que NO busca arquero: reabrir como arquero → goalkeeper_not_searched.
  const m4 = await mkMatch(true, false); // solo-jugadores
  await seedTerminalRequest(keeperAsUser, m4, 'player');
  const noBusca = await reopen(keeperAsUser, m4, 'goalkeeper');
  eq(noBusca.status, 'goalkeeper_not_searched', 'partido no busca arquero → goalkeeper_not_searched');
  eq((await latestStatus(admin, m4, KEEPER)).status, 'rejected', 'no busca arquero → la solicitud NO cambia');
  // ...pero el MISMO usuario ARQ puede reabrir como jugador (el partido busca jugadores).
  eq((await reopen(keeperAsUser, m4, 'player')).status, 'pending', 'solo-jugadores → reabrir como jugador funciona');

  // Partido solo-arquero: reabrir como jugador → players_not_searched.
  const m4b = await mkMatch(false, true); // solo-arquero
  await seedTerminalRequest(keeperAsUser, m4b, 'player');
  const noPlayers = await reopen(keeperAsUser, m4b, 'player');
  eq(noPlayers.status, 'players_not_searched', 'partido no busca jugadores → players_not_searched');
  eq((await latestStatus(admin, m4b, KEEPER)).status, 'rejected', 'no busca jugadores → la solicitud NO cambia');

  // ─────────────────────────────────────────────────────────────────────────
  console.log('\n▶ Combinaciones de toggles + idempotencia + approved');
  // solo-arquero: arquero reabre OK (desde cancelled).
  const m5 = await mkMatch(false, true);
  await seedTerminalRequest(keeperAsUser, m5, 'goalkeeper', 'cancelled');
  eq((await reopen(keeperAsUser, m5, 'goalkeeper')).status, 'pending', 'solo-arquero → reabrir arquero (desde cancelled) funciona');

  // idempotencia: reabrir cuando ya está pending no rompe ni degrada.
  const reopenAgain = await reopen(keeperAsUser, m5, 'goalkeeper');
  eq(reopenAgain.status, 'pending', 'reabrir sobre pending → sigue pending (idempotente)');
  eq(reopenAgain.reopened, false, 'reabrir sobre pending → reopened=false');

  // reabrir un aprobado NO lo reabre ni degrada → already_approved.
  const m6 = await mkMatch(true, false);
  await insertOwnRequest(playerAsUser, m6, 'player');
  const req6 = (await admin.query('select id from public.match_join_requests where match_id=$1 and user_id=$2', [m6, PLAYER])).rows[0].id;
  await adminAsUser.query('select public.approve_join_request($1)', [req6]);
  eq((await reopen(playerAsUser, m6, 'player')).status, 'already_approved', 'reabrir sobre approved → already_approved (no reabre)');
  eq((await latestStatus(admin, m6, PLAYER)).status, 'approved', 'approved permanece approved');

  // ─────────────────────────────────────────────────────────────────────────
  console.log('\n▶ Partido cerrado / pasado / inexistente + usuario que ya participa');
  // Partido pasado (kickoff en el pasado) → match_past.
  const mPast = await mkMatch(true, false, { past: true });
  await seedTerminalRequest(playerAsUser, mPast, 'player');
  eq((await reopen(playerAsUser, mPast, 'player')).status, 'match_past', 'partido pasado → match_past');
  eq((await latestStatus(admin, mPast, PLAYER)).status, 'rejected', 'partido pasado → la solicitud NO cambia');

  // Partido no operativo (estado finalizado) → match_closed.
  const mClosed = await mkMatch(true, false, { estado: 'finalizado' });
  await seedTerminalRequest(playerAsUser, mClosed, 'player');
  eq((await reopen(playerAsUser, mClosed, 'player')).status, 'match_closed', 'partido finalizado → match_closed');

  // Partido inexistente → estado controlado (no hay solicitud que reabrir), sin error genérico.
  const bogus = await reopen(playerAsUser, 2147483000, 'player');
  eq(bogus.status, 'not_found', 'partido inexistente → estado controlado (not_found), sin excepción');

  // Usuario que YA participa (solicitud terminal inconsistente + jugador presente) → already_member.
  const mMember = await mkMatch(true, false);
  await insertOwnRequest(playerAsUser, mMember, 'player');
  const reqM = (await admin.query('select id from public.match_join_requests where match_id=$1 and user_id=$2', [mMember, PLAYER])).rows[0].id;
  await adminAsUser.query('select public.approve_join_request($1)', [reqM]); // agrega jugador
  await admin.query(`update public.match_join_requests set status='rejected' where id=$1`, [reqM]); // fuerza estado terminal, jugador SIGUE en el plantel
  eq((await reopen(playerAsUser, mMember, 'player')).status, 'already_member', 'usuario que ya participa → already_member');

  // ─────────────────────────────────────────────────────────────────────────
  console.log('\n▶ Concurrencia: dos reaperturas simultáneas NO divergen');
  const mConc = await mkMatch(true, false);
  await seedTerminalRequest(playerAsUser, mConc, 'player');
  const cA = await connect(PLAYER);
  const cB = await connect(PLAYER);
  await cA.query('begin');
  await cB.query('begin');
  const rConcA = (await cA.query('select public.reopen_own_match_join_request($1,$2) as r', [mConc, 'player'])).rows[0].r;
  // B queda bloqueado en el FOR UPDATE hasta que A commitea.
  const bPromise = cB.query('select public.reopen_own_match_join_request($1,$2) as r', [mConc, 'player']);
  await sleep(300);
  await cA.query('commit');
  const rConcB = (await bPromise).rows[0].r;
  await cB.query('commit');
  eq(rConcA.status, 'pending', 'concurrencia: A reabre → pending');
  eq(rConcA.reopened, true, 'concurrencia: A reopened=true');
  eq(rConcB.status, 'pending', 'concurrencia: B (serializado) ve pending');
  eq(rConcB.reopened, false, 'concurrencia: B idempotente (reopened=false)');
  eq((await admin.query('select count(*)::int c from public.match_join_requests where match_id=$1 and user_id=$2', [mConc, PLAYER])).rows[0].c, 1, 'concurrencia: sigue habiendo UNA sola solicitud (sin estados inconsistentes)');

  // ─────────────────────────────────────────────────────────────────────────
  console.log('\n▶ Sanidad RLS: el admin SÍ puede actualizar; el RPC exige sesión');
  // El admin puede mover su propio partido (la policy admin-only sigue vigente).
  const adminUpd = await adminAsUser.query(
    `update public.match_join_requests set status='rejected' where match_id=$1 and user_id=$2`,
    [m6, PLAYER],
  );
  eq(adminUpd.rowCount, 1, 'admin conserva su UPDATE (policy admin-only intacta)');
  // Sin sesión (anon) el RPC no está disponible.
  const anon = await connect();
  await anon.query('set role anon');
  const anonErr = await expectFailure(anon, 'select public.reopen_own_match_join_request($1,$2)', [m6, 'player']);
  ok(anonErr.length > 0, 'anon no puede ejecutar el RPC', anonErr);

  // ─────────────────────────────────────────────────────────────────────────
  for (const client of clients) {
    try { await client.end(); } catch (_e) { /* ignore */ }
  }
  await postgres.stop();

  console.log(`\n${failures === 0 ? '✅' : '❌'} rejoin-after-expulsion: ${checks - failures}/${checks} checks`);
  if (failures > 0) process.exit(1);
}

main().catch(async (error) => {
  console.error(error);
  try { await postgres.stop(); } catch (_e) { /* ignore */ }
  process.exit(1);
});
