-- Stub mínimo del entorno Supabase para correr las migraciones de gestación
-- automática contra un Postgres real (embedded-postgres). Reproduce solo lo
-- que esas migraciones y RPCs tocan: roles, auth.uid(), tablas núcleo
-- (usuarios/partidos/jugadores/notifications/notification_delivery_log) y el
-- helper partido_kickoff_at (ya existente en prod vía 20260320110000).

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin;
  end if;
end;
$$;

grant usage on schema public to anon, authenticated, service_role;
alter default privileges in schema public grant all on tables to authenticated, service_role;
alter default privileges in schema public grant all on sequences to authenticated, service_role;

create schema if not exists auth;

-- Como en Supabase: lee el sub del JWT; en el harness se setea por sesión con
-- set_config('request.jwt.claim.sub', ...).
create or replace function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;

create table public.usuarios (
  id uuid primary key,
  nombre text,
  avatar_url text,
  latitud double precision,
  longitud double precision,
  created_at timestamptz not null default now()
);

create table public.partidos (
  id bigint generated by default as identity primary key,
  match_ref uuid,
  codigo text unique,
  nombre text not null,
  fecha date,
  hora text,
  sede text,
  sede_place_id text,
  sede_direccion_normalizada text,
  sede_latitud double precision,
  sede_longitud double precision,
  modalidad text,
  cupo_jugadores integer,
  falta_jugadores boolean default false,
  player_invites_enabled boolean default false,
  tipo_partido text,
  creado_por uuid references public.usuarios(id),
  precio_cancha_por_persona numeric,
  estado text,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.jugadores (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  match_ref uuid,
  usuario_id uuid references public.usuarios(id),
  nombre text,
  avatar_url text,
  score numeric,
  is_goalkeeper boolean default false,
  created_at timestamptz not null default now()
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.usuarios(id),
  type text not null,
  title text,
  message text,
  data jsonb,
  read boolean default false,
  partido_id bigint,
  created_at timestamptz not null default now()
);

create table public.notification_delivery_log (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  partido_id bigint,
  notification_type text,
  payload_json jsonb,
  channel text,
  status text,
  correlation_id uuid,
  error_text text,
  created_at timestamptz not null default now()
);

grant all on all tables in schema public to authenticated, service_role;
grant all on all sequences in schema public to authenticated, service_role;

-- Copia fiel de public.partido_kickoff_at (20260320110000, aplicada en prod).
create or replace function public.partido_kickoff_at(
  p_fecha date,
  p_hora text
)
returns timestamptz
language plpgsql
immutable
as $$
declare
  v_time text := trim(coalesce(p_hora, ''));
  v_parts text[];
  v_hour int;
  v_minute int;
  v_second int := 0;
begin
  if p_fecha is null or v_time = '' then
    return null;
  end if;

  if v_time !~ '^\d{1,2}:\d{2}(:\d{2})?$' then
    return null;
  end if;

  v_parts := regexp_split_to_array(v_time, ':');
  v_hour := v_parts[1]::int;
  v_minute := v_parts[2]::int;
  if array_length(v_parts, 1) >= 3 then
    v_second := v_parts[3]::int;
  end if;

  if v_hour not between 0 and 23 or v_minute not between 0 and 59 or v_second not between 0 and 59 then
    return null;
  end if;

  return make_timestamptz(
    extract(year from p_fecha)::int,
    extract(month from p_fecha)::int,
    extract(day from p_fecha)::int,
    v_hour,
    v_minute,
    v_second,
    'America/Argentina/Buenos_Aires'
  );
end;
$$;
