#!/usr/bin/env python3
"""keychain-payments-test.py — macOS Keychain custody of the PAYMENTS TEST secrets generated by the tooling itself.

One namespace, fixed here and nowhere else (disjoint from every gateway, Core, Staging and non-production entry):
    arma2-torneos-payments-test   account torneos_payments_test   40-char URL-safe DB login password
                                  account internal-hmac-key       64 lowercase hex (32 bytes): the TEST app's internal HMAC key

Operations (status keywords only on stdout — never a value):
  check      <service> <account>   exit 0 = ABSENT, 10 = PRESENT, 3 = ambiguous (never guessed)
  generate   <service> <account>   the value is created INSIDE this process, stored through a pty, read back and compared
No `-U` (no silent overwrite), no delete, no rotation, no store of external values, no account outside the allowlist.
Why a pty: `security add-generic-password -w <value>` would put the value in argv (visible to ps).
Mercado Pago TEST credentials are NEVER stored here: they are typed by the operator into the session and live in its memory.
"""

import os
import pty
import re
import secrets
import select
import subprocess
import sys
import time

SECURITY = "/usr/bin/security"
TIMEOUT_SECONDS = 20
SERVICE = "arma2-torneos-payments-test"
ACCOUNTS = {
    "torneos_payments_test": (re.compile(r"^[A-Za-z0-9_-]{40}$"), lambda: secrets.token_urlsafe(30)),
    "internal-hmac-key": (re.compile(r"^[0-9a-f]{64}$"), lambda: secrets.token_hex(32)),
}
LABEL = "arma2 torneos PAYMENTS TEST (Mercado Pago TEST runtime) generated secret"


def _allowed(service: str, account: str) -> bool:
    return service == SERVICE and account in ACCOUNTS


def _present(service: str, account: str) -> int:
    proc = subprocess.run([SECURITY, "find-generic-password", "-s", service, "-a", account],
                          stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
    if proc.returncode == 0:
        return 10
    if proc.returncode == 44:  # errSecItemNotFound
        return 0
    return 3


def _store(service: str, account: str, value: str) -> int:
    argv = [SECURITY, "add-generic-password", "-s", service, "-a", account, "-D", LABEL, "-w"]
    pid, master = pty.fork()
    if pid == 0:
        os.execv(argv[0], argv)
        os._exit(127)
    deadline = time.time() + TIMEOUT_SECONDS
    payload = (value + "\n").encode("utf-8")
    writes_done = 0
    try:
        while time.time() < deadline:
            ready, _, _ = select.select([master], [], [], 0.5)
            if not ready:
                continue
            try:
                chunk = os.read(master, 4096)
            except OSError:
                break
            if not chunk:
                break
            # `security` prompts twice (value + retype); answer each prompt once, nothing else.
            if chunk.rstrip().endswith(b":") and writes_done < 2:
                os.write(master, payload)
                writes_done += 1
    finally:
        try:
            os.close(master)
        except OSError:
            pass
    _, status = os.waitpid(pid, 0)
    return os.waitstatus_to_exitcode(status) if writes_done == 2 else 5


def _read_back(service: str, account: str) -> str:
    proc = subprocess.run([SECURITY, "find-generic-password", "-s", service, "-a", account, "-w"],
                          stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, check=False)
    return proc.stdout.decode("utf-8").rstrip("\n") if proc.returncode == 0 else ""


def _put(service: str, account: str, value: str, keyword: str) -> int:
    if not ACCOUNTS[account][0].match(value):
        print("KEYCHAIN_VALUE_SHAPE_REFUSED", file=sys.stderr)
        return 4
    if _present(service, account) != 0:
        print("KEYCHAIN_ENTRY_PRESENT_REFUSE_OVERWRITE", file=sys.stderr)
        return 10
    rc = _store(service, account, value)
    if rc != 0:
        print(f"KEYCHAIN_STORE_FAILED status={rc}", file=sys.stderr)
        return 6
    if _read_back(service, account) != value:
        print("KEYCHAIN_READBACK_MISMATCH", file=sys.stderr)
        return 7
    print(f"{keyword} length={len(value)}")
    return 0


def main() -> int:
    if len(sys.argv) != 4 or sys.argv[1] not in ("check", "generate"):
        print("usage: keychain-payments-test.py check|generate <service> <account>", file=sys.stderr)
        return 2
    op, service, account = sys.argv[1], sys.argv[2], sys.argv[3]
    if not _allowed(service, account):
        print("KEYCHAIN_NAMESPACE_REFUSED", file=sys.stderr)
        return 2
    if op == "check":
        state = _present(service, account)
        print({0: "KEYCHAIN_ENTRY_ABSENT", 10: "KEYCHAIN_ENTRY_PRESENT"}.get(state, "KEYCHAIN_CHECK_AMBIGUOUS"))
        return state
    return _put(service, account, ACCOUNTS[account][1](), "KEYCHAIN_GENERATED")


if __name__ == "__main__":
    sys.exit(main())
