-- LOCAL ONLY. Exact canonical baseline delta; no legacy/default ACL changes.
REVOKE EXECUTE ON FUNCTION public.accept_tournament_team_invitation(text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.accept_tournament_team_invitation(text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.acknowledge_tournament_document(uuid, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.acknowledge_tournament_document(uuid, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.add_tournament_match_event(uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.add_tournament_match_event(uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.add_tournament_roster_player(uuid, uuid, uuid, uuid, uuid, text, text, smallint, text, text, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.add_tournament_roster_player(uuid, uuid, uuid, uuid, uuid, text, text, smallint, text, text, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.append_tournament_audit(uuid, text, text, uuid, uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.approve_tournament_team_entry(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.archive_tournament_announcement(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.archive_tournament_document(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.archive_tournament_fixture(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.archive_tournament_team_entry(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.archive_tournament_team_entry(uuid, uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.assert_tournament_fixture_scope(uuid, uuid, uuid, text, text[]) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.assign_tournament_media_photographer(uuid, uuid, boolean) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_schedule_tournament_matches(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.auto_schedule_tournament_matches(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.build_tournament_knockout(uuid, uuid, jsonb, boolean, boolean) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.build_tournament_round_robin(uuid, uuid, uuid, uuid[], boolean) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.bulk_schedule_tournament_matches(uuid, jsonb) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.can_access_tournament_communications(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.can_current_user_access_tournament_announcement(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.can_current_user_read_media_gallery(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.can_edit_tournament_team_entry(uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.can_manage_tournament_match_squad(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.can_read_tournament_fixture_scope(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.can_read_tournament_fixture_scope(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.can_read_tournament_match(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.can_read_tournament_match(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.can_read_tournament_match_operation(uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.can_read_tournament_participant_hub(uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.can_read_tournament_projection_scope(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.can_read_tournament_projection_scope(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.can_read_tournament_team_entry(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.can_read_tournament_team_entry(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.cancel_tournament_match(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.cancel_tournament_media_upload_session(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_tournament_media_upload_session(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.change_tournament_media_gallery_state(uuid, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.change_tournament_media_gallery_state(uuid, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.change_tournament_status(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.change_tournament_status(uuid, uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.complete_tournament_media_upload(uuid, text, text, bigint, integer, integer, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.create_manual_fixture_version(uuid, uuid, uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_manual_fixture_version(uuid, uuid, uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_announcement_draft(uuid, uuid, uuid, text, text, text, text, text, text, timestamp with time zone, uuid, text, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_announcement_draft(uuid, uuid, uuid, text, text, text, text, text, text, timestamp with time zone, uuid, text, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_court(uuid, uuid, text, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_court(uuid, uuid, text, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_disciplinary_override(uuid, text, integer, text, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_disciplinary_override(uuid, text, integer, text, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_document(uuid, uuid, uuid, text, text, text, text, text, timestamp with time zone, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_document(uuid, uuid, uuid, text, text, text, text, text, timestamp with time zone, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_document_version(uuid, text, text, timestamp with time zone, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_match_correction(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_match_correction(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_media_gallery(uuid, uuid, uuid, uuid, uuid, text, text, text, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_media_gallery(uuid, uuid, uuid, uuid, uuid, text, text, text, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_organization(text, text, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_organization(text, text, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_points_adjustment(uuid, uuid, uuid, uuid, uuid, integer, text, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_points_adjustment(uuid, uuid, uuid, uuid, uuid, integer, text, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_provisional_player(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_provisional_player(uuid, uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_season(uuid, text, text, date, date, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_season(uuid, text, text, date, date, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_team_entry(uuid, uuid, uuid, uuid, text, text, text, text, text, uuid, text, text, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_team_entry(uuid, uuid, uuid, uuid, text, text, text, text, text, uuid, text, text, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_venue(uuid, text, text, text, double precision, double precision, text, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_venue(uuid, text, text, text, double precision, double precision, text, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.create_tournament_with_defaults(uuid, uuid, text, text, text, text, text, text, date, date, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_tournament_with_defaults(uuid, uuid, text, text, text, text, text, text, date, date, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.current_user_has_media_team_relation(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.execute_tournament_group_draw(uuid, uuid, uuid, integer, text, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.execute_tournament_group_draw(uuid, uuid, uuid, integer, text, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.freeze_tournament_participants(uuid, uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.freeze_tournament_participants(uuid, uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_tournament_fixture(uuid, uuid, uuid, text, jsonb, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.generate_tournament_fixture(uuid, uuid, uuid, text, jsonb, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_managed_tournament_matches() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_managed_tournament_matches() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_match_squad_context(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_match_squad_context(uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_my_current_tournament_roster_players() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.get_my_managed_match_squad_context(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_managed_match_squad_context(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_my_tournament_memberships(integer, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_tournament_memberships(integer, integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_my_tournament_notification_preferences(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_tournament_notification_preferences(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_player_tournament_matches() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_player_tournament_matches() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_player_tournament_statistics(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_player_tournament_statistics(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_player_tournament_suspensions(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_player_tournament_suspensions(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_published_tournament_documents(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_documents(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_documents(uuid, uuid) TO anon,authenticated,service_role;
REVOKE EXECUTE ON FUNCTION public.get_published_tournament_matches(uuid, uuid, text, uuid, integer, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_matches(uuid, uuid, text, uuid, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_matches(uuid, uuid, text, uuid, integer, integer) TO anon,authenticated,service_role;
REVOKE EXECUTE ON FUNCTION public.get_published_tournament_media(uuid, uuid, uuid, integer, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_media(uuid, uuid, uuid, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_media(uuid, uuid, uuid, integer, integer) TO anon,authenticated,service_role;
REVOKE EXECUTE ON FUNCTION public.get_published_tournament_standings(uuid, uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_standings(uuid, uuid, uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_standings(uuid, uuid, uuid, uuid) TO anon,authenticated,service_role;
REVOKE EXECUTE ON FUNCTION public.get_published_tournament_statistics(uuid, uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_statistics(uuid, uuid, uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_statistics(uuid, uuid, uuid, uuid) TO anon,authenticated,service_role;
REVOKE EXECUTE ON FUNCTION public.get_published_tournament_teams(uuid, uuid, integer, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_teams(uuid, uuid, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_published_tournament_teams(uuid, uuid, integer, integer) TO anon,authenticated,service_role;
REVOKE EXECUTE ON FUNCTION public.get_team_registration_context(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_team_registration_context(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_announcement(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_announcement(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_announcement(uuid) TO anon,authenticated,service_role;
REVOKE EXECUTE ON FUNCTION public.get_tournament_communications_admin_context(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_communications_admin_context(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_communications_inbox(uuid, text, integer, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_communications_inbox(uuid, text, integer, integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_competition_context(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_competition_context(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_fixture_context(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_fixture_context(uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_match_operation_context(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_match_operation_context(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_match_operations_context(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_match_operations_context(uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_media_admin_context(uuid, uuid, text, integer, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_media_admin_context(uuid, uuid, text, integer, integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_participant_hub(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_participant_hub(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_participant_hub(uuid, uuid) TO anon,authenticated,service_role;
REVOKE EXECUTE ON FUNCTION public.get_tournament_participant_match(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_participant_match(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_participant_match(uuid) TO anon,authenticated,service_role;
REVOKE EXECUTE ON FUNCTION public.get_tournament_schedule_context(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_schedule_context(uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_standings_context(uuid, uuid, uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_standings_context(uuid, uuid, uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_statistics_context(uuid, uuid, uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_statistics_context(uuid, uuid, uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_teams_context(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_teams_context(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_tournament_workspace_context() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_workspace_context() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_tournament_media_report(uuid, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.handle_tournament_media_report(uuid, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.has_tournament_communications_capability(uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.has_tournament_media_assignment(uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.has_tournament_media_capability(uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.has_tournament_organization_capability(uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.has_tournament_organization_capability(uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.insert_tournament_match_source(uuid, text, jsonb) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.invite_tournament_team_manager(uuid, uuid, text, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.invite_tournament_team_manager(uuid, uuid, text, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.is_tournament_organization_member(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.is_tournament_organization_member(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.is_tournament_organization_slug_available(text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.is_tournament_organization_slug_available(text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.is_tournament_team_manager(uuid, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.is_tournament_team_manager(uuid, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.is_valid_tournament_format_settings(text, jsonb) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.lock_tournament_roster(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.lock_tournament_roster(uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.make_tournament_match_official(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.make_tournament_match_official(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.manage_tournament_media_consent(uuid, uuid, uuid, text, text, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_tournament_announcement_read(uuid, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.mark_tournament_announcement_read(uuid, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.mark_tournament_suspension_served(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.mark_tournament_suspension_served(uuid, uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.normalize_tournament_competition_slug(text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.normalize_tournament_organization_slug(text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.normalize_tournament_person_name(text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.open_tournament_match_operation(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.open_tournament_match_operation(uuid, uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.postpone_tournament_match(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.preview_tournament_announcement_audience(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.preview_tournament_announcement_audience(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_published_tournament_communication() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_published_tournament_document_version() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_tournament_competition_scope() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_tournament_match_child_history() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_tournament_match_operation_history() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_tournament_match_planning_transition() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_tournament_match_squad_players() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_tournament_organization_owner() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_tournament_registration_scope() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.publish_tournament_announcement(uuid, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.publish_tournament_announcement(uuid, integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.publish_tournament_document_version(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.publish_tournament_document_version(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.publish_tournament_fixture(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.publish_tournament_fixture(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.publish_tournament_media_gallery(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.publish_tournament_media_gallery(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.publish_tournament_standings_revision(uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.publish_tournament_standings_revision(uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.raise_tournament_match_error(text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.rank_tournament_standings(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.ready_tournament_match(uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.rebuild_tournament_discipline(uuid, uuid, uuid, uuid, uuid, text, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.rebuild_tournament_standings(uuid, uuid, uuid, uuid, uuid, text, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.rebuild_tournament_standings(uuid, uuid, uuid, uuid, uuid, text, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.record_manual_match_availability(uuid, uuid, uuid, text, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.record_manual_match_availability(uuid, uuid, uuid, text, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.reject_suspended_tournament_operation_player() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.reject_suspended_tournament_squad_player() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.reject_suspended_tournament_squad_submission() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.reject_tournament_audit_mutation() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.reject_tournament_match_child_delete() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.reject_tournament_projection_mutation() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.reject_tournament_team_entry(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.remove_tournament_roster_player(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.remove_tournament_roster_player(uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.reopen_tournament_participants(uuid, uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.reopen_tournament_participants(uuid, uuid, uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.reorder_tournament_media_item(uuid, uuid, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.reorder_tournament_media_item(uuid, uuid, integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.replace_tournament_announcement_audience(uuid, text, uuid, uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.replace_tournament_announcement_audience(uuid, text, uuid, uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.report_tournament_media_asset(uuid, text, text, boolean, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.report_tournament_media_asset(uuid, text, text, boolean, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.request_tournament_match_correction(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.request_tournament_match_correction(uuid, uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.request_tournament_media_upload_session(uuid, text, text, bigint, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.request_tournament_media_upload_session(uuid, text, text, bigint, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.reschedule_tournament_match(uuid, uuid, timestamp with time zone, uuid, uuid, integer, text, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.reschedule_tournament_match(uuid, uuid, timestamp with time zone, uuid, uuid, integer, text, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.resolve_tournament_announcement_recipients(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.resolve_tournament_qualification(uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_tournament_qualification(uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.respond_match_availability(uuid, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.respond_match_availability(uuid, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.restore_tournament_match_unscheduled(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.review_tournament_match_operation(uuid, uuid, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.review_tournament_match_operation(uuid, uuid, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.review_tournament_team_entry(uuid, uuid, text, text, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.review_tournament_team_entry(uuid, uuid, text, text, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.revoke_tournament_announcement(uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.revoke_tournament_points_adjustment(uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_tournament_points_adjustment(uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.revoke_tournament_team_invitation(uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.save_match_squad(uuid, uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.save_match_squad(uuid, uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.save_tournament_category(uuid, uuid, uuid, text, text, text, integer, smallint, smallint, text, text, smallint, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.save_tournament_category(uuid, uuid, uuid, text, text, text, integer, smallint, smallint, text, text, smallint, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.save_tournament_draw_pots(uuid, uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.save_tournament_draw_pots(uuid, uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.save_tournament_match_operation_draft(uuid, uuid, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.save_tournament_match_operation_draft(uuid, uuid, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.save_tournament_schedule_windows(uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.save_tournament_schedule_windows(uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.schedule_tournament_match(uuid, uuid, timestamp with time zone, uuid, uuid, integer, boolean, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.schedule_tournament_match(uuid, uuid, timestamp with time zone, uuid, uuid, integer, boolean, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.schedule_tournament_match_resumption(uuid, uuid, timestamp with time zone, uuid, uuid, text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.search_tournament_arma2_teams(uuid, uuid, text, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.search_tournament_arma2_teams(uuid, uuid, text, integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.search_tournament_players(uuid, uuid, text, integer, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.search_tournament_players(uuid, uuid, text, integer, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.set_active_tournament_context(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.set_active_tournament_context(uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.set_my_tournament_hub_category(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.set_my_tournament_hub_category(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.set_tournament_announcement_audience(uuid, text, uuid, uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.set_tournament_announcement_audience(uuid, text, uuid, uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.set_tournament_announcement_link(uuid, text, uuid, text, text, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.set_tournament_announcement_link(uuid, text, uuid, text, text, integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.set_tournament_match_outcome(uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.set_tournament_match_outcome(uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.set_tournament_match_score(uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.set_tournament_match_score(uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.set_tournament_media_cover(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.set_tournament_media_cover(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.set_tournament_workspace_preference(text, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.set_tournament_workspace_preference(text, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_match_squad(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.submit_match_squad(uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_tournament_match_operation(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.submit_tournament_match_operation(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.submit_tournament_team_entry(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.submit_tournament_team_entry(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.supersede_tournament_fixture(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.supersede_tournament_fixture(uuid, uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.tag_tournament_media_asset(uuid, text, uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.touch_tournament_communications_updated_at() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.touch_tournament_media_updated_at() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.touch_tournament_workspace_updated_at() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.tournament_communications_role_capabilities(text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.tournament_match_team_entries(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.tournament_media_asset_has_internal_consent(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.tournament_media_role_capabilities(text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.tournament_media_user_can_upload(uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.tournament_projection_source_fingerprint(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.tournament_registration_checklist(uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.tournament_role_capabilities(text) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.transition_tournament_media_asset(uuid, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.transition_tournament_media_asset(uuid, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_draft_fixture(uuid, uuid, text, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_draft_fixture(uuid, uuid, text, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_my_tournament_notification_preferences(uuid, boolean, boolean, boolean, boolean, boolean, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_my_tournament_notification_preferences(uuid, boolean, boolean, boolean, boolean, boolean, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_announcement_draft(uuid, text, text, text, text, text, timestamp with time zone) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_tournament_announcement_draft(uuid, text, text, text, text, text, timestamp with time zone) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_configuration(uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_tournament_configuration(uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_court(uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_tournament_court(uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_document_draft(uuid, text, text, timestamp with time zone) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_media_gallery(uuid, text, text, text, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_tournament_media_gallery(uuid, text, text, text, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_organization(uuid, text, text, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_tournament_organization(uuid, text, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_roster_player(uuid, uuid, uuid, smallint, text, text, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_tournament_roster_player(uuid, uuid, uuid, smallint, text, text, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_season(uuid, uuid, text, text, date, date, text, boolean, boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_tournament_season(uuid, uuid, text, text, date, date, text, boolean, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_team_entry(uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_tournament_team_entry(uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_tournament_venue(uuid, uuid, jsonb) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.update_tournament_venue(uuid, uuid, jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_fixture(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.validate_tournament_fixture(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_fixture_member_scope() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_group_scope() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_match_operation(uuid, uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.validate_tournament_match_operation(uuid, uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_match_operation_payload(uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_match_operation_source() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_match_player_scope() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_match_schedule(uuid, uuid, timestamp with time zone, uuid, uuid, integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.validate_tournament_match_schedule(uuid, uuid, timestamp with time zone, uuid, uuid, integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_match_scope() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_match_source_scope() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_match_squad_scope() FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_tournament_roster(uuid, uuid, uuid) FROM PUBLIC,anon,authenticated;
REVOKE EXECUTE ON FUNCTION public.void_tournament_match_event(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.void_tournament_match_event(uuid, uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.void_tournament_match_operation(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.void_tournament_match_operation(uuid, uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.withdraw_tournament_team_entry(uuid, uuid, text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.withdraw_tournament_team_entry(uuid, uuid, text) TO authenticated;
GRANT SELECT ON TABLE public."tournament_announcement_audiences" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_announcement_audiences" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_announcement_audiences" FROM anon;
ALTER TABLE public."tournament_announcement_audiences" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_announcement_deliveries" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_announcement_deliveries" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_announcement_deliveries" FROM anon;
ALTER TABLE public."tournament_announcement_deliveries" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_announcement_links" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_announcement_links" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_announcement_links" FROM anon;
ALTER TABLE public."tournament_announcement_links" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_announcements" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_announcements" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_announcements" FROM anon;
ALTER TABLE public."tournament_announcements" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_audit_log" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_audit_log" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_audit_log" FROM anon;
ALTER TABLE public."tournament_audit_log" ENABLE ROW LEVEL SECURITY;
GRANT USAGE,SELECT ON SEQUENCE public."tournament_audit_log_id_seq" TO authenticated,service_role;
REVOKE USAGE,UPDATE ON SEQUENCE public."tournament_audit_log_id_seq" FROM anon;
GRANT SELECT ON TABLE public."tournament_categories" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_categories" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_categories" FROM anon;
ALTER TABLE public."tournament_categories" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_competition_formats" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_competition_formats" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_competition_formats" FROM anon;
ALTER TABLE public."tournament_competition_formats" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_competition_participants" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_competition_participants" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_competition_participants" FROM anon;
ALTER TABLE public."tournament_competition_participants" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_courts" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_courts" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_courts" FROM anon;
ALTER TABLE public."tournament_courts" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_disciplinary_overrides" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_disciplinary_overrides" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_disciplinary_overrides" FROM anon;
ALTER TABLE public."tournament_disciplinary_overrides" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_discipline_ledgers" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_discipline_ledgers" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_discipline_ledgers" FROM anon;
ALTER TABLE public."tournament_discipline_ledgers" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_discipline_rules" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_discipline_rules" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_discipline_rules" FROM anon;
ALTER TABLE public."tournament_discipline_rules" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_document_acknowledgements" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_document_acknowledgements" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_document_acknowledgements" FROM anon;
ALTER TABLE public."tournament_document_acknowledgements" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_document_versions" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_document_versions" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_document_versions" FROM anon;
ALTER TABLE public."tournament_document_versions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_documents" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_documents" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_documents" FROM anon;
ALTER TABLE public."tournament_documents" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_draw_pot_members" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_draw_pot_members" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_draw_pot_members" FROM anon;
ALTER TABLE public."tournament_draw_pot_members" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_draw_pots" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_draw_pots" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_draw_pots" FROM anon;
ALTER TABLE public."tournament_draw_pots" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_fixture_versions" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_fixture_versions" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_fixture_versions" FROM anon;
ALTER TABLE public."tournament_fixture_versions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_group_members" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_group_members" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_group_members" FROM anon;
ALTER TABLE public."tournament_group_members" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_groups" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_groups" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_groups" FROM anon;
ALTER TABLE public."tournament_groups" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_availability_responses" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_availability_responses" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_availability_responses" FROM anon;
ALTER TABLE public."tournament_match_availability_responses" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_events" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_events" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_events" FROM anon;
ALTER TABLE public."tournament_match_events" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_operation_players" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_operation_players" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_operation_players" FROM anon;
ALTER TABLE public."tournament_match_operation_players" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_operations" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_operations" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_operations" FROM anon;
ALTER TABLE public."tournament_match_operations" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_outcomes" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_outcomes" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_outcomes" FROM anon;
ALTER TABLE public."tournament_match_outcomes" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_reschedules" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_reschedules" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_reschedules" FROM anon;
ALTER TABLE public."tournament_match_reschedules" ENABLE ROW LEVEL SECURITY;
GRANT USAGE,SELECT ON SEQUENCE public."tournament_match_reschedules_id_seq" TO authenticated,service_role;
REVOKE USAGE,UPDATE ON SEQUENCE public."tournament_match_reschedules_id_seq" FROM anon;
GRANT SELECT ON TABLE public."tournament_match_resumptions" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_resumptions" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_resumptions" FROM anon;
ALTER TABLE public."tournament_match_resumptions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_reviews" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_reviews" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_reviews" FROM anon;
ALTER TABLE public."tournament_match_reviews" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_scores" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_scores" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_scores" FROM anon;
ALTER TABLE public."tournament_match_scores" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_sources" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_sources" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_sources" FROM anon;
ALTER TABLE public."tournament_match_sources" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_squad_players" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_squad_players" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_squad_players" FROM anon;
ALTER TABLE public."tournament_match_squad_players" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_match_squads" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_match_squads" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_match_squads" FROM anon;
ALTER TABLE public."tournament_match_squads" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_matches" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_matches" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_matches" FROM anon;
ALTER TABLE public."tournament_matches" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_media_assets" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_assets" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_assets" FROM anon;
ALTER TABLE public."tournament_media_assets" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_media_assignments" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_assignments" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_assignments" FROM anon;
ALTER TABLE public."tournament_media_assignments" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_media_consent_events" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_consent_events" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_consent_events" FROM anon;
ALTER TABLE public."tournament_media_consent_events" ENABLE ROW LEVEL SECURITY;
GRANT USAGE,SELECT ON SEQUENCE public."tournament_media_consent_events_id_seq" TO authenticated,service_role;
REVOKE USAGE,UPDATE ON SEQUENCE public."tournament_media_consent_events_id_seq" FROM anon;
GRANT SELECT ON TABLE public."tournament_media_consents" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_consents" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_consents" FROM anon;
ALTER TABLE public."tournament_media_consents" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_media_galleries" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_galleries" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_galleries" FROM anon;
ALTER TABLE public."tournament_media_galleries" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_media_gallery_items" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_gallery_items" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_gallery_items" FROM anon;
ALTER TABLE public."tournament_media_gallery_items" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_media_moderation_actions" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_moderation_actions" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_moderation_actions" FROM anon;
ALTER TABLE public."tournament_media_moderation_actions" ENABLE ROW LEVEL SECURITY;
GRANT USAGE,SELECT ON SEQUENCE public."tournament_media_moderation_actions_id_seq" TO authenticated,service_role;
REVOKE USAGE,UPDATE ON SEQUENCE public."tournament_media_moderation_actions_id_seq" FROM anon;
GRANT SELECT ON TABLE public."tournament_media_relations" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_relations" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_relations" FROM anon;
ALTER TABLE public."tournament_media_relations" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_media_reports" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_reports" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_reports" FROM anon;
ALTER TABLE public."tournament_media_reports" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_media_upload_sessions" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_upload_sessions" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_upload_sessions" FROM anon;
ALTER TABLE public."tournament_media_upload_sessions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_media_variants" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_media_variants" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_media_variants" FROM anon;
ALTER TABLE public."tournament_media_variants" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_notification_preferences" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_notification_preferences" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_notification_preferences" FROM anon;
ALTER TABLE public."tournament_notification_preferences" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_organization_members" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_organization_members" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_organization_members" FROM anon;
ALTER TABLE public."tournament_organization_members" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_organizations" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_organizations" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_organizations" FROM anon;
ALTER TABLE public."tournament_organizations" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_participant_hub_preferences" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_participant_hub_preferences" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_participant_hub_preferences" FROM anon;
ALTER TABLE public."tournament_participant_hub_preferences" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_participant_sets" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_participant_sets" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_participant_sets" FROM anon;
ALTER TABLE public."tournament_participant_sets" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_phases" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_phases" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_phases" FROM anon;
ALTER TABLE public."tournament_phases" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_player_statistics" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_player_statistics" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_player_statistics" FROM anon;
ALTER TABLE public."tournament_player_statistics" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_player_suspensions" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_player_suspensions" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_player_suspensions" FROM anon;
ALTER TABLE public."tournament_player_suspensions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_points_adjustments" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_points_adjustments" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_points_adjustments" FROM anon;
ALTER TABLE public."tournament_points_adjustments" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_projection_sources" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_projection_sources" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_projection_sources" FROM anon;
ALTER TABLE public."tournament_projection_sources" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_provisional_players" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_provisional_players" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_provisional_players" FROM anon;
ALTER TABLE public."tournament_provisional_players" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_qualification_resolutions" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_qualification_resolutions" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_qualification_resolutions" FROM anon;
ALTER TABLE public."tournament_qualification_resolutions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_qualification_slots" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_qualification_slots" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_qualification_slots" FROM anon;
ALTER TABLE public."tournament_qualification_slots" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_roster_players" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_roster_players" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_roster_players" FROM anon;
ALTER TABLE public."tournament_roster_players" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_roster_settings" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_roster_settings" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_roster_settings" FROM anon;
ALTER TABLE public."tournament_roster_settings" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_rosters" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_rosters" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_rosters" FROM anon;
ALTER TABLE public."tournament_rosters" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_rounds" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_rounds" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_rounds" FROM anon;
ALTER TABLE public."tournament_rounds" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_schedule_windows" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_schedule_windows" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_schedule_windows" FROM anon;
ALTER TABLE public."tournament_schedule_windows" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_scoring_rules" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_scoring_rules" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_scoring_rules" FROM anon;
ALTER TABLE public."tournament_scoring_rules" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_seasons" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_seasons" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_seasons" FROM anon;
ALTER TABLE public."tournament_seasons" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_sport_modalities" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_sport_modalities" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_sport_modalities" FROM anon;
ALTER TABLE public."tournament_sport_modalities" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_standings_revisions" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_standings_revisions" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_standings_revisions" FROM anon;
ALTER TABLE public."tournament_standings_revisions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_suspension_served_matches" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_suspension_served_matches" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_suspension_served_matches" FROM anon;
ALTER TABLE public."tournament_suspension_served_matches" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_team_entries" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_team_entries" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_team_entries" FROM anon;
ALTER TABLE public."tournament_team_entries" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_team_invitations" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_team_invitations" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_team_invitations" FROM anon;
ALTER TABLE public."tournament_team_invitations" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_team_managers" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_team_managers" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_team_managers" FROM anon;
ALTER TABLE public."tournament_team_managers" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_team_reviews" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_team_reviews" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_team_reviews" FROM anon;
ALTER TABLE public."tournament_team_reviews" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_team_standings" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_team_standings" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_team_standings" FROM anon;
ALTER TABLE public."tournament_team_standings" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_team_statistics" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_team_statistics" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_team_statistics" FROM anon;
ALTER TABLE public."tournament_team_statistics" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_tiebreak_rules" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_tiebreak_rules" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_tiebreak_rules" FROM anon;
ALTER TABLE public."tournament_tiebreak_rules" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournament_venues" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournament_venues" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournament_venues" FROM anon;
ALTER TABLE public."tournament_venues" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."tournaments" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."tournaments" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."tournaments" FROM anon;
ALTER TABLE public."tournaments" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."user_tournament_context_preferences" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."user_tournament_context_preferences" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."user_tournament_context_preferences" FROM anon;
ALTER TABLE public."user_tournament_context_preferences" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE public."user_workspace_preferences" TO anon,authenticated,service_role;
GRANT INSERT,UPDATE,DELETE ON TABLE public."user_workspace_preferences" TO authenticated,service_role;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public."user_workspace_preferences" FROM anon;
ALTER TABLE public."user_workspace_preferences" ENABLE ROW LEVEL SECURITY;
