// App-wide constants for magic numbers and configuration
export const TEAM_BALANCING = {
  MAX_SCORE_DIFFERENCE: 5,
  MAX_SHUFFLE_ATTEMPTS: 500,
  MAX_LOCKED_PLAYERS_PER_TEAM: 3,
  DEFAULT_PLAYER_SCORE: 5,
  PERFECT_MATCH_SCORE_DIFF: 0,
};

export const ANIMATION_DURATIONS = {
  CONFETTI_DISPLAY: 3000,
  TOAST_DISPLAY: 1700,
  PERFECT_MATCH_CELEBRATION: 3000,
  BUTTON_TRANSITION: 200,
  HOVER_TRANSITION: 150,
};

export const POSITION_COLORS = {
  ARQ: '#FDB022', // Mustard/Gold
  DEF: '#FF6B9D', // Pink
  MED: '#06C270', // Green
  DEL: '#FF3B3B', // Red
  DEFAULT: '#8178e5', // Purple default
};

export const UI_SIZES = {
  WHATSAPP_ICON_SIZE: 20,
  PLAYER_AVATAR_MOBILE: 24,
  PLAYER_AVATAR_DEFAULT: 28,
  PLAYER_AVATAR_DESKTOP: 40,
  LOCK_ICON_MOBILE: 14,
  LOCK_ICON_DEFAULT: 16,
  LOCK_ICON_DESKTOP: 18,
};

export const LOADING_STATES = {
  ADDING_PLAYER: 'AGREGANDO...',
  REMOVING_PLAYER: 'ELIMINANDO...',
  CLOSING_VOTING: 'CERRANDO VOTACIÓN...',
  CREATING_MATCH: 'CREANDO...',
  SAVING: 'GUARDANDO...',
  LOADING: 'CARGANDO...',
  PROCESSING: 'PROCESANDO...',
};

export const BREAKPOINTS = {
  MOBILE_MAX: 480,
  TABLET_MIN: 600,
  DESKTOP_MIN: 768,
  LARGE_DESKTOP_MIN: 1024,
};