-- Availability -> matches -> automatic match proposal MVP
-- The MVP deliberately creates proposals, not live matches: every matched player
-- must opt in before an administrator turns the proposal into a normal partido.

create table if not exists public.player_availability (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.usuarios(id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  formats text[] not null default array['F5']::text[],
  max_distance_km integer not null default 8,
  latitude double precision,
  longitude double precision,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint player_availability_time_check check (ends_at > starts_at),
  constraint player_availability_distance_check check (max_distance_km between 1 and 50),
  constraint player_availability_status_check check (status in ('active', 'matched', 'cancelled', 'expired')),
  constraint player_availability_formats_check check (
    cardinality(formats) > 0
    and formats <@ array['F5','F6','F7','F8','F9','F11']::text[]
  ),
  constraint player_availability_latitude_check check (latitude is null or latitude between -90 and 90),
  constraint player_availability_longitude_check check (longitude is null or longitude between -180 and 180)
);

create unique index if not exists player_availability_one_active_per_user
  on public.player_availability(user_id)
  where status = 'active';
create index if not exists player_availability_window_idx
  on public.player_availability(status, starts_at, ends_at);

create table if not exists public.auto_match_proposals (
  id bigint generated by default as identity primary key,
  format text not null,
  proposed_starts_at timestamptz not null,
  latitude double precision,
  longitude double precision,
  max_players integer not null,
  status text not null default 'collecting',
  created_by uuid references public.usuarios(id) on delete set null,
  partido_id bigint references public.partidos(id) on delete set null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint auto_match_proposals_format_check check (format in ('F5','F6','F7','F8','F9','F11')),
  constraint auto_match_proposals_status_check check (status in ('collecting','ready','created','cancelled','expired')),
  constraint auto_match_proposals_max_players_check check (max_players = (substring(format from 2)::integer * 2))
);

create table if not exists public.auto_match_proposal_members (
  proposal_id bigint not null references public.auto_match_proposals(id) on delete cascade,
  availability_id bigint not null references public.player_availability(id) on delete cascade,
  user_id uuid not null references public.usuarios(id) on delete cascade,
  response text not null default 'pending',
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (proposal_id, user_id),
  unique (proposal_id, availability_id),
  constraint auto_match_member_response_check check (response in ('pending','accepted','declined'))
);

alter table public.player_availability enable row level security;
alter table public.auto_match_proposals enable row level security;
alter table public.auto_match_proposal_members enable row level security;

-- Privacy: availabilities carry exact coordinates, so no cross-user SELECT.
-- Matching happens only through find_my_availability_matches (security
-- definer), which returns distance but never another player's coordinates.
drop policy if exists player_availability_manage_own on public.player_availability;
create policy player_availability_manage_own
  on public.player_availability for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists auto_match_proposals_select_members on public.auto_match_proposals;
create policy auto_match_proposals_select_members
  on public.auto_match_proposals for select to authenticated
  using (
    exists (
      select 1 from public.auto_match_proposal_members m
      where m.proposal_id = id and m.user_id = auth.uid()
    )
  );

-- Own rows only: a self-referencing policy on this table would recurse
-- (42P17). Widening visibility to co-members later requires a security
-- definer helper, not a subquery on the same table.
drop policy if exists auto_match_members_select_members on public.auto_match_proposal_members;
create policy auto_match_members_select_members
  on public.auto_match_proposal_members for select to authenticated
  using (user_id = auth.uid());

-- Responses go through respond_to_auto_match_proposal (security definer);
-- no direct UPDATE policy so members can't skip its state checks.

create or replace function public.upsert_my_availability(
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_formats text[],
  p_max_distance_km integer default 8,
  p_latitude double precision default null,
  p_longitude double precision default null
)
returns public.player_availability
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.player_availability;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if p_ends_at <= p_starts_at then raise exception 'invalid_time_window'; end if;
  if p_ends_at < p_starts_at + interval '60 minutes' then raise exception 'window_too_short'; end if;
  if p_starts_at < now() - interval '5 minutes' then raise exception 'availability_in_past'; end if;
  if p_ends_at > now() + interval '30 days' then raise exception 'window_too_far'; end if;
  if p_max_distance_km not between 1 and 50 then raise exception 'invalid_distance'; end if;
  if p_latitude is not null and p_latitude not between -90 and 90 then raise exception 'invalid_latitude'; end if;
  if p_longitude is not null and p_longitude not between -180 and 180 then raise exception 'invalid_longitude'; end if;
  if cardinality(p_formats) = 0 or not (p_formats <@ array['F5','F6','F7','F8','F9','F11']::text[]) then
    raise exception 'invalid_formats';
  end if;

  update public.player_availability
     set status = 'cancelled', updated_at = now()
   where user_id = auth.uid() and status = 'active';

  insert into public.player_availability (
    user_id, starts_at, ends_at, formats, max_distance_km, latitude, longitude
  ) values (
    auth.uid(), p_starts_at, p_ends_at, array(select distinct unnest(p_formats)),
    p_max_distance_km, p_latitude, p_longitude
  ) returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.cancel_my_availability()
returns void
language sql
security definer
set search_path = public
as $$
  update public.player_availability
     set status = 'cancelled', updated_at = now()
   where user_id = auth.uid() and status = 'active';
$$;

create or replace function public.find_my_availability_matches(p_limit integer default 30)
returns table (
  availability_id bigint,
  user_id uuid,
  nombre text,
  avatar_url text,
  starts_at timestamptz,
  ends_at timestamptz,
  shared_formats text[],
  distance_km double precision,
  overlap_minutes integer
)
language sql
stable
security definer
set search_path = public
as $$
  with mine as (
    select * from public.player_availability
    where user_id = auth.uid() and status = 'active' and ends_at > now()
    order by created_at desc limit 1
  )
  select
    other.id as availability_id,
    other.user_id as user_id,
    u.nombre as nombre,
    u.avatar_url as avatar_url,
    greatest(mine.starts_at, other.starts_at) as starts_at,
    least(mine.ends_at, other.ends_at) as ends_at,
    array(select unnest(mine.formats) intersect select unnest(other.formats)) as shared_formats,
    case
      when mine.latitude is null or mine.longitude is null or other.latitude is null or other.longitude is null then null
      else 6371 * 2 * asin(sqrt(
        power(sin(radians(other.latitude - mine.latitude) / 2), 2)
        + cos(radians(mine.latitude)) * cos(radians(other.latitude))
        * power(sin(radians(other.longitude - mine.longitude) / 2), 2)
      ))
    end as distance_km,
    floor(extract(epoch from (least(mine.ends_at, other.ends_at) - greatest(mine.starts_at, other.starts_at))) / 60)::integer as overlap_minutes
  from mine
  join public.player_availability other
    on other.status = 'active'
   and other.ends_at > now()
   and other.user_id <> mine.user_id
   and other.starts_at < mine.ends_at
   and other.ends_at > mine.starts_at
   and other.formats && mine.formats
  join public.usuarios u on u.id = other.user_id
  where
    greatest(mine.starts_at, other.starts_at) + interval '60 minutes' <= least(mine.ends_at, other.ends_at)
    and (
      mine.latitude is null or mine.longitude is null or other.latitude is null or other.longitude is null
      or (6371 * 2 * asin(sqrt(
        power(sin(radians(other.latitude - mine.latitude) / 2), 2)
        + cos(radians(mine.latitude)) * cos(radians(other.latitude))
        * power(sin(radians(other.longitude - mine.longitude) / 2), 2)
      ))) <= least(mine.max_distance_km, other.max_distance_km)
    )
  order by overlap_minutes desc, distance_km asc nulls last
  limit greatest(1, least(coalesce(p_limit, 30), 100));
$$;

revoke execute on function public.upsert_my_availability(timestamptz,timestamptz,text[],integer,double precision,double precision) from public, anon;
revoke execute on function public.cancel_my_availability() from public, anon;
revoke execute on function public.find_my_availability_matches(integer) from public, anon;

grant execute on function public.upsert_my_availability(timestamptz,timestamptz,text[],integer,double precision,double precision) to authenticated;
grant execute on function public.cancel_my_availability() to authenticated;
grant execute on function public.find_my_availability_matches(integer) to authenticated;
