begin;

-- A gestation carries a candidate occurrence, not a reservation. Schedule
-- ownership begins only when finalize_auto_match_proposal atomically creates a
-- real partido. Keep these legacy helpers as harmless compatibility shims for
-- older matcher functions that still call them.
create or replace function public.user_has_overlapping_auto_match(
  p_user_id uuid,
  p_starts_at timestamptz,
  p_exclude_proposal_id bigint default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select false;
$$;

create or replace function public.user_declined_auto_match_slot(
  p_user_id uuid,
  p_format text,
  p_starts_at timestamptz
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select false;
$$;

-- Backfill is scoped to a single proposal. The candidate occurrence is used
-- only to prove that the stored availability can join this cohort; neither a
-- real partido nor another gestation consumes that availability.
create or replace function public.backfill_auto_match_proposal_members(p_proposal_id bigint)
returns integer
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_proposal public.auto_match_proposals;
  v_candidate record;
  v_active integer;
  v_capacity integer;
  v_added integer := 0;
begin
  select * into v_proposal
  from public.auto_match_proposals
  where id = p_proposal_id
  for update;

  if v_proposal.id is null or v_proposal.status not in ('collecting', 'ready') then
    return 0;
  end if;

  v_capacity := public.auto_match_invitation_capacity(v_proposal.format);
  select count(*) into v_active
  from public.auto_match_proposal_members m
  where m.proposal_id = p_proposal_id
    and m.response not in ('declined', 'expired', 'waitlisted');

  for v_candidate in
    select a.id as availability_id, a.user_id, a.can_organize
    from public.player_availability a
    where public.auto_match_availability_is_eligible(a.id)
      and public.auto_match_availability_fits_proposal(a.id, p_proposal_id)
      and not exists (
        select 1
        from public.auto_match_proposal_members m
        where m.proposal_id = p_proposal_id and m.user_id = a.user_id
      )
    order by a.created_at, a.id
  loop
    exit when v_active >= v_capacity;

    insert into public.auto_match_proposal_members (
      proposal_id, availability_id, user_id, response, can_organize, invite_expires_at
    ) values (
      p_proposal_id, v_candidate.availability_id, v_candidate.user_id,
      'pending', v_candidate.can_organize,
      public.auto_match_invite_deadline(now(), v_proposal.proposed_starts_at)
    ) on conflict do nothing;

    if found then
      v_active := v_active + 1;
      v_added := v_added + 1;
      perform public.enqueue_auto_match_notification(
        p_proposal_id,
        'auto_match_gestating',
        'Se libero un lugar',
        format('Se libero un lugar en un %s compatible con tus horarios. Entra para confirmar si te sumas.', v_proposal.format),
        array[v_candidate.user_id]::uuid[],
        format('joined:%s', v_candidate.user_id),
        null
      );
    end if;
  end loop;

  return v_added;
end;
$$;

drop trigger if exists enforce_auto_match_member_eligibility_trigger
  on public.auto_match_proposal_members;

-- Restore only automatic degradations. Explicit exits, real invite expiry,
-- missing accounts and proven geographic incompatibility remain terminal.
create or replace function public.reconcile_auto_match_proposal_members(
  p_proposal_id bigint
)
returns table (
  restored_count integer,
  removed_count integer,
  backfilled_count integer
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_proposal public.auto_match_proposals;
  v_member record;
  v_reason text;
begin
  restored_count := 0;
  removed_count := 0;
  backfilled_count := 0;

  select * into v_proposal
  from public.auto_match_proposals
  where id = p_proposal_id
  for update;

  if v_proposal.id is null
     or v_proposal.status not in ('collecting', 'ready')
     or v_proposal.expires_at <= now() then
    return next;
    return;
  end if;

  create temporary table if not exists tmp_auto_match_reconcile_keep (
    user_id uuid primary key
  ) on commit drop;
  truncate tmp_auto_match_reconcile_keep;

  update public.auto_match_proposal_members m
  set response = 'expired',
      response_reason = 'account_ineligible',
      responded_at = now(),
      confirmed_at = null,
      invite_expires_at = null
  where m.proposal_id = p_proposal_id
    and m.response in ('pending', 'accepted')
    and not public.auto_match_account_is_eligible(m.user_id);
  get diagnostics removed_count = row_count;

  -- A schedule-conflict decline was generated by the old cross-gestation
  -- response path. It is not a voluntary exit, so put it back in this room.
  update public.auto_match_proposal_members m
  set response = 'pending',
      response_reason = null,
      responded_at = null,
      invite_expires_at = public.auto_match_invite_deadline(now(), v_proposal.proposed_starts_at)
  where m.proposal_id = p_proposal_id
    and m.response = 'declined'
    and m.response_reason = 'schedule_conflict'
    and m.confirmed_at is null
    and public.auto_match_member_snapshot_is_valid_for_proposal(p_proposal_id, m.user_id)
    and not exists (
      select 1
      from public.auto_match_proposal_members core
      where core.proposal_id = p_proposal_id
        and core.response = 'accepted'
        and core.user_id <> m.user_id
        and not public.auto_match_member_snapshots_are_compatible(
          p_proposal_id, m.user_id, core.user_id
        )
    );
  get diagnostics restored_count = row_count;

  for v_member in
    select m.user_id
    from public.auto_match_proposal_members m
    where m.proposal_id = p_proposal_id
      and m.response = 'expired'
      and m.confirmed_at is not null
      and coalesce(m.response_reason, '') in ('', 'schedule_conflict', 'availability_ineligible')
      and public.auto_match_member_snapshot_is_valid_for_proposal(p_proposal_id, m.user_id)
      and not exists (
        select 1
        from public.auto_match_proposal_members core
        where core.proposal_id = p_proposal_id
          and core.response = 'accepted'
          and core.user_id <> m.user_id
          and not public.auto_match_member_snapshots_are_compatible(
            p_proposal_id, m.user_id, core.user_id
          )
      )
    order by m.confirmed_at, m.created_at, m.user_id
  loop
    update public.auto_match_proposal_members
    set response = 'accepted',
        response_reason = null,
        responded_at = coalesce(responded_at, confirmed_at),
        invite_expires_at = null
    where proposal_id = p_proposal_id
      and user_id = v_member.user_id
      and response = 'expired'
      and confirmed_at is not null
      and coalesce(response_reason, '') in ('', 'schedule_conflict', 'availability_ineligible');
    if found then restored_count := restored_count + 1; end if;
  end loop;

  insert into tmp_auto_match_reconcile_keep(user_id)
  select m.user_id
  from public.auto_match_proposal_members m
  where m.proposal_id = p_proposal_id and m.response = 'accepted'
  on conflict do nothing;

  for v_member in
    select m.user_id
    from public.auto_match_proposal_members m
    where m.proposal_id = p_proposal_id and m.response = 'pending'
    order by m.created_at, m.user_id
  loop
    v_reason := null;

    if not public.auto_match_member_snapshot_is_valid_for_proposal(
      p_proposal_id, v_member.user_id
    ) then
      v_reason := 'availability_ineligible';
    elsif exists (
      select 1
      from tmp_auto_match_reconcile_keep kept
      where not public.auto_match_member_snapshots_are_compatible(
        p_proposal_id, v_member.user_id, kept.user_id
      )
    ) then
      v_reason := 'geographic_incompatibility';
    end if;

    if v_reason is null then
      insert into tmp_auto_match_reconcile_keep(user_id)
      values (v_member.user_id)
      on conflict do nothing;
    else
      update public.auto_match_proposal_members
      set response = 'expired',
          response_reason = v_reason,
          responded_at = now(),
          confirmed_at = null,
          invite_expires_at = null
      where proposal_id = p_proposal_id
        and user_id = v_member.user_id
        and response = 'pending';
      if found then removed_count := removed_count + 1; end if;
    end if;
  end loop;

  backfilled_count := public.backfill_auto_match_proposal_members(p_proposal_id);
  return next;
end;
$$;

create or replace function public.enforce_auto_match_member_eligibility()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if new.response not in ('pending', 'accepted') then return new; end if;

  if tg_op = 'INSERT' then
    if new.availability_id is not null
       and public.auto_match_availability_is_eligible(new.availability_id)
       and public.auto_match_availability_fits_proposal(new.availability_id, new.proposal_id) then
      return new;
    end if;
    return null;
  end if;

  if old.response = 'expired'
     and new.response = 'accepted'
     and old.confirmed_at is not null
     and coalesce(old.response_reason, '') in ('', 'schedule_conflict', 'availability_ineligible')
     and public.auto_match_member_snapshot_is_valid_for_proposal(
       new.proposal_id, new.user_id
     )
     and not exists (
       select 1
       from public.auto_match_proposal_members core
       where core.proposal_id = new.proposal_id
         and core.response = 'accepted'
         and core.user_id <> new.user_id
         and not public.auto_match_member_snapshots_are_compatible(
           new.proposal_id, new.user_id, core.user_id
         )
     ) then
    return new;
  end if;

  if public.auto_match_member_snapshot_fits_proposal(new.proposal_id, new.user_id) then
    return new;
  end if;

  if new.response = 'accepted' and old.response is distinct from 'accepted' then
    raise exception 'auto_match_location_or_account_ineligible';
  end if;
  return null;
end;
$$;

create trigger enforce_auto_match_member_eligibility_trigger
before insert or update of response, availability_id
on public.auto_match_proposal_members
for each row execute function public.enforce_auto_match_member_eligibility();

-- A response mutates only the addressed gestation. The proposal row is enough
-- to serialize its capacity; there are deliberately no schedule locks or
-- cross-proposal writes here.
create or replace function public.respond_to_auto_match_proposal(
  p_proposal_id bigint,
  p_response text,
  p_can_organize boolean default false
)
returns public.auto_match_proposal_members
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_proposal public.auto_match_proposals;
  v_member public.auto_match_proposal_members;
  v_accepted integer;
  v_pending integer;
  v_required integer;
  v_geo_incompatible boolean;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if p_response not in ('accepted','declined') then raise exception 'invalid_response'; end if;

  select * into v_proposal
  from public.auto_match_proposals
  where id = p_proposal_id
  for update;
  if v_proposal.id is null then raise exception 'proposal_not_found'; end if;

  select * into v_member
  from public.auto_match_proposal_members
  where proposal_id = p_proposal_id and user_id = auth.uid()
  for update;
  if v_member.proposal_id is null then raise exception 'proposal_member_not_found'; end if;

  if p_response = 'accepted' and v_member.response = 'accepted' then
    if coalesce(p_can_organize, false) and not v_member.can_organize
       and v_proposal.status in ('collecting', 'ready') then
      update public.auto_match_proposal_members
      set can_organize = true
      where proposal_id = p_proposal_id and user_id = auth.uid()
      returning * into v_member;
    end if;
    return v_member;
  end if;
  if p_response = 'declined' and v_member.response = 'declined' then return v_member; end if;

  if v_member.response = 'expired'
     and v_member.response_reason = 'geographic_incompatibility' then
    return v_member;
  end if;
  if v_member.response = 'declined' then raise exception 'proposal_member_declined'; end if;
  if v_member.response = 'expired' then raise exception 'proposal_member_expired'; end if;
  if v_member.response = 'waitlisted' then raise exception 'proposal_member_waitlisted'; end if;
  if v_proposal.status not in ('collecting', 'ready') or v_proposal.expires_at <= now() then
    raise exception 'proposal_not_open';
  end if;
  if v_member.invite_expires_at is not null and v_member.invite_expires_at <= now() then
    raise exception 'proposal_member_expired';
  end if;

  v_required := v_proposal.max_players;

  if p_response = 'accepted' then
    select exists (
      select 1
      from public.auto_match_proposal_members other
      where other.proposal_id = p_proposal_id
        and other.user_id <> auth.uid()
        and other.response not in ('declined', 'expired', 'waitlisted')
        and not public.auto_match_member_snapshots_are_compatible(
          p_proposal_id, auth.uid(), other.user_id
        )
    ) into v_geo_incompatible;

    if v_geo_incompatible
       or not public.auto_match_member_snapshot_is_valid_for_proposal(
         p_proposal_id, auth.uid()
       ) then
      update public.auto_match_proposal_members
      set response = 'expired',
          response_reason = case
            when v_geo_incompatible then 'geographic_incompatibility'
            when not public.auto_match_account_is_eligible(auth.uid()) then 'account_ineligible'
            else 'availability_ineligible'
          end,
          responded_at = now(),
          confirmed_at = null,
          invite_expires_at = null
      where proposal_id = p_proposal_id and user_id = auth.uid()
      returning * into v_member;
      perform public.backfill_auto_match_proposal_members(p_proposal_id);
      return v_member;
    end if;

    select count(*) into v_accepted
    from public.auto_match_proposal_members
    where proposal_id = p_proposal_id and response = 'accepted';
    if v_accepted >= public.auto_match_invitation_capacity(v_proposal.format) then
      raise exception 'proposal_full';
    end if;

    update public.auto_match_proposal_members
    set response = 'accepted',
        response_reason = null,
        can_organize = can_organize or coalesce(p_can_organize, false),
        confirmed_at = coalesce(confirmed_at, now()),
        responded_at = coalesce(responded_at, now())
    where proposal_id = p_proposal_id and user_id = auth.uid()
    returning * into v_member;

    select
      count(*) filter (where response = 'accepted'),
      count(*) filter (where response = 'pending')
    into v_accepted, v_pending
    from public.auto_match_proposal_members
    where proposal_id = p_proposal_id;

    if v_accepted >= v_required then
      if v_proposal.status = 'collecting' then
        update public.auto_match_proposals
        set status = 'ready', updated_at = now()
        where id = p_proposal_id and status = 'collecting';
      end if;
      perform public.resolve_auto_match_full_cupo(p_proposal_id);
    elsif v_required - v_accepted <= 2 and v_pending > 0 then
      perform public.enqueue_auto_match_notification(
        p_proposal_id,
        'auto_match_almost_full',
        'Faltan muy pocos',
        format('Faltan %s confirmaciones para completar el partido.', v_required - v_accepted),
        null,
        format('almost_full:%s', v_required - v_accepted),
        null
      );
    end if;
    return v_member;
  end if;

  update public.auto_match_proposal_members
  set response = 'declined',
      response_reason = 'user_declined',
      responded_at = now(),
      confirmed_at = null
  where proposal_id = p_proposal_id and user_id = auth.uid()
  returning * into v_member;

  perform public.process_auto_match_member_exit(p_proposal_id);
  return v_member;
end;
$$;

-- Materialization is the only schedule-ownership boundary. Roster users are
-- locked in UUID order, possible 15-minute starts are derived from immutable
-- snapshots, and 120-minute half-open ranges are compared only with real
-- partidos. The chosen time and partido are persisted in the same transaction.
create or replace function public.finalize_auto_match_proposal(
  p_proposal_id bigint,
  p_nombre text,
  p_fecha date default null,
  p_hora text default null,
  p_tipo_partido text default 'Masculino',
  p_precio numeric default null,
  p_sede text default null,
  p_sede_place_id text default null,
  p_sede_direccion text default null,
  p_sede_latitud double precision default null,
  p_sede_longitud double precision default null
)
returns public.auto_match_proposals
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tz constant text := 'America/Argentina/Buenos_Aires';
  v_proposal public.auto_match_proposals;
  v_local timestamp;
  v_requested_start timestamptz;
  v_final_start timestamptz;
  v_fecha date;
  v_hora text;
  v_nombre text;
  v_codigo text;
  v_partido_id bigint;
  v_match_ref uuid;
  v_attempt integer;
  v_final_cap integer;
  v_roster_count integer;
  v_waitlist uuid[];
  v_pending uuid[];
  v_lock record;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;

  select * into v_proposal
  from public.auto_match_proposals
  where id = p_proposal_id
  for update;

  if v_proposal.id is null then raise exception 'proposal_not_found'; end if;
  if v_proposal.partido_id is not null then return v_proposal; end if;
  if v_proposal.organizer_id is null or v_proposal.organizer_id <> auth.uid() then
    raise exception 'not_the_organizer';
  end if;
  if v_proposal.status <> 'ready' then raise exception 'proposal_not_ready'; end if;
  if v_proposal.expires_at <= now() then raise exception 'proposal_not_open'; end if;

  v_nombre := nullif(trim(coalesce(p_nombre, '')), '');
  if v_nombre is null then raise exception 'match_name_required'; end if;
  if p_precio is not null and p_precio < 0 then raise exception 'invalid_price'; end if;

  v_local := v_proposal.proposed_starts_at at time zone v_tz;
  v_fecha := coalesce(p_fecha, v_local::date);
  v_hora := coalesce(nullif(trim(coalesce(p_hora, '')), ''), to_char(v_local, 'HH24:MI'));
  if v_hora !~ '^([01]\d|2[0-3]):[0-5]\d$' then raise exception 'invalid_time'; end if;

  v_requested_start := (v_fecha + v_hora::time) at time zone v_tz;
  if abs(extract(epoch from (v_requested_start - v_proposal.proposed_starts_at))) > 7200 then
    raise exception 'time_out_of_range';
  end if;

  v_final_cap := public.auto_match_final_roster_capacity(v_proposal.format);
  create temporary table if not exists tmp_auto_match_final_roster (
    user_id uuid primary key,
    seat integer not null
  ) on commit drop;
  truncate tmp_auto_match_final_roster;

  insert into tmp_auto_match_final_roster(user_id, seat)
  select ranked.user_id, ranked.seat
  from (
    select m.user_id,
      row_number() over (order by m.confirmed_at asc nulls last, m.user_id)::integer as seat
    from public.auto_match_proposal_members m
    where m.proposal_id = p_proposal_id and m.response = 'accepted'
  ) ranked
  where ranked.seat <= v_final_cap;

  if (select count(*) from tmp_auto_match_final_roster) < v_proposal.max_players then
    raise exception 'proposal_not_ready';
  end if;

  -- All auto-match materializations use these locks. Two rooms sharing players
  -- therefore serialize before either one chooses a final time.
  for v_lock in
    select r.user_id from tmp_auto_match_final_roster r order by r.user_id
  loop
    perform pg_advisory_xact_lock(
      hashtextextended('auto_match_materialize_user:' || v_lock.user_id::text, 0)
    );
    perform 1 from public.usuarios u where u.id = v_lock.user_id for update;
  end loop;

  create temporary table if not exists tmp_auto_match_final_candidates (
    starts_at timestamptz primary key,
    requested boolean not null
  ) on commit drop;
  truncate tmp_auto_match_final_candidates;

  insert into tmp_auto_match_final_candidates values (v_requested_start, true)
  on conflict (starts_at) do update set requested = true;

  insert into tmp_auto_match_final_candidates(starts_at, requested)
  select candidate, false
  from generate_series(
    v_proposal.proposed_starts_at - interval '120 minutes',
    v_proposal.proposed_starts_at + interval '120 minutes',
    interval '15 minutes'
  ) candidate
  where (candidate at time zone v_tz)::date = v_fecha
  on conflict (starts_at) do nothing;

  select c.starts_at into v_final_start
  from tmp_auto_match_final_candidates c
  where not exists (
      select 1
      from tmp_auto_match_final_roster r
      join public.auto_match_proposal_members m
        on m.proposal_id = p_proposal_id and m.user_id = r.user_id
      where not (
        extract(isodow from (c.starts_at at time zone m.snapshot_timezone))::smallint
          = any(m.snapshot_days_of_week)
        and (c.starts_at at time zone m.snapshot_timezone)::time >= m.snapshot_time_start
        and m.snapshot_time_end
          - (c.starts_at at time zone m.snapshot_timezone)::time >= interval '60 minutes'
      )
    )
    and not exists (
      select 1
      from tmp_auto_match_final_roster r
      join public.jugadores j on j.usuario_id = r.user_id
      join public.partidos pa on pa.id = j.partido_id
      where coalesce(lower(pa.estado), 'active')
              not in ('deleted', 'cancelado', 'cancelled', 'canceled', 'finalizado', 'finished', 'completed')
        and public.partido_kickoff_at(pa.fecha, pa.hora) is not null
        and public.auto_match_play_range(
              public.partido_kickoff_at(pa.fecha, pa.hora), pa.modalidad
            ) && public.auto_match_play_range(c.starts_at, v_proposal.format)
    )
  order by c.requested desc,
           abs(extract(epoch from (c.starts_at - v_requested_start))),
           c.starts_at
  limit 1;

  if v_final_start is null then
    raise exception 'no_compatible_final_time';
  end if;

  v_fecha := (v_final_start at time zone v_tz)::date;
  v_hora := to_char(v_final_start at time zone v_tz, 'HH24:MI');

  for v_attempt in 1..5 loop
    v_codigo := (
      select string_agg(substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', 1 + floor(random() * 32)::integer, 1), '')
      from generate_series(1, 6)
    );
    exit when not exists (select 1 from public.partidos where codigo = v_codigo);
    if v_attempt = 5 then raise exception 'match_code_generation_failed'; end if;
  end loop;

  v_match_ref := gen_random_uuid();
  insert into public.partidos (
    match_ref, codigo, nombre, fecha, hora, sede, sede_place_id, sede_direccion_normalizada,
    sede_latitud, sede_longitud, modalidad, cupo_jugadores, falta_jugadores, player_invites_enabled,
    tipo_partido, creado_por, precio_cancha_por_persona
  ) values (
    v_match_ref, v_codigo, v_nombre, v_fecha, v_hora,
    nullif(trim(coalesce(p_sede, '')), ''),
    nullif(trim(coalesce(p_sede_place_id, '')), ''),
    nullif(trim(coalesce(p_sede_direccion, '')), ''),
    p_sede_latitud, p_sede_longitud, v_proposal.format, v_proposal.max_players, false, false,
    coalesce(nullif(trim(coalesce(p_tipo_partido, '')), ''), 'Masculino'), auth.uid(), p_precio
  ) returning id into v_partido_id;

  insert into public.jugadores (
    partido_id, match_ref, usuario_id, nombre, avatar_url, score, is_goalkeeper, created_at
  )
  select
    v_partido_id, v_match_ref, r.user_id,
    coalesce(nullif(trim(u.nombre), ''), 'Jugador'), u.avatar_url, 5, false,
    now() + make_interval(secs => (r.seat - 1) * 0.001)
  from tmp_auto_match_final_roster r
  join public.usuarios u on u.id = r.user_id
  order by r.seat;

  select array_agg(r.user_id order by r.seat) into v_waitlist
  from (
    select m.user_id,
      row_number() over (order by m.confirmed_at asc nulls last, m.user_id) as seat
    from public.auto_match_proposal_members m
    where m.proposal_id = p_proposal_id and m.response = 'accepted'
  ) r
  where r.seat > v_final_cap;

  if v_waitlist is not null and array_length(v_waitlist, 1) > 0 then
    update public.auto_match_proposal_members
    set response = 'waitlisted', responded_at = now()
    where proposal_id = p_proposal_id and user_id = any(v_waitlist);
  end if;

  update public.auto_match_proposals
  set status = 'created',
      partido_id = v_partido_id,
      proposed_starts_at = v_final_start,
      updated_at = now()
  where id = p_proposal_id
  returning * into v_proposal;

  perform public.enqueue_auto_match_notification(
    p_proposal_id,
    'auto_match_created',
    '¡Partido confirmado!',
    format('%s ya tiene cancha, fecha y hora. Entrá para ver los detalles.', v_nombre),
    array(select r.user_id from tmp_auto_match_final_roster r order by r.seat),
    'created',
    jsonb_build_object('match_id', v_partido_id, 'partido_id', v_partido_id, 'route', '/partido-publico/' || v_partido_id)
  );

  if v_waitlist is not null and array_length(v_waitlist, 1) > 0 then
    perform public.enqueue_auto_match_notification(
      p_proposal_id,
      'auto_match_waitlisted',
      'El plantel se completó',
      'El partido se cerró con los primeros confirmados. Quedaste en lista de espera; tu disponibilidad sigue activa para otras combinaciones.',
      v_waitlist,
      'waitlisted_finalize',
      jsonb_build_object('route', '/quiero-jugar?auto=1')
    );
  end if;

  select count(*) into v_roster_count
  from public.jugadores where partido_id = v_partido_id;

  select array_agg(m.user_id) into v_pending
  from public.auto_match_proposal_members m
  where m.proposal_id = p_proposal_id and m.response = 'pending';

  if v_pending is not null and array_length(v_pending, 1) > 0 then
    if v_roster_count < v_final_cap then
      update public.auto_match_proposal_members
      set invite_expires_at = public.auto_match_invite_deadline(now(), v_final_start)
      where proposal_id = p_proposal_id and response = 'pending';

      perform public.enqueue_auto_match_notification(
        p_proposal_id,
        'auto_match_substitute_invite',
        'Los titulares ya están completos',
        '¿Querés sumarte como suplente? Entrá para confirmar tu lugar.',
        v_pending,
        'substitute_invite',
        jsonb_build_object(
          'partido_id', v_partido_id,
          'route', '/quiero-jugar?auto=1&invite=' || p_proposal_id,
          'slot_kind', 'suplente'
        )
      );
    else
      update public.auto_match_proposal_members
      set response = 'waitlisted', responded_at = now()
      where proposal_id = p_proposal_id and response = 'pending';

      perform public.enqueue_auto_match_notification(
        p_proposal_id,
        'auto_match_waitlisted',
        'El plantel se completó',
        'El partido se cerró con el banco lleno. Quedaste en lista de espera; tu disponibilidad sigue activa.',
        v_pending,
        'waitlisted_pending',
        jsonb_build_object('route', '/quiero-jugar?auto=1')
      );
    end if;
  end if;

  return v_proposal;
end;
$$;

-- Repair live rooms after replacing the buggy cross-schedule behavior. This is
-- idempotent and contains no hard-coded production identifiers.
do $$
declare
  v_row record;
begin
  for v_row in
    select p.id
    from public.auto_match_proposals p
    where p.status in ('collecting', 'ready') and p.expires_at > now()
    order by p.id
  loop
    perform * from public.reconcile_auto_match_proposal_members(v_row.id);
  end loop;
end;
$$;

revoke all on function public.user_has_overlapping_auto_match(uuid,timestamptz,bigint) from public, anon, authenticated, service_role;
revoke all on function public.user_declined_auto_match_slot(uuid,text,timestamptz) from public, anon, authenticated, service_role;
revoke all on function public.backfill_auto_match_proposal_members(bigint) from public, anon, authenticated, service_role;
revoke all on function public.reconcile_auto_match_proposal_members(bigint) from public, anon, authenticated, service_role;
revoke all on function public.enforce_auto_match_member_eligibility() from public, anon, authenticated, service_role;
revoke all on function public.respond_to_auto_match_proposal(bigint,text,boolean) from public, anon;
grant execute on function public.respond_to_auto_match_proposal(bigint,text,boolean) to authenticated;
revoke all on function public.finalize_auto_match_proposal(bigint,text,date,text,text,numeric,text,text,text,double precision,double precision) from public, anon;
grant execute on function public.finalize_auto_match_proposal(bigint,text,date,text,text,numeric,text,text,text,double precision,double precision) to authenticated;

commit;
