import json,collections,pathlib,hashlib,re
from lab import BASE,ROOT
h=json.loads((BASE/'evidence/history-catalog.json').read_text());b=json.loads((BASE/'evidence/baseline-catalog.json').read_text());events=json.loads((BASE/'evidence/history-transitions.json').read_text())
meta={t['name']:t for t in b['tables']};lines=['# Inventario final Torneos — Phase 2','', 'Catálogo derivado de las 48 fuentes verificadas y catálogo instalado del baseline candidato. Los nombres históricos de columnas `user_id`, `arma2_user_id`, `created_by`, etc. contienen UUID **locales** de `torneos_identity.id`; `core_user_id` es la correspondencia externa. No se migraron datos Core.','', 'Los JSON en `evidence/` contienen definiciones completas. Este inventario presenta cada objeto final y sus permisos.','', '## Schemas, tipos, extensiones y vistas','', '- Baseline: `public`, `private`, `extensions`; Postgres aporta `pg_catalog` e `information_schema`.','- Extensiones de la DB candidata: `plpgsql`, `pgcrypto` (en `extensions`). `plpgsql_check` se instaló sólo dentro de una transacción de diagnóstico y se revirtió.','- No hay enums de usuario ni vistas/materialized views finales. Tipos compuestos de fila corresponden a las tablas.','- Referencia: `auth` y cuatro tablas Core son sustitutos estructurales vacíos, nunca se incluyen en el baseline. `storage` en referencia modela sólo las columnas utilizadas; no es una instalación completa del servicio Storage.','', '## Tablas finales: 103 históricas + identidad local','']
for t in b['tables']:
 lines+=['### '+t['name'],'',f"RLS: {t['rls']}; FORCE RLS: {t['force_rls']}. ACL: `{t['acl']}`. ACL nula conserva solamente los permisos implícitos del propietario.",'','| Columna | Tipo | NOT NULL | Default |','|---|---|---|---|']
 for c in t['columns']:lines.append('| '+c['name']+' | '+c['type']+' | '+str(c['not_null'])+' | '+str(c['default']).replace('|','\\|')+' |')
 lines+=['','Constraints:','']
 for x in t['constraints']:lines.append('- `'+x['name']+'`: `'+x['definition']+'`')
 lines+=['']
lines+=['## Políticas RLS finales','', '61 históricas conservadas con identidad adaptada + 2 de identity shadow. Las tablas internas sin políticas no permiten acceso a roles normales; se operan mediante RPC autorizadas o roles servidor. El owner de funciones SECURITY DEFINER conserva bypass; no se afirma FORCE RLS general.','']
for p in b['policies']:lines+=['### '+p['table']+'.'+p['name'],'',f"Operación: {p['command']}; roles: {', '.join(p['roles'])}.",'','```sql','USING: '+str(p['using']),'WITH CHECK: '+str(p['check']),'```','']
lines+=['## Funciones y grants','', f"{len(b['functions'])} funciones del candidato: 358 Torneos históricas, wrapper local gen_random_uuid, tres helpers privados de identidad, tres del boundary Core (Phase 2B) y uno de scope de temporada. Las {sum(1 for f in b['functions'] if f['security_definer'])} SECURITY DEFINER permanecen como RPC/helpers con sus ACL finales: moverlas de schema alteraría la API. Su disposición semántica está en evidence/security-definer-review.json (Phase 2B)." ,'']
for f in b['functions']:lines+=['### '+f['name']+'('+f['signature']+')','',f"Retorna `{f['result']}`; SECURITY DEFINER: `{f['security_definer']}`; settings: `{f['settings']}`; ACL: `{f['acl']}`.",'']
lines+=['## Triggers','']
for t in b['triggers']:lines+=['- `'+t['table']+'.'+t['name']+'`: `'+t['definition']+'`']
lines+=['','## Índices finales','', '367 históricos + PK y UNIQUE de identidad = 369. Comparación estructural: cero pares exactamente duplicados. No se eliminan índices sólo por compartir prefijos, porque pueden tener predicados, unicidad o contratos diferentes.','']
for i in b['indexes']:lines+=['- `'+i['name']+'`: `'+i['definition']+'`']
(BASE/'INVENTORY.md').write_text('\n'.join(lines).rstrip()+'\n')
lines=['# Resolución del historial 1–48','', 'Trazabilidad calculada por introspección antes/después de cada fuente. Las tablas de laboratorio Core existían antes del paso 1, por lo que no se confunden con tablas creadas por Torneos. `history-transitions.json` registra 1.402 eventos de creación/cambio/remoción con hashes de objeto y fuente. Un cambio de nombre aparece como remoción + creación, no implica perder sus datos.','', '## Renombres resueltos','', '- Paso 34: `tournament_entitlement_plans` → `tournament_legacy_subscription_plans`.','- Paso 34: `tournament_organization_subscriptions` → `tournament_legacy_organization_subscriptions`.','- Se conservan ambas tablas con su nombre final para compatibilidad/auditoría. No se reinstalan nombres antiguos ni el gate `first_free` como autoridad comercial.','', '## Objetos retirados o sustituidos','']
for e in events:
 if e['event']=='removed':lines.append(f"- Paso {e['step']}: `{e['object']}`. Fuente: `{e['source']}`.")
lines+=['', 'La firma eliminada de `complete_tournament_media_simple_upload` cambia sus nombres de parámetros; el catálogo final conserva la firma efectiva. `authorize_tournament_social_export` conserva la firma final ampliada. Los índices/trigger de tablas renombradas se registran bajo el nombre final. Las políticas de lectura de temporadas, torneos y categorías del paso 41 son reemplazadas por las de scope por temporada.','', '## Revisiones que no sobreviven en la instalación','', '- CREATE OR REPLACE de funciones, ALTER de columnas/constraints, grants transitorios y reemplazos de políticas se resuelven en sus definiciones finales.','- Se excluyen el ledger Core, receipts de promoción, `local_existing_functions`, hooks operacionales y el schema `lab_reference`.','- Los grants finales incluyen la revocación de defaults de cada nueva función que los ejecutables certificados aplicaban desde el paso 12. 48/48 hashes de esos ejecutables verificados; no se ejecutaron sus operadores.','- El baseline no contiene las cuatro tablas Core de referencia ni el helper Core `team_user_is_admin_or_owner`.','- Las funciones antiguas aún existentes en el catálogo se conservan, aunque algunas sean internas/legacy. No se presume obsolescencia sólo por el nombre; su retiro requiere comprobar consumidores y autorización.','', '## Conservados','', 'Los 103 nombres de tablas finales y las definiciones de 358 funciones históricas están en INVENTORY.md. Las diferencias de definición respecto del histórico están enumeradas una por una en evidence/intentional-function-differences.json (boundary Core, scope de temporada, relaciones temporales, portabilidad del owner); evidence/equivalence.json no deja ninguna diferencia sin motivo.','']
(BASE/'HISTORY.md').write_text('\n'.join(lines).rstrip()+'\n')
# Compact review ledger: explicit mechanical checks, never substitute for semantic audit.
review=[]
for f in b['functions']:
 if f['security_definer']:
  review.append({'function':f['name'],'signature':f['signature'],'fixed_search_path':f['settings']==['search_path=""'],'public_execute':any(a.startswith('=X') for a in f['acl'] or []),'acl':f['acl'],'direct_identity_check':'private.current_identity_id()' in f['definition'],'semantic_disposition':'see evidence/security-definer-review.json'})
# Mechanical ACL ledger only; the semantic disposition lives in evidence/security-definer-review.json (phase2b/semantic_review.py).
(BASE/'evidence/security-definer-acl-ledger.json').write_text(json.dumps(review,indent=2)+'\n')
# Seed equivalence ignores generated audit timestamps only, not business configuration.
