-- Transitional bootstrap for the pre-versioned Arma2 schema.
--
-- This file intentionally contains only the objects that existed before the
-- first tracked migration. It is used to replay the historical chain locally
-- and produce the final canonical baseline. No production data is required.

create extension if not exists pgcrypto;

-- Supabase installs pgcrypto in the non-exposed `extensions` schema. The
-- tournament RPCs qualify this compatibility helper as `public.digest`.
create function public.digest(data text, type text)
returns bytea
language sql
immutable
strict
set search_path = ''
as $$
  select extensions.digest(data, type)
$$;

create table public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  email text,
  avatar_url text,
  telefono text,
  ciudad text,
  localidad text,
  posicion text,
  ranking numeric not null default 0,
  partidos_jugados integer not null default 0,
  partidos_ganados integer not null default 0,
  partidos_perdidos integer not null default 0,
  partidos_empatados integer not null default 0,
  partidos_abandonados integer not null default 0,
  mvps integer not null default 0,
  guantes_dorados integer not null default 0,
  tarjetas_rojas integer not null default 0,
  acepta_invitaciones boolean not null default true,
  perfil_completo boolean not null default false,
  profile_completion integer not null default 0,
  latitud double precision,
  longitud double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  avatar_url text,
  telefono text,
  ciudad text,
  posicion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.partidos_frecuentes (
  id bigint generated by default as identity primary key,
  usuario_id uuid references public.usuarios(id) on delete cascade,
  creado_por uuid references public.usuarios(id) on delete cascade,
  nombre text,
  fecha date,
  hora text,
  sede text,
  "sedeMaps" jsonb,
  modalidad text,
  cupo_jugadores integer,
  falta_jugadores boolean not null default false,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.partidos (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid() unique,
  match_ref uuid unique,
  codigo text unique,
  nombre text,
  fecha date,
  hora text,
  sede text,
  "sedeMaps" jsonb,
  modalidad text,
  tipo_partido text,
  cupo_jugadores integer,
  falta_jugadores boolean not null default false,
  precio_cancha numeric,
  creado_por uuid references public.usuarios(id) on delete set null,
  admin_id uuid references public.usuarios(id) on delete set null,
  equipos_json jsonb,
  equipos_generados boolean not null default false,
  teams_confirmed boolean not null default false,
  awards_status text not null default 'pending',
  awards_resolved_at timestamptz,
  estado text not null default 'active',
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.jugadores (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid() unique,
  match_ref uuid,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  usuario_id uuid references public.usuarios(id) on delete set null,
  nombre text,
  avatar_url text,
  score numeric not null default 5,
  is_goalkeeper boolean not null default false,
  titular boolean not null default true,
  posicion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.votos (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  votante_id text not null,
  votado_id text not null,
  puntaje numeric not null,
  jugador_nombre text,
  jugador_avatar_url text,
  created_at timestamptz not null default now(),
  unique (partido_id, votante_id, votado_id)
);

create table public.public_voters (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  nombre text not null,
  token text unique,
  created_at timestamptz not null default now()
);

create table public.votos_publicos (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  public_voter_id bigint not null references public.public_voters(id) on delete cascade,
  votado_jugador_id bigint not null references public.jugadores(id) on delete cascade,
  puntaje numeric not null,
  votante_nombre text,
  created_at timestamptz not null default now(),
  unique (partido_id, public_voter_id, votado_jugador_id)
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  partido_id bigint references public.partidos(id) on delete cascade,
  type text not null,
  title text,
  message text,
  data jsonb not null default '{}'::jsonb,
  status text,
  read boolean not null default false,
  read_at timestamptz,
  send_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notification_delivery_log (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  partido_id bigint references public.partidos(id) on delete set null,
  user_id uuid references auth.users(id) on delete cascade,
  notification_type text not null,
  payload_json jsonb not null default '{}'::jsonb,
  channel text not null check (channel in ('in_app', 'push')),
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed', 'skipped')),
  error_text text,
  correlation_id uuid not null default gen_random_uuid(),
  attempt_count integer not null default 0,
  sent_at timestamptz,
  unique (user_id, partido_id, notification_type, correlation_id)
);

create table public.survey_progress (
  partido_id bigint primary key references public.partidos(id) on delete cascade,
  enabled_at timestamptz,
  first_response_at timestamptz,
  response_count integer not null default 0,
  results_notified boolean not null default false,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.survey_results (
  partido_id bigint primary key references public.partidos(id) on delete cascade,
  mvp uuid,
  golden_glove uuid,
  red_cards uuid[],
  awards jsonb not null default '{}'::jsonb,
  winner_team text,
  scoreline text,
  ready_at timestamptz,
  results_ready boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.partido_team_confirmations (
  partido_id bigint primary key references public.partidos(id) on delete cascade,
  confirmed_at timestamptz not null default now(),
  confirmed_by uuid references auth.users(id) on delete set null,
  team_a uuid[] not null,
  team_b uuid[] not null,
  teams_json jsonb not null
);

create table public.post_match_surveys (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  votante_id bigint not null references public.jugadores(id) on delete cascade,
  se_jugo boolean,
  motivo_no_jugado text,
  asistieron_todos boolean,
  jugadores_ausentes bigint[] not null default '{}'::bigint[],
  partido_limpio boolean,
  jugadores_violentos bigint[] not null default '{}'::bigint[],
  mejor_jugador_eq_a bigint,
  mejor_jugador_eq_b bigint,
  created_at timestamptz not null default now(),
  unique (partido_id, votante_id)
);

create table public.guest_match_invites (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  token text not null unique,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  max_uses integer not null default 14,
  uses_count integer not null default 0,
  revoked_at timestamptz
);

create table public.mensajes_partido (
  id bigint generated by default as identity primary key,
  partido_id bigint references public.partidos(id) on delete cascade,
  team_match_id uuid,
  autor text,
  mensaje text not null,
  user_id uuid references auth.users(id) on delete set null,
  "timestamp" timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.player_awards (
  id bigint generated by default as identity primary key,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  jugador_id uuid not null,
  user_id uuid references public.usuarios(id) on delete cascade,
  award_type text not null,
  created_at timestamptz not null default now()
);

create table public.amigos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  friend_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, friend_id)
);

create table public.partidos_manuales (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  tipo_partido text not null check (tipo_partido in ('amistoso', 'torneo')),
  resultado text not null check (resultado in ('ganaste', 'perdiste', 'empate')),
  fecha date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.match_join_requests (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.partidos(id) on delete cascade,
  user_id uuid not null references public.usuarios(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid references public.usuarios(id)
);

create table public.lesiones (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  tipo_lesion text not null,
  fecha_inicio date not null,
  fecha_fin date,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.player_absences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.usuarios(id) on delete cascade,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  reason text,
  created_at timestamptz not null default now(),
  unique (user_id, partido_id)
);

create table public.cleared_matches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.usuarios(id) on delete cascade,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  cleared_at timestamptz not null default now(),
  unique (user_id, partido_id)
);

create view public.notifications_ext
with (security_invoker = true)
as
select
  n.*,
  p.nombre as partido_nombre,
  p.fecha as partido_fecha,
  p.hora as partido_hora,
  p.sede as partido_sede
from public.notifications n
left join public.partidos p on p.id = n.partido_id;

create view public.partidos_view
with (security_invoker = true)
as
select p.*
from public.partidos p
where p.deleted_at is null;

create view public.partidos_jugadores
with (security_invoker = true)
as
select
  p.id as partido_id,
  j.id as jugador_id,
  j.usuario_id,
  j.nombre,
  j.avatar_url,
  j.score,
  j.is_goalkeeper
from public.partidos p
join public.jugadores j on j.partido_id = p.id;

alter table public.usuarios enable row level security;
alter table public.profiles enable row level security;
alter table public.partidos_frecuentes enable row level security;
alter table public.partidos enable row level security;
alter table public.jugadores enable row level security;
alter table public.votos enable row level security;
alter table public.public_voters enable row level security;
alter table public.votos_publicos enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_delivery_log enable row level security;
alter table public.survey_progress enable row level security;
alter table public.survey_results enable row level security;
alter table public.partido_team_confirmations enable row level security;
alter table public.post_match_surveys enable row level security;
alter table public.guest_match_invites enable row level security;
alter table public.mensajes_partido enable row level security;
alter table public.player_awards enable row level security;
alter table public.amigos enable row level security;
alter table public.partidos_manuales enable row level security;
alter table public.match_join_requests enable row level security;
alter table public.lesiones enable row level security;
alter table public.player_absences enable row level security;
alter table public.cleared_matches enable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to authenticated, service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
